<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Recipe;
use App\Models\Ingredient;

class AdditionalFlutterRecipesSeeder extends Seeder
{
    public function run(): void
    {
        $this->createAdditionalRecipes();
    }

    private function createAdditionalRecipes(): void
    {
        // Batch 2: Healthy Filipino Dishes (30 recipes)
        $recipes = [
            [
                'name' => 'Ginataang Gulay',
                'description' => 'Mixed vegetables in coconut milk',
                'prep_time' => 15,
                'cook_time' => 20,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Healthy',
                'calories_per_serving' => 120,
                'protein_per_serving' => 4,
                'carbs_per_serving' => 18,
                'fat_per_serving' => 3,
                'instructions' => 'Cook mixed vegetables in coconut milk with spices',
                'is_filipino_dish' => true,
                'ingredients' => ['mixed vegetables', 'coconut milk', 'onion', 'garlic', 'ginger', 'chili'],
            ],
            [
                'name' => 'Tinolang Manok',
                'description' => 'Filipino chicken soup with vegetables',
                'prep_time' => 15,
                'cook_time' => 30,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Healthy',
                'calories_per_serving' => 180,
                'protein_per_serving' => 22,
                'carbs_per_serving' => 8,
                'fat_per_serving' => 6,
                'instructions' => 'Simmer chicken with vegetables in broth',
                'is_filipino_dish' => true,
                'ingredients' => ['chicken', 'potato', 'carrot', 'onion', 'garlic', 'ginger'],
            ],
            [
                'name' => 'Chicken Tinola',
                'description' => 'Traditional Filipino chicken soup',
                'prep_time' => 15,
                'cook_time' => 25,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Healthy',
                'calories_per_serving' => 160,
                'protein_per_serving' => 20,
                'carbs_per_serving' => 6,
                'fat_per_serving' => 5,
                'instructions' => 'Boil chicken with ginger, onion, and vegetables',
                'is_filipino_dish' => true,
                'ingredients' => ['chicken', 'ginger', 'onion', 'garlic', 'chayote', 'morning glory'],
            ],
            [
                'name' => 'Adobong Kangkong',
                'description' => 'Stir-fried water spinach in adobo sauce',
                'prep_time' => 10,
                'cook_time' => 15,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Healthy',
                'calories_per_serving' => 45,
                'protein_per_serving' => 3,
                'carbs_per_serving' => 6,
                'fat_per_serving' => 1,
                'instructions' => 'Stir-fry kangkong with garlic, soy sauce, and vinegar',
                'is_filipino_dish' => true,
                'ingredients' => ['morning glory', 'garlic', 'soy sauce', 'vinegar', 'onion'],
            ],
            [
                'name' => 'Ginataang Kalabasa',
                'description' => 'Squash in coconut milk',
                'prep_time' => 10,
                'cook_time' => 20,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Healthy',
                'calories_per_serving' => 80,
                'protein_per_serving' => 3,
                'carbs_per_serving' => 12,
                'fat_per_serving' => 2,
                'instructions' => 'Cook squash in coconut milk with spices',
                'is_filipino_dish' => true,
                'ingredients' => ['squash', 'coconut milk', 'onion', 'garlic', 'ginger', 'chili'],
            ],
            [
                'name' => 'Pinakbet',
                'description' => 'Mixed vegetables with shrimp paste',
                'prep_time' => 15,
                'cook_time' => 25,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Healthy',
                'calories_per_serving' => 90,
                'protein_per_serving' => 5,
                'carbs_per_serving' => 15,
                'fat_per_serving' => 2,
                'instructions' => 'Cook mixed vegetables with bagoong',
                'is_filipino_dish' => true,
                'ingredients' => ['eggplant', 'okra', 'bitter gourd', 'string beans', 'squash', 'bagoong'],
            ],
            [
                'name' => 'Laing',
                'description' => 'Taro leaves in coconut milk',
                'prep_time' => 15,
                'cook_time' => 30,
                'servings' => 4,
                'difficulty' => 'Medium',
                'category' => 'Healthy',
                'calories_per_serving' => 120,
                'protein_per_serving' => 6,
                'carbs_per_serving' => 18,
                'fat_per_serving' => 3,
                'instructions' => 'Cook taro leaves in coconut milk with spices',
                'is_filipino_dish' => true,
                'ingredients' => ['taro leaves', 'coconut milk', 'onion', 'garlic', 'ginger', 'chili'],
            ],
            [
                'name' => 'Ginataang Langka',
                'description' => 'Jackfruit in coconut milk',
                'prep_time' => 10,
                'cook_time' => 20,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Healthy',
                'calories_per_serving' => 100,
                'protein_per_serving' => 4,
                'carbs_per_serving' => 16,
                'fat_per_serving' => 2,
                'instructions' => 'Cook jackfruit in coconut milk with spices',
                'is_filipino_dish' => true,
                'ingredients' => ['jackfruit', 'coconut milk', 'onion', 'garlic', 'ginger', 'chili'],
            ],
            [
                'name' => 'Ginataang Sitaw',
                'description' => 'String beans in coconut milk',
                'prep_time' => 10,
                'cook_time' => 15,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Healthy',
                'calories_per_serving' => 70,
                'protein_per_serving' => 3,
                'carbs_per_serving' => 10,
                'fat_per_serving' => 2,
                'instructions' => 'Cook string beans in coconut milk',
                'is_filipino_dish' => true,
                'ingredients' => ['string beans', 'coconut milk', 'onion', 'garlic', 'ginger'],
            ],
            [
                'name' => 'Ginataang Kalabasa at Sitaw',
                'description' => 'Squash and string beans in coconut milk',
                'prep_time' => 10,
                'cook_time' => 20,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Healthy',
                'calories_per_serving' => 85,
                'protein_per_serving' => 3,
                'carbs_per_serving' => 14,
                'fat_per_serving' => 2,
                'instructions' => 'Cook squash and string beans in coconut milk',
                'is_filipino_dish' => true,
                'ingredients' => ['squash', 'string beans', 'coconut milk', 'onion', 'garlic', 'ginger'],
            ],
            [
                'name' => 'Ginataang Hipon',
                'description' => 'Shrimp in coconut milk',
                'prep_time' => 10,
                'cook_time' => 15,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Healthy',
                'calories_per_serving' => 150,
                'protein_per_serving' => 18,
                'carbs_per_serving' => 8,
                'fat_per_serving' => 4,
                'instructions' => 'Cook shrimp in coconut milk with vegetables',
                'is_filipino_dish' => true,
                'ingredients' => ['shrimp', 'coconut milk', 'vegetables', 'onion', 'garlic', 'ginger'],
            ],
            [
                'name' => 'Ginataang Alimango',
                'description' => 'Crab in coconut milk',
                'prep_time' => 15,
                'cook_time' => 20,
                'servings' => 4,
                'difficulty' => 'Medium',
                'category' => 'Healthy',
                'calories_per_serving' => 180,
                'protein_per_serving' => 22,
                'carbs_per_serving' => 8,
                'fat_per_serving' => 6,
                'instructions' => 'Cook crab in coconut milk with vegetables',
                'is_filipino_dish' => true,
                'ingredients' => ['crab', 'coconut milk', 'vegetables', 'onion', 'garlic', 'ginger'],
            ],
            [
                'name' => 'Ginataang Pusit',
                'description' => 'Squid in coconut milk',
                'prep_time' => 15,
                'cook_time' => 20,
                'servings' => 4,
                'difficulty' => 'Medium',
                'category' => 'Healthy',
                'calories_per_serving' => 160,
                'protein_per_serving' => 20,
                'carbs_per_serving' => 8,
                'fat_per_serving' => 5,
                'instructions' => 'Cook squid in coconut milk with vegetables',
                'is_filipino_dish' => true,
                'ingredients' => ['squid', 'coconut milk', 'vegetables', 'onion', 'garlic', 'ginger'],
            ],
            [
                'name' => 'Ginataang Tahong',
                'description' => 'Mussels in coconut milk',
                'prep_time' => 15,
                'cook_time' => 20,
                'servings' => 4,
                'difficulty' => 'Medium',
                'category' => 'Healthy',
                'calories_per_serving' => 140,
                'protein_per_serving' => 16,
                'carbs_per_serving' => 8,
                'fat_per_serving' => 4,
                'instructions' => 'Cook mussels in coconut milk with vegetables',
                'is_filipino_dish' => true,
                'ingredients' => ['mussel', 'coconut milk', 'vegetables', 'onion', 'garlic', 'ginger'],
            ],
            [
                'name' => 'Ginataang Talaba',
                'description' => 'Oysters in coconut milk',
                'prep_time' => 15,
                'cook_time' => 20,
                'servings' => 4,
                'difficulty' => 'Medium',
                'category' => 'Healthy',
                'calories_per_serving' => 130,
                'protein_per_serving' => 14,
                'carbs_per_serving' => 8,
                'fat_per_serving' => 4,
                'instructions' => 'Cook oysters in coconut milk with vegetables',
                'is_filipino_dish' => true,
                'ingredients' => ['oyster', 'coconut milk', 'vegetables', 'onion', 'garlic', 'ginger'],
            ],
            [
                'name' => 'Ginataang Manok',
                'description' => 'Chicken in coconut milk',
                'prep_time' => 15,
                'cook_time' => 30,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Healthy',
                'calories_per_serving' => 220,
                'protein_per_serving' => 25,
                'carbs_per_serving' => 8,
                'fat_per_serving' => 10,
                'instructions' => 'Cook chicken in coconut milk with vegetables',
                'is_filipino_dish' => true,
                'ingredients' => ['chicken', 'coconut milk', 'vegetables', 'onion', 'garlic', 'ginger'],
            ],
            [
                'name' => 'Ginataang Baboy',
                'description' => 'Pork in coconut milk',
                'prep_time' => 15,
                'cook_time' => 30,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Healthy',
                'calories_per_serving' => 280,
                'protein_per_serving' => 22,
                'carbs_per_serving' => 8,
                'fat_per_serving' => 16,
                'instructions' => 'Cook pork in coconut milk with vegetables',
                'is_filipino_dish' => true,
                'ingredients' => ['pork', 'coconut milk', 'vegetables', 'onion', 'garlic', 'ginger'],
            ],
            [
                'name' => 'Ginataang Baka',
                'description' => 'Beef in coconut milk',
                'prep_time' => 15,
                'cook_time' => 45,
                'servings' => 4,
                'difficulty' => 'Medium',
                'category' => 'Healthy',
                'calories_per_serving' => 320,
                'protein_per_serving' => 28,
                'carbs_per_serving' => 8,
                'fat_per_serving' => 18,
                'instructions' => 'Cook beef in coconut milk with vegetables',
                'is_filipino_dish' => true,
                'ingredients' => ['beef', 'coconut milk', 'vegetables', 'onion', 'garlic', 'ginger'],
            ],
            [
                'name' => 'Ginataang Isda',
                'description' => 'Fish in coconut milk',
                'prep_time' => 15,
                'cook_time' => 20,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Healthy',
                'calories_per_serving' => 180,
                'protein_per_serving' => 20,
                'carbs_per_serving' => 8,
                'fat_per_serving' => 6,
                'instructions' => 'Cook fish in coconut milk with vegetables',
                'is_filipino_dish' => true,
                'ingredients' => ['fish', 'coconut milk', 'vegetables', 'onion', 'garlic', 'ginger'],
            ],
            [
                'name' => 'Ginataang Kamote',
                'description' => 'Sweet potato in coconut milk',
                'prep_time' => 10,
                'cook_time' => 20,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Healthy',
                'calories_per_serving' => 120,
                'protein_per_serving' => 3,
                'carbs_per_serving' => 22,
                'fat_per_serving' => 2,
                'instructions' => 'Cook sweet potato in coconut milk',
                'is_filipino_dish' => true,
                'ingredients' => ['sweet potato', 'coconut milk', 'onion', 'garlic', 'ginger'],
            ],
            [
                'name' => 'Ginataang Gabi',
                'description' => 'Taro in coconut milk',
                'prep_time' => 10,
                'cook_time' => 20,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Healthy',
                'calories_per_serving' => 110,
                'protein_per_serving' => 3,
                'carbs_per_serving' => 20,
                'fat_per_serving' => 2,
                'instructions' => 'Cook taro in coconut milk',
                'is_filipino_dish' => true,
                'ingredients' => ['gabi', 'coconut milk', 'onion', 'garlic', 'ginger'],
            ],
            [
                'name' => 'Ginataang Kamoteng Kahoy',
                'description' => 'Cassava in coconut milk',
                'prep_time' => 10,
                'cook_time' => 20,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Healthy',
                'calories_per_serving' => 130,
                'protein_per_serving' => 3,
                'carbs_per_serving' => 24,
                'fat_per_serving' => 2,
                'instructions' => 'Cook cassava in coconut milk',
                'is_filipino_dish' => true,
                'ingredients' => ['cassava', 'coconut milk', 'onion', 'garlic', 'ginger'],
            ],
            [
                'name' => 'Ginataang Mais',
                'description' => 'Corn in coconut milk',
                'prep_time' => 10,
                'cook_time' => 15,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Healthy',
                'calories_per_serving' => 100,
                'protein_per_serving' => 4,
                'carbs_per_serving' => 16,
                'fat_per_serving' => 2,
                'instructions' => 'Cook corn in coconut milk',
                'is_filipino_dish' => true,
                'ingredients' => ['corn', 'coconut milk', 'onion', 'garlic', 'ginger'],
            ],
            [
                'name' => 'Ginataang Labong',
                'description' => 'Bamboo shoots in coconut milk',
                'prep_time' => 15,
                'cook_time' => 20,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Healthy',
                'calories_per_serving' => 80,
                'protein_per_serving' => 4,
                'carbs_per_serving' => 12,
                'fat_per_serving' => 2,
                'instructions' => 'Cook bamboo shoots in coconut milk',
                'is_filipino_dish' => true,
                'ingredients' => ['bamboo shoots', 'coconut milk', 'onion', 'garlic', 'ginger'],
            ],
            [
                'name' => 'Ginataang Kabute',
                'description' => 'Mushrooms in coconut milk',
                'prep_time' => 10,
                'cook_time' => 15,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Healthy',
                'calories_per_serving' => 90,
                'protein_per_serving' => 5,
                'carbs_per_serving' => 10,
                'fat_per_serving' => 3,
                'instructions' => 'Cook mushrooms in coconut milk',
                'is_filipino_dish' => true,
                'ingredients' => ['mushroom', 'coconut milk', 'onion', 'garlic', 'ginger'],
            ],
            [
                'name' => 'Ginataang Toge',
                'description' => 'Bean sprouts in coconut milk',
                'prep_time' => 10,
                'cook_time' => 10,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Healthy',
                'calories_per_serving' => 60,
                'protein_per_serving' => 4,
                'carbs_per_serving' => 8,
                'fat_per_serving' => 1,
                'instructions' => 'Cook bean sprouts in coconut milk',
                'is_filipino_dish' => true,
                'ingredients' => ['bean sprouts', 'coconut milk', 'onion', 'garlic', 'ginger'],
            ],
            [
                'name' => 'Ginataang Saging',
                'description' => 'Banana in coconut milk',
                'prep_time' => 10,
                'cook_time' => 15,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Healthy',
                'calories_per_serving' => 110,
                'protein_per_serving' => 2,
                'carbs_per_serving' => 20,
                'fat_per_serving' => 2,
                'instructions' => 'Cook banana in coconut milk',
                'is_filipino_dish' => true,
                'ingredients' => ['banana', 'coconut milk', 'onion', 'garlic', 'ginger'],
            ],
            [
                'name' => 'Ginataang Mangga',
                'description' => 'Mango in coconut milk',
                'prep_time' => 10,
                'cook_time' => 15,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Healthy',
                'calories_per_serving' => 100,
                'protein_per_serving' => 2,
                'carbs_per_serving' => 18,
                'fat_per_serving' => 2,
                'instructions' => 'Cook mango in coconut milk',
                'is_filipino_dish' => true,
                'ingredients' => ['mango', 'coconut milk', 'onion', 'garlic', 'ginger'],
            ],
            [
                'name' => 'Ginataang Pinya',
                'description' => 'Pineapple in coconut milk',
                'prep_time' => 10,
                'cook_time' => 15,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Healthy',
                'calories_per_serving' => 90,
                'protein_per_serving' => 2,
                'carbs_per_serving' => 16,
                'fat_per_serving' => 2,
                'instructions' => 'Cook pineapple in coconut milk',
                'is_filipino_dish' => true,
                'ingredients' => ['pineapple', 'coconut milk', 'onion', 'garlic', 'ginger'],
            ],
            [
                'name' => 'Ginataang Papaya',
                'description' => 'Papaya in coconut milk',
                'prep_time' => 10,
                'cook_time' => 15,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Healthy',
                'calories_per_serving' => 80,
                'protein_per_serving' => 2,
                'carbs_per_serving' => 14,
                'fat_per_serving' => 2,
                'instructions' => 'Cook papaya in coconut milk',
                'is_filipino_dish' => true,
                'ingredients' => ['papaya', 'coconut milk', 'onion', 'garlic', 'ginger'],
            ],
            [
                'name' => 'Ginataang Niyog',
                'description' => 'Coconut in coconut milk',
                'prep_time' => 15,
                'cook_time' => 20,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Healthy',
                'calories_per_serving' => 140,
                'protein_per_serving' => 3,
                'carbs_per_serving' => 12,
                'fat_per_serving' => 8,
                'instructions' => 'Cook coconut in coconut milk',
                'is_filipino_dish' => true,
                'ingredients' => ['coconut', 'coconut milk', 'onion', 'garlic', 'ginger'],
            ],
        ];

        foreach ($recipes as $recipeData) {
            $ingredients = $recipeData['ingredients'];
            unset($recipeData['ingredients']);

            $recipe = Recipe::firstOrCreate(
                ['name' => $recipeData['name']],
                $recipeData
            );

            foreach ($ingredients as $ingredientName) {
                $ingredient = Ingredient::where('name', $ingredientName)->first();
                if ($ingredient && !$recipe->ingredients()->where('ingredient_id', $ingredient->id)->exists()) {
                    $recipe->ingredients()->attach($ingredient->id, [
                        'quantity' => '1',
                        'unit' => 'piece'
                    ]);
                }
            }
        }
    }
}
