<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Recipe;
use App\Models\Ingredient;

class AdditionalBreakfastFoodsSeeder extends Seeder
{
    public function run(): void
    {
        // Create additional breakfast ingredients first
        $this->createBreakfastIngredients();
        
        // Create additional Filipino breakfast recipes
        $this->createBreakfastRecipes();
    }

    private function createBreakfastIngredients(): void
    {
        $ingredients = [
            // Additional Breakfast Proteins
            ['name' => 'tocino', 'category' => 'Protein', 'description' => 'Sweet cured pork'],
            ['name' => 'corned beef', 'category' => 'Protein', 'description' => 'Canned corned beef'],
            ['name' => 'spam', 'category' => 'Protein', 'description' => 'Canned luncheon meat'],
            ['name' => 'hotdog', 'category' => 'Protein', 'description' => 'Filipino hotdog'],
            ['name' => 'bacon', 'category' => 'Protein', 'description' => 'Bacon strips'],
            ['name' => 'ham', 'category' => 'Protein', 'description' => 'Sliced ham'],
            ['name' => 'chorizo', 'category' => 'Protein', 'description' => 'Spanish sausage'],
            ['name' => 'vienna sausage', 'category' => 'Protein', 'description' => 'Canned vienna sausage'],
            ['name' => 'sardines in tomato sauce', 'category' => 'Protein', 'description' => 'Canned sardines in tomato sauce'],
            ['name' => 'tuna flakes', 'category' => 'Protein', 'description' => 'Canned tuna flakes'],
            
            // Additional Breakfast Grains & Starches
            ['name' => 'ensaymada', 'category' => 'Bread', 'description' => 'Sweet bread with cheese'],
            ['name' => 'pan de sal', 'category' => 'Bread', 'description' => 'Filipino bread'],
            ['name' => 'monay', 'category' => 'Bread', 'description' => 'Filipino bread roll'],
            ['name' => 'puto', 'category' => 'Rice Cake', 'description' => 'Steamed rice cake'],
            ['name' => 'kutsinta', 'category' => 'Rice Cake', 'description' => 'Brown rice cake'],
            ['name' => 'pichi-pichi', 'category' => 'Rice Cake', 'description' => 'Cassava rice cake'],
            ['name' => 'sapin-sapin', 'category' => 'Rice Cake', 'description' => 'Layered rice cake'],
            ['name' => 'biko', 'category' => 'Rice Cake', 'description' => 'Sweet sticky rice'],
            ['name' => 'suman', 'category' => 'Rice Cake', 'description' => 'Wrapped sticky rice'],
            
            // Additional Breakfast Vegetables & Fruits
            ['name' => 'green papaya', 'category' => 'Fruit', 'description' => 'Unripe papaya'],
            ['name' => 'ripe papaya', 'category' => 'Fruit', 'description' => 'Ripe papaya'],
            ['name' => 'ripe mango', 'category' => 'Fruit', 'description' => 'Sweet ripe mango'],
            ['name' => 'lacatan banana', 'category' => 'Fruit', 'description' => 'Sweet banana variety'],
            ['name' => 'avocado', 'category' => 'Fruit', 'description' => 'Avocado fruit'],
            ['name' => 'watermelon', 'category' => 'Fruit', 'description' => 'Fresh watermelon'],
            
            // Additional Breakfast Condiments & Sauces
            ['name' => 'margarine', 'category' => 'Dairy', 'description' => 'Margarine spread'],
            ['name' => 'cheddar cheese', 'category' => 'Dairy', 'description' => 'Cheddar cheese'],
            ['name' => 'queso de bola', 'category' => 'Dairy', 'description' => 'Edam cheese'],
            ['name' => 'evaporated milk', 'category' => 'Dairy', 'description' => 'Evaporated milk'],
            ['name' => 'coconut cream', 'category' => 'Dairy', 'description' => 'Coconut cream'],
            ['name' => 'mayonnaise', 'category' => 'Condiment', 'description' => 'Mayonnaise'],
            
            // Additional Breakfast Spices & Seasonings
            ['name' => 'vanilla extract', 'category' => 'Flavoring', 'description' => 'Vanilla extract'],
            ['name' => 'nutmeg', 'category' => 'Spice', 'description' => 'Nutmeg powder'],
            ['name' => 'cardamom', 'category' => 'Spice', 'description' => 'Cardamom powder'],
            ['name' => 'star anise', 'category' => 'Spice', 'description' => 'Star anise'],
            ['name' => 'cloves', 'category' => 'Spice', 'description' => 'Cloves'],
            ['name' => 'allspice', 'category' => 'Spice', 'description' => 'Allspice powder'],
        ];

        foreach ($ingredients as $ingredient) {
            Ingredient::firstOrCreate(
                ['name' => $ingredient['name']],
                $ingredient
            );
        }
    }

    private function createBreakfastRecipes(): void
    {
        $recipes = [
            // Traditional Filipino Breakfast Dishes
            [
                'name' => 'Tocilog',
                'description' => 'Tocino, Sinangag, at Itlog - Sweet cured pork with garlic rice and egg',
                'prep_time' => 10,
                'cook_time' => 20,
                'servings' => 2,
                'difficulty' => 'Easy',
                'category' => 'Filipino',
                'calories_per_serving' => 580,
                'protein_per_serving' => 32,
                'carbs_per_serving' => 58,
                'fat_per_serving' => 22,
                'instructions' => 'Cook tocino until caramelized, prepare garlic rice, fry egg',
                'is_filipino_dish' => true,
                'ingredients' => ['tocino', 'garlic rice', 'egg', 'garlic', 'soy sauce'],
            ],
            [
                'name' => 'Cornsilog',
                'description' => 'Corned beef, Sinangag, at Itlog - Corned beef with garlic rice and egg',
                'prep_time' => 5,
                'cook_time' => 15,
                'servings' => 2,
                'difficulty' => 'Easy',
                'category' => 'Filipino',
                'calories_per_serving' => 520,
                'protein_per_serving' => 28,
                'carbs_per_serving' => 58,
                'fat_per_serving' => 18,
                'instructions' => 'Sauté corned beef with onions, prepare garlic rice, fry egg',
                'is_filipino_dish' => true,
                'ingredients' => ['corned beef', 'garlic rice', 'egg', 'onion', 'garlic'],
            ],
            [
                'name' => 'Spamsilog',
                'description' => 'Spam, Sinangag, at Itlog - Spam with garlic rice and egg',
                'prep_time' => 5,
                'cook_time' => 15,
                'servings' => 2,
                'difficulty' => 'Easy',
                'category' => 'Filipino',
                'calories_per_serving' => 540,
                'protein_per_serving' => 26,
                'carbs_per_serving' => 58,
                'fat_per_serving' => 20,
                'instructions' => 'Fry spam slices, prepare garlic rice, fry egg',
                'is_filipino_dish' => true,
                'ingredients' => ['spam', 'garlic rice', 'egg', 'garlic', 'soy sauce'],
            ],
            [
                'name' => 'Hotdogsilog',
                'description' => 'Hotdog, Sinangag, at Itlog - Filipino hotdog with garlic rice and egg',
                'prep_time' => 5,
                'cook_time' => 15,
                'servings' => 2,
                'difficulty' => 'Easy',
                'category' => 'Filipino',
                'calories_per_serving' => 500,
                'protein_per_serving' => 24,
                'carbs_per_serving' => 58,
                'fat_per_serving' => 16,
                'instructions' => 'Fry hotdog, prepare garlic rice, fry egg',
                'is_filipino_dish' => true,
                'ingredients' => ['hotdog', 'garlic rice', 'egg', 'garlic', 'soy sauce'],
            ],
            [
                'name' => 'Baconsilog',
                'description' => 'Bacon, Sinangag, at Itlog - Bacon with garlic rice and egg',
                'prep_time' => 5,
                'cook_time' => 15,
                'servings' => 2,
                'difficulty' => 'Easy',
                'category' => 'Filipino',
                'calories_per_serving' => 560,
                'protein_per_serving' => 30,
                'carbs_per_serving' => 58,
                'fat_per_serving' => 24,
                'instructions' => 'Fry bacon until crispy, prepare garlic rice, fry egg',
                'is_filipino_dish' => true,
                'ingredients' => ['bacon', 'garlic rice', 'egg', 'garlic', 'soy sauce'],
            ],
            [
                'name' => 'Hamsilog',
                'description' => 'Ham, Sinangag, at Itlog - Ham with garlic rice and egg',
                'prep_time' => 5,
                'cook_time' => 10,
                'servings' => 2,
                'difficulty' => 'Easy',
                'category' => 'Filipino',
                'calories_per_serving' => 480,
                'protein_per_serving' => 28,
                'carbs_per_serving' => 58,
                'fat_per_serving' => 14,
                'instructions' => 'Heat ham slices, prepare garlic rice, fry egg',
                'is_filipino_dish' => true,
                'ingredients' => ['ham', 'garlic rice', 'egg', 'garlic', 'soy sauce'],
            ],
            [
                'name' => 'Chorisilog',
                'description' => 'Chorizo, Sinangag, at Itlog - Spanish sausage with garlic rice and egg',
                'prep_time' => 5,
                'cook_time' => 15,
                'servings' => 2,
                'difficulty' => 'Easy',
                'category' => 'Filipino',
                'calories_per_serving' => 520,
                'protein_per_serving' => 26,
                'carbs_per_serving' => 58,
                'fat_per_serving' => 18,
                'instructions' => 'Cook chorizo, prepare garlic rice, fry egg',
                'is_filipino_dish' => true,
                'ingredients' => ['chorizo', 'garlic rice', 'egg', 'garlic', 'soy sauce'],
            ],
            [
                'name' => 'Viennasilog',
                'description' => 'Vienna Sausage, Sinangag, at Itlog - Vienna sausage with garlic rice and egg',
                'prep_time' => 5,
                'cook_time' => 10,
                'servings' => 2,
                'difficulty' => 'Easy',
                'category' => 'Filipino',
                'calories_per_serving' => 460,
                'protein_per_serving' => 22,
                'carbs_per_serving' => 58,
                'fat_per_serving' => 14,
                'instructions' => 'Heat vienna sausage, prepare garlic rice, fry egg',
                'is_filipino_dish' => true,
                'ingredients' => ['vienna sausage', 'garlic rice', 'egg', 'garlic', 'soy sauce'],
            ],
            [
                'name' => 'Sardinesilog',
                'description' => 'Sardines, Sinangag, at Itlog - Sardines with garlic rice and egg',
                'prep_time' => 5,
                'cook_time' => 10,
                'servings' => 2,
                'difficulty' => 'Easy',
                'category' => 'Filipino',
                'calories_per_serving' => 480,
                'protein_per_serving' => 26,
                'carbs_per_serving' => 58,
                'fat_per_serving' => 16,
                'instructions' => 'Sauté sardines with onions, prepare garlic rice, fry egg',
                'is_filipino_dish' => true,
                'ingredients' => ['sardines in tomato sauce', 'garlic rice', 'egg', 'onion', 'garlic'],
            ],
            [
                'name' => 'Tunasilog',
                'description' => 'Tuna, Sinangag, at Itlog - Tuna flakes with garlic rice and egg',
                'prep_time' => 5,
                'cook_time' => 10,
                'servings' => 2,
                'difficulty' => 'Easy',
                'category' => 'Filipino',
                'calories_per_serving' => 460,
                'protein_per_serving' => 24,
                'carbs_per_serving' => 58,
                'fat_per_serving' => 14,
                'instructions' => 'Sauté tuna flakes with onions, prepare garlic rice, fry egg',
                'is_filipino_dish' => true,
                'ingredients' => ['tuna flakes', 'garlic rice', 'egg', 'onion', 'garlic'],
            ],

            // Filipino Bread Breakfasts
            [
                'name' => 'Pandesal with Butter and Cheese',
                'description' => 'Soft Filipino bread with butter and cheese',
                'prep_time' => 5,
                'cook_time' => 5,
                'servings' => 2,
                'difficulty' => 'Easy',
                'category' => 'Filipino',
                'calories_per_serving' => 320,
                'protein_per_serving' => 12,
                'carbs_per_serving' => 44,
                'fat_per_serving' => 8,
                'instructions' => 'Toast pandesal, spread butter, add cheese',
                'is_filipino_dish' => true,
                'ingredients' => ['pandesal', 'butter', 'cheddar cheese'],
            ],
            [
                'name' => 'Pandesal with Jam',
                'description' => 'Soft Filipino bread with fruit jam',
                'prep_time' => 5,
                'cook_time' => 5,
                'servings' => 2,
                'difficulty' => 'Easy',
                'category' => 'Filipino',
                'calories_per_serving' => 280,
                'protein_per_serving' => 8,
                'carbs_per_serving' => 52,
                'fat_per_serving' => 4,
                'instructions' => 'Toast pandesal, spread jam',
                'is_filipino_dish' => true,
                'ingredients' => ['pandesal', 'sugar', 'fruit'],
            ],
            [
                'name' => 'Pandesal with Peanut Butter',
                'description' => 'Soft Filipino bread with peanut butter',
                'prep_time' => 5,
                'cook_time' => 5,
                'servings' => 2,
                'difficulty' => 'Easy',
                'category' => 'Filipino',
                'calories_per_serving' => 340,
                'protein_per_serving' => 14,
                'carbs_per_serving' => 44,
                'fat_per_serving' => 12,
                'instructions' => 'Toast pandesal, spread peanut butter',
                'is_filipino_dish' => true,
                'ingredients' => ['pandesal', 'peanut butter'],
            ],
            [
                'name' => 'Ensaymada',
                'description' => 'Sweet bread with cheese and sugar',
                'prep_time' => 10,
                'cook_time' => 20,
                'servings' => 4,
                'difficulty' => 'Medium',
                'category' => 'Filipino',
                'calories_per_serving' => 380,
                'protein_per_serving' => 12,
                'carbs_per_serving' => 58,
                'fat_per_serving' => 14,
                'instructions' => 'Make sweet bread dough, add cheese, bake',
                'is_filipino_dish' => true,
                'ingredients' => ['flour', 'sugar', 'cheddar cheese', 'butter', 'egg'],
            ],
            [
                'name' => 'Pan de Sal with Scrambled Egg',
                'description' => 'Filipino bread with scrambled eggs',
                'prep_time' => 5,
                'cook_time' => 10,
                'servings' => 2,
                'difficulty' => 'Easy',
                'category' => 'Filipino',
                'calories_per_serving' => 360,
                'protein_per_serving' => 20,
                'carbs_per_serving' => 44,
                'fat_per_serving' => 14,
                'instructions' => 'Toast pan de sal, scramble eggs with milk',
                'is_filipino_dish' => true,
                'ingredients' => ['pan de sal', 'egg', 'milk', 'butter'],
            ],
            [
                'name' => 'Monay with Butter',
                'description' => 'Filipino bread roll with butter',
                'prep_time' => 5,
                'cook_time' => 5,
                'servings' => 2,
                'difficulty' => 'Easy',
                'category' => 'Filipino',
                'calories_per_serving' => 300,
                'protein_per_serving' => 10,
                'carbs_per_serving' => 44,
                'fat_per_serving' => 8,
                'instructions' => 'Warm monay, spread butter',
                'is_filipino_dish' => true,
                'ingredients' => ['monay', 'butter'],
            ],

            // Filipino Rice Cakes for Breakfast
            [
                'name' => 'Puto with Cheese',
                'description' => 'Steamed rice cake with cheese',
                'prep_time' => 15,
                'cook_time' => 20,
                'servings' => 6,
                'difficulty' => 'Easy',
                'category' => 'Filipino',
                'calories_per_serving' => 180,
                'protein_per_serving' => 6,
                'carbs_per_serving' => 32,
                'fat_per_serving' => 4,
                'instructions' => 'Make rice cake batter, steam, top with cheese',
                'is_filipino_dish' => true,
                'ingredients' => ['rice flour', 'sugar', 'cheddar cheese', 'coconut milk'],
            ],
            [
                'name' => 'Puto with Salted Egg',
                'description' => 'Steamed rice cake with salted egg',
                'prep_time' => 15,
                'cook_time' => 20,
                'servings' => 6,
                'difficulty' => 'Easy',
                'category' => 'Filipino',
                'calories_per_serving' => 200,
                'protein_per_serving' => 8,
                'carbs_per_serving' => 32,
                'fat_per_serving' => 6,
                'instructions' => 'Make rice cake batter, steam, top with salted egg',
                'is_filipino_dish' => true,
                'ingredients' => ['rice flour', 'sugar', 'salted egg', 'coconut milk'],
            ],
            [
                'name' => 'Kutsinta',
                'description' => 'Brown rice cake with coconut',
                'prep_time' => 20,
                'cook_time' => 25,
                'servings' => 8,
                'difficulty' => 'Easy',
                'category' => 'Filipino',
                'calories_per_serving' => 160,
                'protein_per_serving' => 4,
                'carbs_per_serving' => 35,
                'fat_per_serving' => 2,
                'instructions' => 'Make brown rice cake batter, steam, serve with coconut',
                'is_filipino_dish' => true,
                'ingredients' => ['brown sugar', 'rice flour', 'coconut', 'lye water'],
            ],
            [
                'name' => 'Pichi-Pichi',
                'description' => 'Cassava rice cake with coconut',
                'prep_time' => 20,
                'cook_time' => 25,
                'servings' => 8,
                'difficulty' => 'Easy',
                'category' => 'Filipino',
                'calories_per_serving' => 180,
                'protein_per_serving' => 4,
                'carbs_per_serving' => 38,
                'fat_per_serving' => 3,
                'instructions' => 'Make cassava batter, steam, serve with coconut',
                'is_filipino_dish' => true,
                'ingredients' => ['cassava', 'sugar', 'coconut', 'coconut milk'],
            ],
            [
                'name' => 'Sapin-Sapin',
                'description' => 'Layered rice cake',
                'prep_time' => 30,
                'cook_time' => 30,
                'servings' => 8,
                'difficulty' => 'Medium',
                'category' => 'Filipino',
                'calories_per_serving' => 220,
                'protein_per_serving' => 6,
                'carbs_per_serving' => 42,
                'fat_per_serving' => 4,
                'instructions' => 'Make layered rice cake with different colors, steam',
                'is_filipino_dish' => true,
                'ingredients' => ['glutinous rice', 'coconut milk', 'sugar', 'food coloring'],
            ],
            [
                'name' => 'Biko',
                'description' => 'Sweet sticky rice with coconut',
                'prep_time' => 20,
                'cook_time' => 30,
                'servings' => 6,
                'difficulty' => 'Easy',
                'category' => 'Filipino',
                'calories_per_serving' => 280,
                'protein_per_serving' => 6,
                'carbs_per_serving' => 58,
                'fat_per_serving' => 6,
                'instructions' => 'Cook sticky rice with coconut milk and sugar',
                'is_filipino_dish' => true,
                'ingredients' => ['glutinous rice', 'coconut milk', 'brown sugar', 'coconut'],
            ],
            [
                'name' => 'Suman with Mango',
                'description' => 'Wrapped sticky rice with mango',
                'prep_time' => 25,
                'cook_time' => 30,
                'servings' => 6,
                'difficulty' => 'Medium',
                'category' => 'Filipino',
                'calories_per_serving' => 240,
                'protein_per_serving' => 4,
                'carbs_per_serving' => 52,
                'fat_per_serving' => 4,
                'instructions' => 'Wrap sticky rice in banana leaves, steam, serve with mango',
                'is_filipino_dish' => true,
                'ingredients' => ['glutinous rice', 'coconut milk', 'sugar', 'banana leaves', 'mango'],
            ],

            // Filipino Porridge Breakfasts
            [
                'name' => 'Ginataang Mais',
                'description' => 'Sweet corn in coconut milk',
                'prep_time' => 10,
                'cook_time' => 20,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Filipino',
                'calories_per_serving' => 220,
                'protein_per_serving' => 6,
                'carbs_per_serving' => 38,
                'fat_per_serving' => 8,
                'instructions' => 'Cook corn in coconut milk with sugar',
                'is_filipino_dish' => true,
                'ingredients' => ['mais', 'coconut milk', 'sugar', 'salt'],
            ],
            [
                'name' => 'Ginataang Saba',
                'description' => 'Sweet banana in coconut milk',
                'prep_time' => 10,
                'cook_time' => 20,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Filipino',
                'calories_per_serving' => 200,
                'protein_per_serving' => 4,
                'carbs_per_serving' => 42,
                'fat_per_serving' => 6,
                'instructions' => 'Cook saba banana in coconut milk with sugar',
                'is_filipino_dish' => true,
                'ingredients' => ['saba banana', 'coconut milk', 'sugar', 'salt'],
            ],
            [
                'name' => 'Ginataang Kamote',
                'description' => 'Sweet potato in coconut milk',
                'prep_time' => 10,
                'cook_time' => 25,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Filipino',
                'calories_per_serving' => 240,
                'protein_per_serving' => 6,
                'carbs_per_serving' => 45,
                'fat_per_serving' => 8,
                'instructions' => 'Cook sweet potato in coconut milk with sugar',
                'is_filipino_dish' => true,
                'ingredients' => ['sweet potato', 'coconut milk', 'sugar', 'salt'],
            ],
            [
                'name' => 'Ginataang Bilo-Bilo',
                'description' => 'Sweet rice balls in coconut milk',
                'prep_time' => 20,
                'cook_time' => 25,
                'servings' => 6,
                'difficulty' => 'Medium',
                'category' => 'Filipino',
                'calories_per_serving' => 280,
                'protein_per_serving' => 6,
                'carbs_per_serving' => 52,
                'fat_per_serving' => 8,
                'instructions' => 'Make rice balls, cook in coconut milk with fruits',
                'is_filipino_dish' => true,
                'ingredients' => ['glutinous rice', 'coconut milk', 'sugar', 'saba banana', 'jackfruit'],
            ],
            [
                'name' => 'Ginataang Halo-Halo',
                'description' => 'Mixed fruits in coconut milk',
                'prep_time' => 15,
                'cook_time' => 20,
                'servings' => 6,
                'difficulty' => 'Easy',
                'category' => 'Filipino',
                'calories_per_serving' => 200,
                'protein_per_serving' => 4,
                'carbs_per_serving' => 38,
                'fat_per_serving' => 6,
                'instructions' => 'Cook mixed fruits in coconut milk with sugar',
                'is_filipino_dish' => true,
                'ingredients' => ['saba banana', 'jackfruit', 'sweet potato', 'coconut milk', 'sugar'],
            ],

            // Filipino Omelet Breakfasts
            [
                'name' => 'Tortang Talong',
                'description' => 'Eggplant omelet',
                'prep_time' => 15,
                'cook_time' => 15,
                'servings' => 3,
                'difficulty' => 'Easy',
                'category' => 'Filipino',
                'calories_per_serving' => 180,
                'protein_per_serving' => 12,
                'carbs_per_serving' => 15,
                'fat_per_serving' => 10,
                'instructions' => 'Grill eggplant, wrap in beaten egg, cook',
                'is_filipino_dish' => true,
                'ingredients' => ['eggplant', 'egg', 'onion', 'garlic', 'oil'],
            ],
            [
                'name' => 'Tortang Giniling',
                'description' => 'Ground meat omelet',
                'prep_time' => 15,
                'cook_time' => 20,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Filipino',
                'calories_per_serving' => 280,
                'protein_per_serving' => 20,
                'carbs_per_serving' => 8,
                'fat_per_serving' => 18,
                'instructions' => 'Sauté ground meat, mix with beaten egg, cook',
                'is_filipino_dish' => true,
                'ingredients' => ['ground pork', 'egg', 'onion', 'garlic', 'oil'],
            ],
            [
                'name' => 'Tortang Alimasag',
                'description' => 'Crab omelet',
                'prep_time' => 20,
                'cook_time' => 15,
                'servings' => 3,
                'difficulty' => 'Medium',
                'category' => 'Filipino',
                'calories_per_serving' => 220,
                'protein_per_serving' => 18,
                'carbs_per_serving' => 8,
                'fat_per_serving' => 12,
                'instructions' => 'Mix crab meat with beaten egg, cook',
                'is_filipino_dish' => true,
                'ingredients' => ['crab meat', 'egg', 'onion', 'garlic', 'oil'],
            ],
            [
                'name' => 'Tortang Hipon',
                'description' => 'Shrimp omelet',
                'prep_time' => 15,
                'cook_time' => 15,
                'servings' => 3,
                'difficulty' => 'Easy',
                'category' => 'Filipino',
                'calories_per_serving' => 200,
                'protein_per_serving' => 16,
                'carbs_per_serving' => 8,
                'fat_per_serving' => 10,
                'instructions' => 'Mix shrimp with beaten egg, cook',
                'is_filipino_dish' => true,
                'ingredients' => ['shrimp', 'egg', 'onion', 'garlic', 'oil'],
            ],
            [
                'name' => 'Tortang Isda',
                'description' => 'Fish omelet',
                'prep_time' => 15,
                'cook_time' => 15,
                'servings' => 3,
                'difficulty' => 'Easy',
                'category' => 'Filipino',
                'calories_per_serving' => 190,
                'protein_per_serving' => 18,
                'carbs_per_serving' => 8,
                'fat_per_serving' => 10,
                'instructions' => 'Mix fish with beaten egg, cook',
                'is_filipino_dish' => true,
                'ingredients' => ['fish', 'egg', 'onion', 'garlic', 'oil'],
            ],

            // Filipino Pancake Breakfasts
            [
                'name' => 'Pancake with Margarine',
                'description' => 'Filipino pancake with margarine',
                'prep_time' => 10,
                'cook_time' => 15,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Filipino',
                'calories_per_serving' => 220,
                'protein_per_serving' => 8,
                'carbs_per_serving' => 32,
                'fat_per_serving' => 8,
                'instructions' => 'Make pancake batter, cook, serve with margarine',
                'is_filipino_dish' => true,
                'ingredients' => ['flour', 'egg', 'milk', 'sugar', 'margarine'],
            ],
            [
                'name' => 'Pancake with Cheese',
                'description' => 'Filipino pancake with cheese',
                'prep_time' => 10,
                'cook_time' => 15,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Filipino',
                'calories_per_serving' => 240,
                'protein_per_serving' => 12,
                'carbs_per_serving' => 32,
                'fat_per_serving' => 10,
                'instructions' => 'Make pancake batter, cook, top with cheese',
                'is_filipino_dish' => true,
                'ingredients' => ['flour', 'egg', 'milk', 'sugar', 'cheddar cheese'],
            ],
            [
                'name' => 'Pancake with Jam',
                'description' => 'Filipino pancake with fruit jam',
                'prep_time' => 10,
                'cook_time' => 15,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Filipino',
                'calories_per_serving' => 200,
                'protein_per_serving' => 6,
                'carbs_per_serving' => 38,
                'fat_per_serving' => 6,
                'instructions' => 'Make pancake batter, cook, serve with jam',
                'is_filipino_dish' => true,
                'ingredients' => ['flour', 'egg', 'milk', 'sugar', 'jam'],
            ],
            [
                'name' => 'Pancake with Condensed Milk',
                'description' => 'Filipino pancake with condensed milk',
                'prep_time' => 10,
                'cook_time' => 15,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Filipino',
                'calories_per_serving' => 260,
                'protein_per_serving' => 8,
                'carbs_per_serving' => 42,
                'fat_per_serving' => 8,
                'instructions' => 'Make pancake batter, cook, drizzle with condensed milk',
                'is_filipino_dish' => true,
                'ingredients' => ['flour', 'egg', 'milk', 'sugar', 'condensed milk'],
            ],

            // Filipino Fruit Breakfasts
            [
                'name' => 'Fresh Fruit Salad',
                'description' => 'Mixed Filipino fruits',
                'prep_time' => 15,
                'cook_time' => 0,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Filipino',
                'calories_per_serving' => 120,
                'protein_per_serving' => 2,
                'carbs_per_serving' => 28,
                'fat_per_serving' => 1,
                'instructions' => 'Mix fresh fruits together',
                'is_filipino_dish' => true,
                'ingredients' => ['mango', 'papaya', 'pineapple', 'banana', 'watermelon'],
            ],
            [
                'name' => 'Mango with Rice',
                'description' => 'Sweet mango with rice',
                'prep_time' => 10,
                'cook_time' => 15,
                'servings' => 2,
                'difficulty' => 'Easy',
                'category' => 'Filipino',
                'calories_per_serving' => 320,
                'protein_per_serving' => 6,
                'carbs_per_serving' => 68,
                'fat_per_serving' => 2,
                'instructions' => 'Cook rice, serve with sliced mango',
                'is_filipino_dish' => true,
                'ingredients' => ['rice', 'ripe mango', 'sugar'],
            ],
            [
                'name' => 'Banana with Rice',
                'description' => 'Sweet banana with rice',
                'prep_time' => 10,
                'cook_time' => 15,
                'servings' => 2,
                'difficulty' => 'Easy',
                'category' => 'Filipino',
                'calories_per_serving' => 300,
                'protein_per_serving' => 6,
                'carbs_per_serving' => 65,
                'fat_per_serving' => 2,
                'instructions' => 'Cook rice, serve with sliced banana',
                'is_filipino_dish' => true,
                'ingredients' => ['rice', 'banana', 'sugar'],
            ],
            [
                'name' => 'Avocado with Condensed Milk',
                'description' => 'Avocado with sweetened condensed milk',
                'prep_time' => 10,
                'cook_time' => 0,
                'servings' => 2,
                'difficulty' => 'Easy',
                'category' => 'Filipino',
                'calories_per_serving' => 280,
                'protein_per_serving' => 6,
                'carbs_per_serving' => 42,
                'fat_per_serving' => 12,
                'instructions' => 'Slice avocado, drizzle with condensed milk',
                'is_filipino_dish' => true,
                'ingredients' => ['avocado', 'condensed milk'],
            ],
            [
                'name' => 'Guyabano Smoothie',
                'description' => 'Soursop smoothie',
                'prep_time' => 10,
                'cook_time' => 0,
                'servings' => 2,
                'difficulty' => 'Easy',
                'category' => 'Filipino',
                'calories_per_serving' => 180,
                'protein_per_serving' => 4,
                'carbs_per_serving' => 38,
                'fat_per_serving' => 2,
                'instructions' => 'Blend guyabano with milk and sugar',
                'is_filipino_dish' => true,
                'ingredients' => ['guyabano', 'milk', 'sugar', 'ice'],
            ],

            // Filipino Healthy Breakfast Options
            [
                'name' => 'Malunggay Omelet',
                'description' => 'Moringa leaves omelet',
                'prep_time' => 10,
                'cook_time' => 15,
                'servings' => 3,
                'difficulty' => 'Easy',
                'category' => 'Healthy',
                'calories_per_serving' => 160,
                'protein_per_serving' => 12,
                'carbs_per_serving' => 8,
                'fat_per_serving' => 10,
                'instructions' => 'Mix moringa leaves with beaten egg, cook',
                'is_filipino_dish' => true,
                'ingredients' => ['malunggay', 'egg', 'onion', 'garlic', 'oil'],
            ],
            [
                'name' => 'Kangkong Omelet',
                'description' => 'Water spinach omelet',
                'prep_time' => 10,
                'cook_time' => 15,
                'servings' => 3,
                'difficulty' => 'Easy',
                'category' => 'Healthy',
                'calories_per_serving' => 140,
                'protein_per_serving' => 10,
                'carbs_per_serving' => 8,
                'fat_per_serving' => 8,
                'instructions' => 'Mix water spinach with beaten egg, cook',
                'is_filipino_dish' => true,
                'ingredients' => ['kangkong', 'egg', 'onion', 'garlic', 'oil'],
            ],
            [
                'name' => 'Ampalaya Omelet',
                'description' => 'Bitter gourd omelet',
                'prep_time' => 15,
                'cook_time' => 15,
                'servings' => 3,
                'difficulty' => 'Easy',
                'category' => 'Healthy',
                'calories_per_serving' => 120,
                'protein_per_serving' => 8,
                'carbs_per_serving' => 8,
                'fat_per_serving' => 6,
                'instructions' => 'Mix bitter gourd with beaten egg, cook',
                'is_filipino_dish' => true,
                'ingredients' => ['ampalaya', 'egg', 'onion', 'garlic', 'oil'],
            ],
            [
                'name' => 'Ginataang Malunggay',
                'description' => 'Moringa leaves in coconut milk',
                'prep_time' => 5,
                'cook_time' => 15,
                'servings' => 3,
                'difficulty' => 'Easy',
                'category' => 'Healthy',
                'calories_per_serving' => 100,
                'protein_per_serving' => 6,
                'carbs_per_serving' => 8,
                'fat_per_serving' => 6,
                'instructions' => 'Cook moringa leaves in coconut milk',
                'is_filipino_dish' => true,
                'ingredients' => ['malunggay', 'coconut milk', 'garlic', 'onion'],
            ],
            [
                'name' => 'Ginataang Kangkong',
                'description' => 'Water spinach in coconut milk',
                'prep_time' => 5,
                'cook_time' => 15,
                'servings' => 3,
                'difficulty' => 'Easy',
                'category' => 'Healthy',
                'calories_per_serving' => 80,
                'protein_per_serving' => 4,
                'carbs_per_serving' => 8,
                'fat_per_serving' => 4,
                'instructions' => 'Cook water spinach in coconut milk',
                'is_filipino_dish' => true,
                'ingredients' => ['kangkong', 'coconut milk', 'garlic', 'onion'],
            ],

            // Filipino Modern Breakfast Options
            [
                'name' => 'Filipino Breakfast Burrito',
                'description' => 'Tortilla with Filipino fillings',
                'prep_time' => 15,
                'cook_time' => 10,
                'servings' => 2,
                'difficulty' => 'Easy',
                'category' => 'Filipino',
                'calories_per_serving' => 420,
                'protein_per_serving' => 20,
                'carbs_per_serving' => 45,
                'fat_per_serving' => 18,
                'instructions' => 'Wrap Filipino ingredients in tortilla',
                'is_filipino_dish' => true,
                'ingredients' => ['tortilla', 'longganisa', 'egg', 'garlic rice', 'onion'],
            ],
            [
                'name' => 'Filipino Breakfast Bowl',
                'description' => 'Rice bowl with Filipino toppings',
                'prep_time' => 10,
                'cook_time' => 15,
                'servings' => 2,
                'difficulty' => 'Easy',
                'category' => 'Filipino',
                'calories_per_serving' => 380,
                'protein_per_serving' => 18,
                'carbs_per_serving' => 52,
                'fat_per_serving' => 12,
                'instructions' => 'Top rice with Filipino breakfast ingredients',
                'is_filipino_dish' => true,
                'ingredients' => ['rice', 'tocino', 'egg', 'onion', 'garlic'],
            ],
            [
                'name' => 'Filipino Breakfast Sandwich',
                'description' => 'Sandwich with Filipino fillings',
                'prep_time' => 10,
                'cook_time' => 10,
                'servings' => 2,
                'difficulty' => 'Easy',
                'category' => 'Filipino',
                'calories_per_serving' => 360,
                'protein_per_serving' => 16,
                'carbs_per_serving' => 38,
                'fat_per_serving' => 14,
                'instructions' => 'Make sandwich with Filipino breakfast ingredients',
                'is_filipino_dish' => true,
                'ingredients' => ['bread', 'longganisa', 'egg', 'onion', 'mayonnaise'],
            ],
            [
                'name' => 'Filipino Breakfast Wrap',
                'description' => 'Wrap with Filipino fillings',
                'prep_time' => 10,
                'cook_time' => 10,
                'servings' => 2,
                'difficulty' => 'Easy',
                'category' => 'Filipino',
                'calories_per_serving' => 340,
                'protein_per_serving' => 14,
                'carbs_per_serving' => 42,
                'fat_per_serving' => 12,
                'instructions' => 'Wrap Filipino ingredients in flatbread',
                'is_filipino_dish' => true,
                'ingredients' => ['flatbread', 'corned beef', 'egg', 'onion', 'garlic'],
            ],
        ];

        foreach ($recipes as $recipeData) {
            $ingredients = $recipeData['ingredients'];
            unset($recipeData['ingredients']);
            
            $recipe = Recipe::firstOrCreate(
                ['name' => $recipeData['name']],
                $recipeData
            );

            // Attach ingredients to recipe
            foreach ($ingredients as $ingredientName) {
                $ingredient = Ingredient::where('name', $ingredientName)->first();
                if ($ingredient && !$recipe->ingredients()->where('ingredient_id', $ingredient->id)->exists()) {
                    $recipe->ingredients()->attach($ingredient->id, [
                        'quantity' => '1',
                        'unit' => 'piece'
                    ]);
                }
            }
        }
    }
}
