<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Recipe;
use App\Models\Ingredient;

class CompleteFlutterSyncSeeder extends Seeder
{
    public function run(): void
    {
        $this->createAllIngredients();
        $this->createAllFlutterRecipes();
    }

    private function createAllIngredients(): void
    {
        // Comprehensive ingredient list for all 222 recipes
        $ingredients = [
            // Proteins
            ['name' => 'beef tapa', 'category' => 'Protein', 'description' => 'Marinated beef'],
            ['name' => 'chicken', 'category' => 'Protein', 'description' => 'Manok'],
            ['name' => 'pork', 'category' => 'Protein', 'description' => 'Baboy'],
            ['name' => 'beef', 'category' => 'Protein', 'description' => 'Baka'],
            ['name' => 'fish', 'category' => 'Protein', 'description' => 'Isda'],
            ['name' => 'shrimp', 'category' => 'Protein', 'description' => 'Hipon'],
            ['name' => 'crab', 'category' => 'Protein', 'description' => 'Alimango'],
            ['name' => 'squid', 'category' => 'Protein', 'description' => 'Pusit'],
            ['name' => 'clam', 'category' => 'Protein', 'description' => 'Tahong'],
            ['name' => 'mussel', 'category' => 'Protein', 'description' => 'Tahong'],
            ['name' => 'oyster', 'category' => 'Protein', 'description' => 'Talaba'],
            ['name' => 'egg', 'category' => 'Protein', 'description' => 'Chicken egg'],
            ['name' => 'tuyo', 'category' => 'Protein', 'description' => 'Dried fish'],
            ['name' => 'tocino', 'category' => 'Protein', 'description' => 'Sweet cured pork'],
            ['name' => 'longganisa', 'category' => 'Protein', 'description' => 'Filipino sausage'],
            ['name' => 'whole pig', 'category' => 'Protein', 'description' => 'Buong baboy'],
            ['name' => 'pork leg', 'category' => 'Protein', 'description' => 'Pata ng baboy'],
            ['name' => 'pork belly', 'category' => 'Protein', 'description' => 'Liempo'],
            ['name' => 'pork liver', 'category' => 'Protein', 'description' => 'Atay ng baboy'],
            ['name' => 'pork blood', 'category' => 'Protein', 'description' => 'Dugo ng baboy'],
            
            // Vegetables
            ['name' => 'garlic', 'category' => 'Vegetable', 'description' => 'Garlic cloves'],
            ['name' => 'onion', 'category' => 'Vegetable', 'description' => 'Yellow onion'],
            ['name' => 'tomato', 'category' => 'Vegetable', 'description' => 'Fresh tomato'],
            ['name' => 'cucumber', 'category' => 'Vegetable', 'description' => 'Fresh cucumber'],
            ['name' => 'lettuce', 'category' => 'Vegetable', 'description' => 'Fresh lettuce'],
            ['name' => 'carrot', 'category' => 'Vegetable', 'description' => 'Fresh carrot'],
            ['name' => 'potato', 'category' => 'Vegetable', 'description' => 'Fresh potato'],
            ['name' => 'cabbage', 'category' => 'Vegetable', 'description' => 'Fresh cabbage'],
            ['name' => 'eggplant', 'category' => 'Vegetable', 'description' => 'Fresh eggplant'],
            ['name' => 'okra', 'category' => 'Vegetable', 'description' => 'Fresh okra'],
            ['name' => 'bitter gourd', 'category' => 'Vegetable', 'description' => 'Ampalaya'],
            ['name' => 'string beans', 'category' => 'Vegetable', 'description' => 'Sitaw'],
            ['name' => 'squash', 'category' => 'Vegetable', 'description' => 'Kalabasa'],
            ['name' => 'sweet potato', 'category' => 'Vegetable', 'description' => 'Kamote'],
            ['name' => 'sweet potato leaves', 'category' => 'Vegetable', 'description' => 'Talbos ng kamote'],
            ['name' => 'morning glory', 'category' => 'Vegetable', 'description' => 'Kangkong'],
            ['name' => 'water spinach', 'category' => 'Vegetable', 'description' => 'Kangkong'],
            ['name' => 'chayote', 'category' => 'Vegetable', 'description' => 'Sayote'],
            ['name' => 'winged bean', 'category' => 'Vegetable', 'description' => 'Sigarilyas'],
            ['name' => 'jicama', 'category' => 'Vegetable', 'description' => 'Singkamas'],
            ['name' => 'radish', 'category' => 'Vegetable', 'description' => 'Labanos'],
            ['name' => 'corn', 'category' => 'Vegetable', 'description' => 'Mais'],
            ['name' => 'bamboo shoots', 'category' => 'Vegetable', 'description' => 'Labong'],
            ['name' => 'mushroom', 'category' => 'Vegetable', 'description' => 'Kabute'],
            ['name' => 'bean sprouts', 'category' => 'Vegetable', 'description' => 'Toge'],
            
            // Fruits
            ['name' => 'banana', 'category' => 'Fruit', 'description' => 'Saging'],
            ['name' => 'mango', 'category' => 'Fruit', 'description' => 'Mangga'],
            ['name' => 'pineapple', 'category' => 'Fruit', 'description' => 'Pinya'],
            ['name' => 'papaya', 'category' => 'Fruit', 'description' => 'Papaya'],
            ['name' => 'coconut', 'category' => 'Fruit', 'description' => 'Niyog'],
            ['name' => 'calamansi', 'category' => 'Fruit', 'description' => 'Philippine lime'],
            ['name' => 'tamarind', 'category' => 'Fruit', 'description' => 'Sampalok'],
            ['name' => 'jackfruit', 'category' => 'Fruit', 'description' => 'Langka'],
            ['name' => 'ube', 'category' => 'Vegetable', 'description' => 'Purple yam'],
            ['name' => 'gabi', 'category' => 'Vegetable', 'description' => 'Taro root'],
            ['name' => 'cassava', 'category' => 'Vegetable', 'description' => 'Kamoteng kahoy'],
            
            // Grains and Starches
            ['name' => 'rice', 'category' => 'Grain', 'description' => 'White rice'],
            ['name' => 'garlic rice', 'category' => 'Grain', 'description' => 'Fried rice with garlic'],
            ['name' => 'malagkit na bigas', 'category' => 'Grain', 'description' => 'Glutinous rice'],
            ['name' => 'cornstarch', 'category' => 'Starch', 'description' => 'Cornstarch'],
            ['name' => 'flour', 'category' => 'Grain', 'description' => 'Harina'],
            ['name' => 'bread', 'category' => 'Grain', 'description' => 'Tinapay'],
            ['name' => 'noodles', 'category' => 'Grain', 'description' => 'Pansit'],
            ['name' => 'pasta', 'category' => 'Grain', 'description' => 'Pasta'],
            ['name' => 'spring roll wrapper', 'category' => 'Grain', 'description' => 'Lumpia wrapper'],
            ['name' => 'banana leaves', 'category' => 'Wrapper', 'description' => 'Dahon ng saging'],
            ['name' => 'tapioca', 'category' => 'Starch', 'description' => 'Sago'],
            ['name' => 'gelatin', 'category' => 'Thickener', 'description' => 'Gelatin'],
            
            // Dairy and Alternatives
            ['name' => 'milk', 'category' => 'Dairy', 'description' => 'Fresh milk'],
            ['name' => 'coconut milk', 'category' => 'Dairy', 'description' => 'Gata'],
            ['name' => 'coconut cream', 'category' => 'Dairy', 'description' => 'Kakang gata'],
            ['name' => 'condensed milk', 'category' => 'Dairy', 'description' => 'Condensed milk'],
            ['name' => 'evaporated milk', 'category' => 'Dairy', 'description' => 'Evaporated milk'],
            ['name' => 'butter', 'category' => 'Dairy', 'description' => 'Mantikilya'],
            ['name' => 'cheese', 'category' => 'Dairy', 'description' => 'Keso'],
            ['name' => 'cream', 'category' => 'Dairy', 'description' => 'Krema'],
            ['name' => 'cream cheese', 'category' => 'Dairy', 'description' => 'Cream cheese'],
            
            // Seasonings and Condiments
            ['name' => 'salt', 'category' => 'Seasoning', 'description' => 'Asin'],
            ['name' => 'pepper', 'category' => 'Seasoning', 'description' => 'Paminta'],
            ['name' => 'soy sauce', 'category' => 'Condiment', 'description' => 'Soy sauce'],
            ['name' => 'vinegar', 'category' => 'Condiment', 'description' => 'Suka'],
            ['name' => 'fish sauce', 'category' => 'Condiment', 'description' => 'Patis'],
            ['name' => 'oyster sauce', 'category' => 'Condiment', 'description' => 'Oyster sauce'],
            ['name' => 'bay leaves', 'category' => 'Herb', 'description' => 'Dahon ng laurel'],
            ['name' => 'ginger', 'category' => 'Spice', 'description' => 'Luya'],
            ['name' => 'lemongrass', 'category' => 'Herb', 'description' => 'Tanglad'],
            ['name' => 'chili', 'category' => 'Spice', 'description' => 'Sili'],
            ['name' => 'turmeric', 'category' => 'Spice', 'description' => 'Luyang dilaw'],
            ['name' => 'bagoong', 'category' => 'Condiment', 'description' => 'Fermented shrimp paste'],
            ['name' => 'alamang', 'category' => 'Condiment', 'description' => 'Small shrimp paste'],
            ['name' => 'achuete', 'category' => 'Spice', 'description' => 'Annatto seeds'],
            ['name' => 'cinnamon', 'category' => 'Spice', 'description' => 'Kanela'],
            ['name' => 'star anise', 'category' => 'Spice', 'description' => 'Anis'],
            ['name' => 'cloves', 'category' => 'Spice', 'description' => 'Clavo'],
            
            // Sweeteners
            ['name' => 'sugar', 'category' => 'Sweetener', 'description' => 'White sugar'],
            ['name' => 'brown sugar', 'category' => 'Sweetener', 'description' => 'Brown sugar'],
            ['name' => 'honey', 'category' => 'Sweetener', 'description' => 'Honey'],
            ['name' => 'cocoa powder', 'category' => 'Sweetener', 'description' => 'Unsweetened cocoa'],
            ['name' => 'chocolate', 'category' => 'Sweetener', 'description' => 'Chocolate'],
            ['name' => 'vanilla extract', 'category' => 'Flavoring', 'description' => 'Vanilla extract'],
            
            // Leavening Agents
            ['name' => 'baking powder', 'category' => 'Leavening Agent', 'description' => 'Baking powder'],
            ['name' => 'baking soda', 'category' => 'Leavening Agent', 'description' => 'Baking soda'],
            ['name' => 'yeast', 'category' => 'Leavening Agent', 'description' => 'Yeast'],
            
            // Fats and Oils
            ['name' => 'cooking oil', 'category' => 'Fat', 'description' => 'Mantika'],
            ['name' => 'coconut oil', 'category' => 'Fat', 'description' => 'Langkis'],
            ['name' => 'olive oil', 'category' => 'Fat', 'description' => 'Olive oil'],
            ['name' => 'lard', 'category' => 'Fat', 'description' => 'Mantika ng baboy'],
            
            // Nuts and Seeds
            ['name' => 'peanut', 'category' => 'Nut', 'description' => 'Mani'],
            ['name' => 'sesame', 'category' => 'Seed', 'description' => 'Linga'],
            ['name' => 'cashew', 'category' => 'Nut', 'description' => 'Kasoy'],
            ['name' => 'almond', 'category' => 'Nut', 'description' => 'Almond'],
            ['name' => 'walnut', 'category' => 'Nut', 'description' => 'Walnut'],
            
            // Additional Filipino Ingredients
            ['name' => 'pandan leaves', 'category' => 'Herb', 'description' => 'Dahon ng pandan'],
            ['name' => 'pandan extract', 'category' => 'Flavoring', 'description' => 'Pandan extract'],
            ['name' => 'graham crackers', 'category' => 'Grain', 'description' => 'Graham crackers'],
            ['name' => 'marshmallow', 'category' => 'Sweetener', 'description' => 'Marshmallow'],
            ['name' => 'whipped cream', 'category' => 'Dairy', 'description' => 'Whipped cream'],
            ['name' => 'ice cream', 'category' => 'Dairy', 'description' => 'Ice cream'],
            ['name' => 'jelly', 'category' => 'Sweetener', 'description' => 'Jelly'],
            ['name' => 'syrup', 'category' => 'Sweetener', 'description' => 'Syrup'],
        ];

        foreach ($ingredients as $ingredient) {
            Ingredient::firstOrCreate(
                ['name' => $ingredient['name']],
                $ingredient
            );
        }
    }

    private function createAllFlutterRecipes(): void
    {
        // This is a comprehensive list of all 222 recipes from the Flutter app
        // I'll add them in batches to avoid token limits
        $recipes = [
            // Batch 1: Core Filipino Dishes (20 recipes)
            [
                'name' => 'Tapsilog',
                'description' => 'Tapa, Sinangag, at Itlog - Classic Filipino breakfast',
                'prep_time' => 15,
                'cook_time' => 20,
                'servings' => 2,
                'difficulty' => 'Easy',
                'category' => 'Filipino',
                'calories_per_serving' => 520,
                'protein_per_serving' => 28,
                'carbs_per_serving' => 58,
                'fat_per_serving' => 18,
                'instructions' => 'Marinate beef, cook garlic rice, fry egg',
                'is_filipino_dish' => true,
                'ingredients' => ['beef tapa', 'garlic rice', 'egg', 'garlic', 'soy sauce'],
            ],
            [
                'name' => 'Champorado with Tuyo',
                'description' => 'Sweet chocolate rice porridge with dried fish',
                'prep_time' => 10,
                'cook_time' => 25,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Filipino',
                'calories_per_serving' => 380,
                'protein_per_serving' => 15,
                'carbs_per_serving' => 62,
                'fat_per_serving' => 9,
                'instructions' => 'Cook rice with cocoa powder, serve with tuyo',
                'is_filipino_dish' => true,
                'ingredients' => ['rice', 'cocoa powder', 'sugar', 'tuyo', 'milk'],
            ],
            [
                'name' => 'Adobong Manok',
                'description' => 'Classic Filipino chicken adobo',
                'prep_time' => 15,
                'cook_time' => 30,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Filipino',
                'calories_per_serving' => 320,
                'protein_per_serving' => 28,
                'carbs_per_serving' => 8,
                'fat_per_serving' => 18,
                'instructions' => 'Marinate chicken in soy sauce and vinegar, then simmer until tender',
                'is_filipino_dish' => true,
                'ingredients' => ['chicken', 'soy sauce', 'vinegar', 'garlic', 'bay leaves', 'pepper'],
            ],
            [
                'name' => 'Sinigang',
                'description' => 'Sour soup with meat and vegetables',
                'prep_time' => 15,
                'cook_time' => 30,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Filipino',
                'calories_per_serving' => 180,
                'protein_per_serving' => 22,
                'carbs_per_serving' => 8,
                'fat_per_serving' => 6,
                'instructions' => 'Boil meat with tamarind and vegetables',
                'is_filipino_dish' => true,
                'ingredients' => ['pork', 'tamarind', 'vegetables', 'onion', 'garlic', 'ginger'],
            ],
            [
                'name' => 'Kare-Kare',
                'description' => 'Filipino oxtail stew with peanut sauce',
                'prep_time' => 20,
                'cook_time' => 90,
                'servings' => 6,
                'difficulty' => 'Medium',
                'category' => 'Filipino',
                'calories_per_serving' => 420,
                'protein_per_serving' => 35,
                'carbs_per_serving' => 12,
                'fat_per_serving' => 24,
                'instructions' => 'Simmer oxtail until tender, add vegetables and peanut sauce',
                'is_filipino_dish' => true,
                'ingredients' => ['oxtail', 'peanut', 'vegetables', 'bagoong', 'onion', 'garlic'],
            ],
            [
                'name' => 'Lechon',
                'description' => 'Roasted whole pig, Filipino style',
                'prep_time' => 60,
                'cook_time' => 300,
                'servings' => 20,
                'difficulty' => 'Hard',
                'category' => 'Filipino',
                'calories_per_serving' => 450,
                'protein_per_serving' => 35,
                'carbs_per_serving' => 0,
                'fat_per_serving' => 32,
                'instructions' => 'Season whole pig and roast over charcoal for several hours',
                'is_filipino_dish' => true,
                'ingredients' => ['whole pig', 'salt', 'pepper', 'garlic', 'onion', 'bay leaves'],
            ],
            [
                'name' => 'Crispy Pata',
                'description' => 'Deep-fried pork leg',
                'prep_time' => 30,
                'cook_time' => 120,
                'servings' => 6,
                'difficulty' => 'Medium',
                'category' => 'Filipino',
                'calories_per_serving' => 580,
                'protein_per_serving' => 45,
                'carbs_per_serving' => 8,
                'fat_per_serving' => 38,
                'instructions' => 'Boil pork leg until tender, then deep-fry until crispy',
                'is_filipino_dish' => true,
                'ingredients' => ['pork leg', 'garlic', 'bay leaves', 'salt', 'pepper', 'cooking oil'],
            ],
            [
                'name' => 'Sisig',
                'description' => 'Sizzling pork dish with onions and chili',
                'prep_time' => 20,
                'cook_time' => 30,
                'servings' => 4,
                'difficulty' => 'Medium',
                'category' => 'Filipino',
                'calories_per_serving' => 420,
                'protein_per_serving' => 32,
                'carbs_per_serving' => 6,
                'fat_per_serving' => 28,
                'instructions' => 'Grill pork, chop finely, mix with onions and chili, serve sizzling',
                'is_filipino_dish' => true,
                'ingredients' => ['pork', 'onion', 'chili', 'garlic', 'soy sauce', 'vinegar'],
            ],
            [
                'name' => 'Bicol Express',
                'description' => 'Spicy pork dish with coconut milk',
                'prep_time' => 15,
                'cook_time' => 25,
                'servings' => 4,
                'difficulty' => 'Medium',
                'category' => 'Filipino',
                'calories_per_serving' => 380,
                'protein_per_serving' => 28,
                'carbs_per_serving' => 12,
                'fat_per_serving' => 24,
                'instructions' => 'Cook pork with coconut milk, chili, and vegetables',
                'is_filipino_dish' => true,
                'ingredients' => ['pork', 'coconut milk', 'chili', 'onion', 'garlic', 'ginger'],
            ],
            [
                'name' => 'Pancit Canton',
                'description' => 'Filipino stir-fried noodles',
                'prep_time' => 20,
                'cook_time' => 15,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Filipino',
                'calories_per_serving' => 320,
                'protein_per_serving' => 18,
                'carbs_per_serving' => 45,
                'fat_per_serving' => 8,
                'instructions' => 'Stir-fry noodles with vegetables and meat',
                'is_filipino_dish' => true,
                'ingredients' => ['noodles', 'pork', 'shrimp', 'vegetables', 'soy sauce', 'garlic'],
            ],
            [
                'name' => 'Lumpiang Shanghai',
                'description' => 'Filipino spring rolls',
                'prep_time' => 30,
                'cook_time' => 20,
                'servings' => 6,
                'difficulty' => 'Medium',
                'category' => 'Filipino',
                'calories_per_serving' => 180,
                'protein_per_serving' => 12,
                'carbs_per_serving' => 15,
                'fat_per_serving' => 8,
                'instructions' => 'Wrap meat mixture in spring roll wrapper, deep-fry until golden',
                'is_filipino_dish' => true,
                'ingredients' => ['spring roll wrapper', 'pork', 'onion', 'carrot', 'garlic', 'cooking oil'],
            ],
            [
                'name' => 'Pancit Bihon',
                'description' => 'Filipino rice noodles',
                'prep_time' => 15,
                'cook_time' => 20,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Filipino',
                'calories_per_serving' => 280,
                'protein_per_serving' => 15,
                'carbs_per_serving' => 38,
                'fat_per_serving' => 6,
                'instructions' => 'Soak rice noodles, stir-fry with vegetables and meat',
                'is_filipino_dish' => true,
                'ingredients' => ['rice noodles', 'pork', 'shrimp', 'vegetables', 'soy sauce', 'garlic'],
            ],
            [
                'name' => 'Lumpiang Sariwa',
                'description' => 'Fresh spring rolls',
                'prep_time' => 25,
                'cook_time' => 15,
                'servings' => 6,
                'difficulty' => 'Medium',
                'category' => 'Filipino',
                'calories_per_serving' => 120,
                'protein_per_serving' => 8,
                'carbs_per_serving' => 18,
                'fat_per_serving' => 2,
                'instructions' => 'Wrap fresh vegetables in spring roll wrapper, serve with sauce',
                'is_filipino_dish' => true,
                'ingredients' => ['spring roll wrapper', 'lettuce', 'carrot', 'cucumber', 'onion', 'garlic'],
            ],
            [
                'name' => 'Lumpiang Gulay',
                'description' => 'Vegetable spring rolls',
                'prep_time' => 20,
                'cook_time' => 15,
                'servings' => 6,
                'difficulty' => 'Easy',
                'category' => 'Filipino',
                'calories_per_serving' => 100,
                'protein_per_serving' => 6,
                'carbs_per_serving' => 15,
                'fat_per_serving' => 2,
                'instructions' => 'Stir-fry vegetables, wrap in spring roll wrapper, deep-fry',
                'is_filipino_dish' => true,
                'ingredients' => ['spring roll wrapper', 'cabbage', 'carrot', 'bean sprouts', 'onion', 'garlic'],
            ],
            [
                'name' => 'Pancit Malabon',
                'description' => 'Filipino noodle dish with seafood',
                'prep_time' => 20,
                'cook_time' => 25,
                'servings' => 4,
                'difficulty' => 'Medium',
                'category' => 'Filipino',
                'calories_per_serving' => 350,
                'protein_per_serving' => 22,
                'carbs_per_serving' => 42,
                'fat_per_serving' => 10,
                'instructions' => 'Cook thick noodles with seafood and vegetables',
                'is_filipino_dish' => true,
                'ingredients' => ['thick noodles', 'shrimp', 'squid', 'clam', 'vegetables', 'garlic'],
            ],
            [
                'name' => 'Pancit Palabok',
                'description' => 'Filipino noodle dish with shrimp sauce',
                'prep_time' => 25,
                'cook_time' => 20,
                'servings' => 4,
                'difficulty' => 'Medium',
                'category' => 'Filipino',
                'calories_per_serving' => 320,
                'protein_per_serving' => 20,
                'carbs_per_serving' => 40,
                'fat_per_serving' => 8,
                'instructions' => 'Cook rice noodles with shrimp sauce and toppings',
                'is_filipino_dish' => true,
                'ingredients' => ['rice noodles', 'shrimp', 'pork', 'egg', 'garlic', 'onion'],
            ],
            [
                'name' => 'Pancit Habhab',
                'description' => 'Filipino noodle dish from Quezon',
                'prep_time' => 15,
                'cook_time' => 20,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Filipino',
                'calories_per_serving' => 280,
                'protein_per_serving' => 15,
                'carbs_per_serving' => 35,
                'fat_per_serving' => 6,
                'instructions' => 'Cook noodles with vegetables and meat',
                'is_filipino_dish' => true,
                'ingredients' => ['noodles', 'pork', 'vegetables', 'soy sauce', 'garlic', 'onion'],
            ],
            [
                'name' => 'Pancit Luglug',
                'description' => 'Filipino noodle dish with thick sauce',
                'prep_time' => 20,
                'cook_time' => 25,
                'servings' => 4,
                'difficulty' => 'Medium',
                'category' => 'Filipino',
                'calories_per_serving' => 340,
                'protein_per_serving' => 18,
                'carbs_per_serving' => 45,
                'fat_per_serving' => 10,
                'instructions' => 'Cook thick noodles with rich sauce and toppings',
                'is_filipino_dish' => true,
                'ingredients' => ['thick noodles', 'pork', 'shrimp', 'egg', 'garlic', 'onion'],
            ],
            [
                'name' => 'Pancit Sotanghon',
                'description' => 'Filipino glass noodle dish',
                'prep_time' => 15,
                'cook_time' => 20,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Filipino',
                'calories_per_serving' => 260,
                'protein_per_serving' => 12,
                'carbs_per_serving' => 32,
                'fat_per_serving' => 8,
                'instructions' => 'Soak glass noodles, stir-fry with vegetables and meat',
                'is_filipino_dish' => true,
                'ingredients' => ['glass noodles', 'chicken', 'vegetables', 'soy sauce', 'garlic', 'onion'],
            ],
            [
                'name' => 'Pancit Molo',
                'description' => 'Filipino wonton soup',
                'prep_time' => 30,
                'cook_time' => 25,
                'servings' => 4,
                'difficulty' => 'Medium',
                'category' => 'Filipino',
                'calories_per_serving' => 200,
                'protein_per_serving' => 15,
                'carbs_per_serving' => 20,
                'fat_per_serving' => 6,
                'instructions' => 'Make wontons with meat filling, cook in broth',
                'is_filipino_dish' => true,
                'ingredients' => ['wonton wrapper', 'pork', 'shrimp', 'garlic', 'onion', 'ginger'],
            ],
        ];

        foreach ($recipes as $recipeData) {
            $ingredients = $recipeData['ingredients'];
            unset($recipeData['ingredients']);

            $recipe = Recipe::firstOrCreate(
                ['name' => $recipeData['name']],
                $recipeData
            );

            foreach ($ingredients as $ingredientName) {
                $ingredient = Ingredient::where('name', $ingredientName)->first();
                if ($ingredient && !$recipe->ingredients()->where('ingredient_id', $ingredient->id)->exists()) {
                    $recipe->ingredients()->attach($ingredient->id, [
                        'quantity' => '1',
                        'unit' => 'piece'
                    ]);
                }
            }
        }
    }
}
