<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Recipe;
use App\Models\Ingredient;

class FilipinoDessertRecipesSeeder extends Seeder
{
    public function run(): void
    {
        // Create additional ingredients for desserts
        $this->createDessertIngredients();
        
        // Create dessert recipes
        $this->createDessertRecipes();
    }

    private function createDessertIngredients(): void
    {
        $ingredients = [
            // Dessert-specific ingredients
            ['name' => 'malagkit na bigas', 'category' => 'Grain', 'description' => 'Glutinous rice'],
            ['name' => 'gata', 'category' => 'Dairy', 'description' => 'Coconut milk'],
            ['name' => 'asukal', 'category' => 'Sweetener', 'description' => 'Sugar'],
            ['name' => 'latik', 'category' => 'Dairy', 'description' => 'Coconut curd'],
            ['name' => 'niyog', 'category' => 'Dairy', 'description' => 'Coconut'],
            ['name' => 'ube', 'category' => 'Vegetable', 'description' => 'Purple yam'],
            ['name' => 'pandan', 'category' => 'Spice', 'description' => 'Pandan leaves'],
            ['name' => 'sago', 'category' => 'Ingredient', 'description' => 'Tapioca pearls'],
            ['name' => 'arnibal', 'category' => 'Sweetener', 'description' => 'Brown sugar syrup'],
            ['name' => 'condensed milk', 'category' => 'Dairy', 'description' => 'Condensed milk'],
            ['name' => 'evaporated milk', 'category' => 'Dairy', 'description' => 'Evaporated milk'],
            ['name' => 'rice flour', 'category' => 'Grain', 'description' => 'Rice flour'],
            ['name' => 'lye water', 'category' => 'Ingredient', 'description' => 'Lye water'],
            ['name' => 'cassava', 'category' => 'Vegetable', 'description' => 'Cassava root'],
            ['name' => 'cornstarch', 'category' => 'Grain', 'description' => 'Cornstarch'],
            ['name' => 'agar powder', 'category' => 'Ingredient', 'description' => 'Agar powder'],
            ['name' => 'young coconut', 'category' => 'Fruit', 'description' => 'Young coconut meat'],
            ['name' => 'mixed fruits', 'category' => 'Fruit', 'description' => 'Assorted fruits'],
            ['name' => 'cheese', 'category' => 'Dairy', 'description' => 'Cheese'],
            ['name' => 'cream', 'category' => 'Dairy', 'description' => 'Heavy cream'],
            ['name' => 'shaved ice', 'category' => 'Ingredient', 'description' => 'Shaved ice'],
            ['name' => 'leche flan', 'category' => 'Dessert', 'description' => 'Caramel custard'],
            ['name' => 'nata de coco', 'category' => 'Dessert', 'description' => 'Coconut gel'],
            ['name' => 'bread flour', 'category' => 'Grain', 'description' => 'Bread flour'],
            ['name' => 'yeast', 'category' => 'Ingredient', 'description' => 'Yeast'],
            ['name' => 'breadcrumbs', 'category' => 'Grain', 'description' => 'Breadcrumbs'],
            ['name' => 'sweet bean paste', 'category' => 'Ingredient', 'description' => 'Sweet bean paste'],
            ['name' => 'ground pork', 'category' => 'Protein', 'description' => 'Ground pork'],
            ['name' => 'dumpling wrapper', 'category' => 'Wrapper', 'description' => 'Dumpling wrapper'],
            ['name' => 'rice paper', 'category' => 'Wrapper', 'description' => 'Rice paper'],
            ['name' => 'bean sprouts', 'category' => 'Vegetable', 'description' => 'Bean sprouts'],
            ['name' => 'heart of palm', 'category' => 'Vegetable', 'description' => 'Heart of palm'],
            ['name' => 'jicama', 'category' => 'Vegetable', 'description' => 'Jicama'],
            ['name' => 'squash', 'category' => 'Vegetable', 'description' => 'Squash'],
            ['name' => 'chayote', 'category' => 'Vegetable', 'description' => 'Chayote'],
            ['name' => 'bottle gourd', 'category' => 'Vegetable', 'description' => 'Bottle gourd'],
            ['name' => 'sponge gourd', 'category' => 'Vegetable', 'description' => 'Sponge gourd'],
            ['name' => 'bitter gourd', 'category' => 'Vegetable', 'description' => 'Bitter gourd'],
            ['name' => 'water spinach', 'category' => 'Vegetable', 'description' => 'Water spinach'],
            ['name' => 'jute leaves', 'category' => 'Vegetable', 'description' => 'Jute leaves'],
            ['name' => 'moringa leaves', 'category' => 'Vegetable', 'description' => 'Moringa leaves'],
            ['name' => 'Chinese cabbage', 'category' => 'Vegetable', 'description' => 'Chinese cabbage'],
            ['name' => 'radish', 'category' => 'Vegetable', 'description' => 'Radish'],
            ['name' => 'macapuno', 'category' => 'Fruit', 'description' => 'Coconut sport'],
            ['name' => 'pie crust', 'category' => 'Dough', 'description' => 'Pie crust'],
            ['name' => 'flour', 'category' => 'Grain', 'description' => 'All-purpose flour'],
            ['name' => 'mantikilya', 'category' => 'Dairy', 'description' => 'Butter'],
            ['name' => 'powdered milk', 'category' => 'Dairy', 'description' => 'Powdered milk'],
            ['name' => 'cellophane', 'category' => 'Wrapper', 'description' => 'Cellophane wrapper'],
            ['name' => 'langka', 'category' => 'Fruit', 'description' => 'Jackfruit'],
            ['name' => 'saging', 'category' => 'Fruit', 'description' => 'Banana'],
            ['name' => 'saging saba', 'category' => 'Fruit', 'description' => 'Cooking banana'],
            ['name' => 'kamote', 'category' => 'Vegetable', 'description' => 'Sweet potato'],
            ['name' => 'kamoteng kahoy', 'category' => 'Vegetable', 'description' => 'Cassava'],
            ['name' => 'gawgaw', 'category' => 'Grain', 'description' => 'Cornstarch'],
            ['name' => 'bao ng niyog', 'category' => 'Fruit', 'description' => 'Coconut shell'],
            ['name' => 'vanilla', 'category' => 'Spice', 'description' => 'Vanilla extract'],
            ['name' => 'food coloring', 'category' => 'Ingredient', 'description' => 'Food coloring'],
            ['name' => 'ice', 'category' => 'Ingredient', 'description' => 'Ice cubes'],
            ['name' => 'purple rice flour', 'category' => 'Grain', 'description' => 'Purple rice flour'],
            ['name' => 'bamboo tubes', 'category' => 'Tool', 'description' => 'Bamboo tubes for steaming'],
            ['name' => 'silken tofu', 'category' => 'Protein', 'description' => 'Silken tofu'],
            ['name' => 'pandan jelly', 'category' => 'Dessert', 'description' => 'Pandan flavored jelly'],
            ['name' => 'sweet corn', 'category' => 'Vegetable', 'description' => 'Sweet corn'],
            ['name' => 'agar powder', 'category' => 'Ingredient', 'description' => 'Agar powder'],
            ['name' => 'gulaman', 'category' => 'Dessert', 'description' => 'Agar jelly'],
            ['name' => 'brown sugar syrup', 'category' => 'Sweetener', 'description' => 'Brown sugar syrup'],
            ['name' => 'pasko', 'category' => 'Occasion', 'description' => 'Christmas'],
            ['name' => 'mahal na araw', 'category' => 'Occasion', 'description' => 'Holy Week'],
            ['name' => 'meryenda', 'category' => 'Meal', 'description' => 'Snack time'],
            ['name' => 'handaan', 'category' => 'Occasion', 'description' => 'Feast'],
            ['name' => 'pista', 'category' => 'Occasion', 'description' => 'Festival'],
            ['name' => 'almusal', 'category' => 'Meal', 'description' => 'Breakfast'],
            ['name' => 'pasalubong', 'category' => 'Occasion', 'description' => 'Souvenir'],
            ['name' => 'panghimagas', 'category' => 'Meal', 'description' => 'Dessert'],
            ['name' => 'tag-init', 'category' => 'Season', 'description' => 'Summer'],
        ];

        foreach ($ingredients as $ingredient) {
            Ingredient::firstOrCreate(
                ['name' => $ingredient['name']],
                $ingredient
            );
        }
    }

    private function createDessertRecipes(): void
    {
        $recipes = [
            // Traditional Filipino Desserts (from Flutter RecipeService)
            [
                'name' => 'Bibingka',
                'description' => 'Traditional Filipino rice cake with coconut milk',
                'prep_time' => 15,
                'cook_time' => 25,
                'servings' => 8,
                'difficulty' => 'Medium',
                'category' => 'Dessert',
                'calories_per_serving' => 250,
                'protein_per_serving' => 5,
                'carbs_per_serving' => 45,
                'fat_per_serving' => 6,
                'instructions' => 'Mix rice flour with coconut milk, bake in banana leaves',
                'is_filipino_dish' => true,
                'ingredients' => ['malagkit na bigas', 'gata', 'asukal', 'itlog', 'baking powder'],
            ],
            [
                'name' => 'Biko',
                'description' => 'Sweet sticky rice cake with coconut milk',
                'prep_time' => 20,
                'cook_time' => 30,
                'servings' => 10,
                'difficulty' => 'Medium',
                'category' => 'Dessert',
                'calories_per_serving' => 280,
                'protein_per_serving' => 4,
                'carbs_per_serving' => 50,
                'fat_per_serving' => 7,
                'instructions' => 'Cook glutinous rice with coconut milk and brown sugar',
                'is_filipino_dish' => true,
                'ingredients' => ['malagkit na bigas', 'gata', 'brown sugar', 'latik'],
            ],
            [
                'name' => 'Halo-Halo',
                'description' => 'Filipino mixed dessert with shaved ice and various toppings',
                'prep_time' => 30,
                'cook_time' => 0,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 320,
                'protein_per_serving' => 6,
                'carbs_per_serving' => 55,
                'fat_per_serving' => 8,
                'instructions' => 'Layer shaved ice with various sweet ingredients and evaporated milk',
                'is_filipino_dish' => true,
                'ingredients' => ['shaved ice', 'evaporated milk', 'ube', 'leche flan', 'sago', 'nata de coco'],
            ],
            [
                'name' => 'Leche Flan',
                'description' => 'Filipino caramel custard dessert',
                'prep_time' => 20,
                'cook_time' => 40,
                'servings' => 8,
                'difficulty' => 'Medium',
                'category' => 'Dessert',
                'calories_per_serving' => 310,
                'protein_per_serving' => 6,
                'carbs_per_serving' => 45,
                'fat_per_serving' => 12,
                'instructions' => 'Make caramel, pour custard mixture, steam until set',
                'is_filipino_dish' => true,
                'ingredients' => ['itlog', 'gatas', 'asukal', 'vanilla'],
            ],
            [
                'name' => 'Ube Halaya',
                'description' => 'Purple yam jam dessert',
                'prep_time' => 15,
                'cook_time' => 45,
                'servings' => 8,
                'difficulty' => 'Medium',
                'category' => 'Dessert',
                'calories_per_serving' => 270,
                'protein_per_serving' => 4,
                'carbs_per_serving' => 45,
                'fat_per_serving' => 8,
                'instructions' => 'Cook purple yam with coconut milk and sugar until thick',
                'is_filipino_dish' => true,
                'ingredients' => ['ube', 'gatas', 'mantikilya', 'asukal', 'condensed milk'],
            ],
            [
                'name' => 'Sans Rival',
                'description' => 'Filipino layered cake with cashew meringue',
                'prep_time' => 45,
                'cook_time' => 30,
                'servings' => 12,
                'difficulty' => 'Hard',
                'category' => 'Dessert',
                'calories_per_serving' => 460,
                'protein_per_serving' => 8,
                'carbs_per_serving' => 40,
                'fat_per_serving' => 30,
                'instructions' => 'Make cashew meringue layers, fill with buttercream, chill',
                'is_filipino_dish' => true,
                'ingredients' => ['cashew', 'butter', 'itlog', 'asukal', 'flour'],
            ],
            [
                'name' => 'Polvoron',
                'description' => 'Filipino powdered milk candy',
                'prep_time' => 20,
                'cook_time' => 15,
                'servings' => 20,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 430,
                'protein_per_serving' => 8,
                'carbs_per_serving' => 50,
                'fat_per_serving' => 20,
                'instructions' => 'Toast flour, mix with powdered milk and sugar, shape into balls',
                'is_filipino_dish' => true,
                'ingredients' => ['harina', 'asukal', 'gatas', 'mantikilya', 'powdered milk'],
            ],
            [
                'name' => 'Yema',
                'description' => 'Filipino milk candy balls',
                'prep_time' => 15,
                'cook_time' => 20,
                'servings' => 15,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 400,
                'protein_per_serving' => 8,
                'carbs_per_serving' => 60,
                'fat_per_serving' => 15,
                'instructions' => 'Cook condensed milk with egg yolks, shape into balls, wrap in cellophane',
                'is_filipino_dish' => true,
                'ingredients' => ['itlog', 'gatas', 'asukal', 'condensed milk'],
            ],
            [
                'name' => 'Turon',
                'description' => 'Filipino banana spring roll dessert',
                'prep_time' => 20,
                'cook_time' => 15,
                'servings' => 8,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 180,
                'protein_per_serving' => 3,
                'carbs_per_serving' => 35,
                'fat_per_serving' => 4,
                'instructions' => 'Wrap banana and jackfruit in spring roll wrapper, fry until golden',
                'is_filipino_dish' => true,
                'ingredients' => ['saging', 'langka', 'spring roll wrapper', 'brown sugar', 'oil'],
            ],
            [
                'name' => 'Puto',
                'description' => 'Filipino steamed rice cake',
                'prep_time' => 15,
                'cook_time' => 20,
                'servings' => 12,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 120,
                'protein_per_serving' => 3,
                'carbs_per_serving' => 25,
                'fat_per_serving' => 1,
                'instructions' => 'Mix rice flour with water and sugar, steam in molds',
                'is_filipino_dish' => true,
                'ingredients' => ['rice flour', 'asukal', 'water', 'baking powder'],
            ],
            [
                'name' => 'Kutsinta',
                'description' => 'Filipino brown rice cake',
                'prep_time' => 10,
                'cook_time' => 25,
                'servings' => 12,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 90,
                'protein_per_serving' => 2,
                'carbs_per_serving' => 20,
                'fat_per_serving' => 1,
                'instructions' => 'Mix rice flour with brown sugar and water, steam until set',
                'is_filipino_dish' => true,
                'ingredients' => ['rice flour', 'brown sugar', 'water', 'lye water'],
            ],
            [
                'name' => 'Pichi-Pichi',
                'description' => 'Filipino cassava cake with coconut',
                'prep_time' => 15,
                'cook_time' => 20,
                'servings' => 10,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 150,
                'protein_per_serving' => 2,
                'carbs_per_serving' => 30,
                'fat_per_serving' => 3,
                'instructions' => 'Mix cassava with sugar and water, steam, roll in coconut',
                'is_filipino_dish' => true,
                'ingredients' => ['cassava', 'asukal', 'water', 'niyog', 'gata'],
            ],
            [
                'name' => 'Sapin-Sapin',
                'description' => 'Filipino layered glutinous rice cake',
                'prep_time' => 30,
                'cook_time' => 45,
                'servings' => 12,
                'difficulty' => 'Hard',
                'category' => 'Dessert',
                'calories_per_serving' => 220,
                'protein_per_serving' => 4,
                'carbs_per_serving' => 40,
                'fat_per_serving' => 6,
                'instructions' => 'Make different colored layers of glutinous rice, steam each layer',
                'is_filipino_dish' => true,
                'ingredients' => ['malagkit na bigas', 'gata', 'asukal', 'ube', 'pandan', 'latik'],
            ],
            [
                'name' => 'Maja Blanca',
                'description' => 'Filipino coconut pudding',
                'prep_time' => 15,
                'cook_time' => 20,
                'servings' => 8,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 160,
                'protein_per_serving' => 3,
                'carbs_per_serving' => 25,
                'fat_per_serving' => 6,
                'instructions' => 'Cook coconut milk with cornstarch and sugar until thick',
                'is_filipino_dish' => true,
                'ingredients' => ['gata', 'cornstarch', 'asukal', 'niyog', 'latik'],
            ],
            [
                'name' => 'Ginataang Bilo-Bilo',
                'description' => 'Filipino sweet soup with glutinous rice balls',
                'prep_time' => 20,
                'cook_time' => 25,
                'servings' => 6,
                'difficulty' => 'Medium',
                'category' => 'Dessert',
                'calories_per_serving' => 200,
                'protein_per_serving' => 4,
                'carbs_per_serving' => 35,
                'fat_per_serving' => 6,
                'instructions' => 'Make glutinous rice balls, cook in coconut milk with sweet potatoes and sago',
                'is_filipino_dish' => true,
                'ingredients' => ['malagkit na bigas', 'gata', 'kamote', 'sago', 'asukal'],
            ],
            [
                'name' => 'Taho',
                'description' => 'Filipino silken tofu dessert',
                'prep_time' => 5,
                'cook_time' => 10,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 80,
                'protein_per_serving' => 4,
                'carbs_per_serving' => 15,
                'fat_per_serving' => 1,
                'instructions' => 'Heat silken tofu, add brown sugar syrup and sago pearls',
                'is_filipino_dish' => true,
                'ingredients' => ['silken tofu', 'brown sugar', 'sago', 'water'],
            ],
            [
                'name' => 'Buko Pandan',
                'description' => 'Filipino coconut and pandan jelly dessert',
                'prep_time' => 20,
                'cook_time' => 15,
                'servings' => 8,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 140,
                'protein_per_serving' => 2,
                'carbs_per_serving' => 25,
                'fat_per_serving' => 4,
                'instructions' => 'Make pandan jelly, mix with young coconut, add cream and condensed milk',
                'is_filipino_dish' => true,
                'ingredients' => ['young coconut', 'pandan jelly', 'cream', 'condensed milk', 'gata'],
            ],
            [
                'name' => 'Mais Con Yelo',
                'description' => 'Filipino corn and ice dessert',
                'prep_time' => 10,
                'cook_time' => 0,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 120,
                'protein_per_serving' => 3,
                'carbs_per_serving' => 20,
                'fat_per_serving' => 3,
                'instructions' => 'Mix sweet corn with shaved ice, evaporated milk, and sugar',
                'is_filipino_dish' => true,
                'ingredients' => ['sweet corn', 'shaved ice', 'evaporated milk', 'asukal'],
            ],
            [
                'name' => 'Gulaman',
                'description' => 'Filipino agar jelly dessert',
                'prep_time' => 15,
                'cook_time' => 10,
                'servings' => 6,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 60,
                'protein_per_serving' => 1,
                'carbs_per_serving' => 12,
                'fat_per_serving' => 0,
                'instructions' => 'Dissolve agar powder in water, add sugar and flavoring, let set',
                'is_filipino_dish' => true,
                'ingredients' => ['agar powder', 'water', 'asukal', 'food coloring'],
            ],
            [
                'name' => 'Sago at Gulaman',
                'description' => 'Filipino sago and jelly drink',
                'prep_time' => 20,
                'cook_time' => 15,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 100,
                'protein_per_serving' => 1,
                'carbs_per_serving' => 20,
                'fat_per_serving' => 0,
                'instructions' => 'Cook sago pearls, make gulaman jelly, mix with brown sugar syrup',
                'is_filipino_dish' => true,
                'ingredients' => ['sago', 'gulaman', 'brown sugar', 'water', 'ice'],
            ],
            [
                'name' => 'Puto Bumbong',
                'description' => 'Filipino purple rice cake steamed in bamboo',
                'prep_time' => 30,
                'cook_time' => 20,
                'servings' => 8,
                'difficulty' => 'Medium',
                'category' => 'Dessert',
                'calories_per_serving' => 200,
                'protein_per_serving' => 4,
                'carbs_per_serving' => 35,
                'fat_per_serving' => 5,
                'instructions' => 'Mix purple rice flour with coconut milk, steam in bamboo tubes',
                'is_filipino_dish' => true,
                'ingredients' => ['purple rice flour', 'gata', 'asukal', 'niyog', 'latik'],
            ],
            [
                'name' => 'Bibingkang Malagkit',
                'description' => 'Filipino glutinous rice cake',
                'prep_time' => 20,
                'cook_time' => 30,
                'servings' => 10,
                'difficulty' => 'Medium',
                'category' => 'Dessert',
                'calories_per_serving' => 240,
                'protein_per_serving' => 4,
                'carbs_per_serving' => 42,
                'fat_per_serving' => 6,
                'instructions' => 'Mix glutinous rice with coconut milk and sugar, bake until set',
                'is_filipino_dish' => true,
                'ingredients' => ['malagkit na bigas', 'gata', 'asukal', 'latik'],
            ],
            [
                'name' => 'Kakanin',
                'description' => 'Filipino rice cake assortment',
                'prep_time' => 25,
                'cook_time' => 35,
                'servings' => 12,
                'difficulty' => 'Medium',
                'category' => 'Dessert',
                'calories_per_serving' => 180,
                'protein_per_serving' => 3,
                'carbs_per_serving' => 32,
                'fat_per_serving' => 4,
                'instructions' => 'Make various rice cakes with different flavors and colors',
                'is_filipino_dish' => true,
                'ingredients' => ['rice flour', 'gata', 'asukal', 'food coloring', 'niyog'],
            ],
            [
                'name' => 'Buko Salad',
                'description' => 'Filipino young coconut fruit salad',
                'prep_time' => 20,
                'cook_time' => 0,
                'servings' => 8,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 180,
                'protein_per_serving' => 3,
                'carbs_per_serving' => 35,
                'fat_per_serving' => 5,
                'instructions' => 'Mix young coconut with various fruits and cream',
                'is_filipino_dish' => true,
                'ingredients' => ['young coconut', 'mixed fruits', 'cream', 'condensed milk', 'cheese'],
            ],
            [
                'name' => 'Macapuno',
                'description' => 'Filipino coconut sport dessert',
                'prep_time' => 15,
                'cook_time' => 30,
                'servings' => 6,
                'difficulty' => 'Medium',
                'category' => 'Dessert',
                'calories_per_serving' => 200,
                'protein_per_serving' => 2,
                'carbs_per_serving' => 40,
                'fat_per_serving' => 4,
                'instructions' => 'Cook coconut sport with sugar and water until thick',
                'is_filipino_dish' => true,
                'ingredients' => ['macapuno', 'asukal', 'water', 'gata'],
            ],
            [
                'name' => 'Buko Pie',
                'description' => 'Filipino young coconut pie',
                'prep_time' => 30,
                'cook_time' => 45,
                'servings' => 8,
                'difficulty' => 'Hard',
                'category' => 'Dessert',
                'calories_per_serving' => 350,
                'protein_per_serving' => 6,
                'carbs_per_serving' => 45,
                'fat_per_serving' => 16,
                'instructions' => 'Make pie crust, fill with young coconut mixture, bake until golden',
                'is_filipino_dish' => true,
                'ingredients' => ['young coconut', 'pie crust', 'milk', 'sugar', 'cornstarch'],
            ],
            [
                'name' => 'Ensaymada',
                'description' => 'Filipino sweet bread with cheese and butter',
                'prep_time' => 60,
                'cook_time' => 25,
                'servings' => 12,
                'difficulty' => 'Hard',
                'category' => 'Dessert',
                'calories_per_serving' => 280,
                'protein_per_serving' => 8,
                'carbs_per_serving' => 35,
                'fat_per_serving' => 12,
                'instructions' => 'Make sweet bread dough, roll with butter and sugar, top with cheese',
                'is_filipino_dish' => true,
                'ingredients' => ['bread flour', 'sugar', 'butter', 'cheese', 'yeast'],
            ],
            [
                'name' => 'Pan de Sal',
                'description' => 'Filipino salt bread rolls',
                'prep_time' => 30,
                'cook_time' => 20,
                'servings' => 12,
                'difficulty' => 'Medium',
                'category' => 'Dessert',
                'calories_per_serving' => 120,
                'protein_per_serving' => 4,
                'carbs_per_serving' => 22,
                'fat_per_serving' => 2,
                'instructions' => 'Make bread dough with salt, shape into rolls, bake until golden',
                'is_filipino_dish' => true,
                'ingredients' => ['bread flour', 'salt', 'yeast', 'water', 'oil'],
            ],
            [
                'name' => 'Pandesal',
                'description' => 'Filipino sweet bread rolls',
                'prep_time' => 30,
                'cook_time' => 20,
                'servings' => 12,
                'difficulty' => 'Medium',
                'category' => 'Dessert',
                'calories_per_serving' => 140,
                'protein_per_serving' => 4,
                'carbs_per_serving' => 25,
                'fat_per_serving' => 3,
                'instructions' => 'Make sweet bread dough, shape into rolls, bake until golden',
                'is_filipino_dish' => true,
                'ingredients' => ['bread flour', 'sugar', 'yeast', 'water', 'oil'],
            ],
            [
                'name' => 'Monay',
                'description' => 'Filipino dense bread',
                'prep_time' => 25,
                'cook_time' => 30,
                'servings' => 8,
                'difficulty' => 'Medium',
                'category' => 'Dessert',
                'calories_per_serving' => 180,
                'protein_per_serving' => 5,
                'carbs_per_serving' => 30,
                'fat_per_serving' => 4,
                'instructions' => 'Make dense bread dough, shape into oval, bake until golden',
                'is_filipino_dish' => true,
                'ingredients' => ['bread flour', 'sugar', 'yeast', 'water', 'oil'],
            ],
            [
                'name' => 'Spanish Bread',
                'description' => 'Filipino sweet bread with filling',
                'prep_time' => 40,
                'cook_time' => 25,
                'servings' => 10,
                'difficulty' => 'Medium',
                'category' => 'Dessert',
                'calories_per_serving' => 220,
                'protein_per_serving' => 6,
                'carbs_per_serving' => 32,
                'fat_per_serving' => 7,
                'instructions' => 'Make sweet bread dough, fill with butter and sugar mixture, bake',
                'is_filipino_dish' => true,
                'ingredients' => ['bread flour', 'sugar', 'butter', 'yeast', 'breadcrumbs'],
            ],
            [
                'name' => 'Hopia',
                'description' => 'Filipino flaky pastry with sweet filling',
                'prep_time' => 45,
                'cook_time' => 30,
                'servings' => 15,
                'difficulty' => 'Hard',
                'category' => 'Dessert',
                'calories_per_serving' => 250,
                'protein_per_serving' => 5,
                'carbs_per_serving' => 35,
                'fat_per_serving' => 10,
                'instructions' => 'Make flaky pastry dough, fill with sweet bean paste, bake until golden',
                'is_filipino_dish' => true,
                'ingredients' => ['flour', 'butter', 'sweet bean paste', 'sugar', 'oil'],
            ],
            [
                'name' => 'Hopiang Baboy',
                'description' => 'Filipino flaky pastry with pork filling',
                'prep_time' => 45,
                'cook_time' => 30,
                'servings' => 15,
                'difficulty' => 'Hard',
                'category' => 'Dessert',
                'calories_per_serving' => 280,
                'protein_per_serving' => 8,
                'carbs_per_serving' => 30,
                'fat_per_serving' => 12,
                'instructions' => 'Make flaky pastry dough, fill with seasoned pork, bake until golden',
                'is_filipino_dish' => true,
                'ingredients' => ['flour', 'butter', 'ground pork', 'onion', 'garlic'],
            ],
            [
                'name' => 'Empanada',
                'description' => 'Filipino meat-filled pastry',
                'prep_time' => 30,
                'cook_time' => 25,
                'servings' => 8,
                'difficulty' => 'Medium',
                'category' => 'Dessert',
                'calories_per_serving' => 200,
                'protein_per_serving' => 8,
                'carbs_per_serving' => 25,
                'fat_per_serving' => 8,
                'instructions' => 'Make pastry dough, fill with meat mixture, seal and fry',
                'is_filipino_dish' => true,
                'ingredients' => ['flour', 'ground meat', 'onion', 'garlic', 'potatoes'],
            ],
            [
                'name' => 'Siopao',
                'description' => 'Filipino steamed bun with meat filling',
                'prep_time' => 40,
                'cook_time' => 20,
                'servings' => 8,
                'difficulty' => 'Medium',
                'category' => 'Dessert',
                'calories_per_serving' => 180,
                'protein_per_serving' => 8,
                'carbs_per_serving' => 28,
                'fat_per_serving' => 4,
                'instructions' => 'Make bun dough, fill with meat mixture, steam until cooked',
                'is_filipino_dish' => true,
                'ingredients' => ['flour', 'ground meat', 'onion', 'garlic', 'yeast'],
            ],
            [
                'name' => 'Siomai',
                'description' => 'Filipino steamed dumpling',
                'prep_time' => 30,
                'cook_time' => 15,
                'servings' => 12,
                'difficulty' => 'Medium',
                'category' => 'Dessert',
                'calories_per_serving' => 80,
                'protein_per_serving' => 6,
                'carbs_per_serving' => 8,
                'fat_per_serving' => 2,
                'instructions' => 'Make dumpling wrapper, fill with meat mixture, steam until cooked',
                'is_filipino_dish' => true,
                'ingredients' => ['dumpling wrapper', 'ground meat', 'onion', 'garlic', 'soy sauce'],
            ],
            [
                'name' => 'Lumpia',
                'description' => 'Filipino spring roll',
                'prep_time' => 25,
                'cook_time' => 15,
                'servings' => 10,
                'difficulty' => 'Medium',
                'category' => 'Dessert',
                'calories_per_serving' => 120,
                'protein_per_serving' => 5,
                'carbs_per_serving' => 15,
                'fat_per_serving' => 4,
                'instructions' => 'Wrap vegetable mixture in spring roll wrapper, fry until golden',
                'is_filipino_dish' => true,
                'ingredients' => ['spring roll wrapper', 'vegetables', 'onion', 'garlic', 'oil'],
            ],
            [
                'name' => 'Lumpiang Gulay',
                'description' => 'Filipino vegetable spring roll',
                'prep_time' => 25,
                'cook_time' => 15,
                'servings' => 10,
                'difficulty' => 'Medium',
                'category' => 'Dessert',
                'calories_per_serving' => 100,
                'protein_per_serving' => 4,
                'carbs_per_serving' => 12,
                'fat_per_serving' => 3,
                'instructions' => 'Wrap mixed vegetables in spring roll wrapper, fry until golden',
                'is_filipino_dish' => true,
                'ingredients' => ['spring roll wrapper', 'mixed vegetables', 'onion', 'garlic', 'oil'],
            ],
            [
                'name' => 'Lumpiang Sariwa',
                'description' => 'Filipino fresh spring roll',
                'prep_time' => 20,
                'cook_time' => 10,
                'servings' => 8,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 80,
                'protein_per_serving' => 3,
                'carbs_per_serving' => 10,
                'fat_per_serving' => 2,
                'instructions' => 'Wrap fresh vegetables in rice paper, serve with sweet sauce',
                'is_filipino_dish' => true,
                'ingredients' => ['rice paper', 'fresh vegetables', 'lettuce', 'carrots', 'sweet sauce'],
            ],
            [
                'name' => 'Lumpiang Hubad',
                'description' => 'Filipino naked spring roll',
                'prep_time' => 15,
                'cook_time' => 10,
                'servings' => 6,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 90,
                'protein_per_serving' => 4,
                'carbs_per_serving' => 12,
                'fat_per_serving' => 2,
                'instructions' => 'Mix vegetables with sauce, serve without wrapper',
                'is_filipino_dish' => true,
                'ingredients' => ['mixed vegetables', 'sweet sauce', 'onion', 'garlic', 'oil'],
            ],
            [
                'name' => 'Lumpiang Togue',
                'description' => 'Filipino bean sprout spring roll',
                'prep_time' => 20,
                'cook_time' => 12,
                'servings' => 8,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 70,
                'protein_per_serving' => 3,
                'carbs_per_serving' => 8,
                'fat_per_serving' => 2,
                'instructions' => 'Wrap bean sprouts in spring roll wrapper, fry until golden',
                'is_filipino_dish' => true,
                'ingredients' => ['spring roll wrapper', 'bean sprouts', 'onion', 'garlic', 'oil'],
            ],
            [
                'name' => 'Lumpiang Ubod',
                'description' => 'Filipino heart of palm spring roll',
                'prep_time' => 25,
                'cook_time' => 15,
                'servings' => 8,
                'difficulty' => 'Medium',
                'category' => 'Dessert',
                'calories_per_serving' => 110,
                'protein_per_serving' => 4,
                'carbs_per_serving' => 12,
                'fat_per_serving' => 4,
                'instructions' => 'Wrap heart of palm mixture in spring roll wrapper, fry until golden',
                'is_filipino_dish' => true,
                'ingredients' => ['spring roll wrapper', 'heart of palm', 'onion', 'garlic', 'oil'],
            ],
            [
                'name' => 'Lumpiang Singkamas',
                'description' => 'Filipino jicama spring roll',
                'prep_time' => 20,
                'cook_time' => 12,
                'servings' => 8,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 85,
                'protein_per_serving' => 3,
                'carbs_per_serving' => 10,
                'fat_per_serving' => 2,
                'instructions' => 'Wrap jicama mixture in spring roll wrapper, fry until golden',
                'is_filipino_dish' => true,
                'ingredients' => ['spring roll wrapper', 'jicama', 'onion', 'garlic', 'oil'],
            ],
            [
                'name' => 'Lumpiang Kamote',
                'description' => 'Filipino sweet potato spring roll',
                'prep_time' => 20,
                'cook_time' => 12,
                'servings' => 8,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 95,
                'protein_per_serving' => 3,
                'carbs_per_serving' => 15,
                'fat_per_serving' => 2,
                'instructions' => 'Wrap sweet potato mixture in spring roll wrapper, fry until golden',
                'is_filipino_dish' => true,
                'ingredients' => ['spring roll wrapper', 'sweet potato', 'onion', 'garlic', 'oil'],
            ],
            [
                'name' => 'Lumpiang Kalabasa',
                'description' => 'Filipino squash spring roll',
                'prep_time' => 20,
                'cook_time' => 12,
                'servings' => 8,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 80,
                'protein_per_serving' => 3,
                'carbs_per_serving' => 10,
                'fat_per_serving' => 2,
                'instructions' => 'Wrap squash mixture in spring roll wrapper, fry until golden',
                'is_filipino_dish' => true,
                'ingredients' => ['spring roll wrapper', 'squash', 'onion', 'garlic', 'oil'],
            ],
            [
                'name' => 'Lumpiang Sayote',
                'description' => 'Filipino chayote spring roll',
                'prep_time' => 20,
                'cook_time' => 12,
                'servings' => 8,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 75,
                'protein_per_serving' => 3,
                'carbs_per_serving' => 8,
                'fat_per_serving' => 2,
                'instructions' => 'Wrap chayote mixture in spring roll wrapper, fry until golden',
                'is_filipino_dish' => true,
                'ingredients' => ['spring roll wrapper', 'chayote', 'onion', 'garlic', 'oil'],
            ],
            [
                'name' => 'Lumpiang Upo',
                'description' => 'Filipino bottle gourd spring roll',
                'prep_time' => 20,
                'cook_time' => 12,
                'servings' => 8,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 70,
                'protein_per_serving' => 3,
                'carbs_per_serving' => 8,
                'fat_per_serving' => 2,
                'instructions' => 'Wrap bottle gourd mixture in spring roll wrapper, fry until golden',
                'is_filipino_dish' => true,
                'ingredients' => ['spring roll wrapper', 'bottle gourd', 'onion', 'garlic', 'oil'],
            ],
            [
                'name' => 'Lumpiang Patola',
                'description' => 'Filipino sponge gourd spring roll',
                'prep_time' => 20,
                'cook_time' => 12,
                'servings' => 8,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 75,
                'protein_per_serving' => 3,
                'carbs_per_serving' => 8,
                'fat_per_serving' => 2,
                'instructions' => 'Wrap sponge gourd mixture in spring roll wrapper, fry until golden',
                'is_filipino_dish' => true,
                'ingredients' => ['spring roll wrapper', 'sponge gourd', 'onion', 'garlic', 'oil'],
            ],
            [
                'name' => 'Lumpiang Talong',
                'description' => 'Filipino eggplant spring roll',
                'prep_time' => 20,
                'cook_time' => 12,
                'servings' => 8,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 85,
                'protein_per_serving' => 3,
                'carbs_per_serving' => 10,
                'fat_per_serving' => 2,
                'instructions' => 'Wrap eggplant mixture in spring roll wrapper, fry until golden',
                'is_filipino_dish' => true,
                'ingredients' => ['spring roll wrapper', 'eggplant', 'onion', 'garlic', 'oil'],
            ],
            [
                'name' => 'Lumpiang Ampalaya',
                'description' => 'Filipino bitter gourd spring roll',
                'prep_time' => 20,
                'cook_time' => 12,
                'servings' => 8,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 80,
                'protein_per_serving' => 3,
                'carbs_per_serving' => 8,
                'fat_per_serving' => 2,
                'instructions' => 'Wrap bitter gourd mixture in spring roll wrapper, fry until golden',
                'is_filipino_dish' => true,
                'ingredients' => ['spring roll wrapper', 'bitter gourd', 'onion', 'garlic', 'oil'],
            ],
            [
                'name' => 'Lumpiang Kangkong',
                'description' => 'Filipino water spinach spring roll',
                'prep_time' => 20,
                'cook_time' => 12,
                'servings' => 8,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 70,
                'protein_per_serving' => 3,
                'carbs_per_serving' => 8,
                'fat_per_serving' => 2,
                'instructions' => 'Wrap water spinach mixture in spring roll wrapper, fry until golden',
                'is_filipino_dish' => true,
                'ingredients' => ['spring roll wrapper', 'water spinach', 'onion', 'garlic', 'oil'],
            ],
            [
                'name' => 'Lumpiang Saluyot',
                'description' => 'Filipino jute leaves spring roll',
                'prep_time' => 20,
                'cook_time' => 12,
                'servings' => 8,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 75,
                'protein_per_serving' => 3,
                'carbs_per_serving' => 8,
                'fat_per_serving' => 2,
                'instructions' => 'Wrap jute leaves mixture in spring roll wrapper, fry until golden',
                'is_filipino_dish' => true,
                'ingredients' => ['spring roll wrapper', 'jute leaves', 'onion', 'garlic', 'oil'],
            ],
            [
                'name' => 'Lumpiang Malunggay',
                'description' => 'Filipino moringa leaves spring roll',
                'prep_time' => 20,
                'cook_time' => 12,
                'servings' => 8,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 80,
                'protein_per_serving' => 4,
                'carbs_per_serving' => 8,
                'fat_per_serving' => 2,
                'instructions' => 'Wrap moringa leaves mixture in spring roll wrapper, fry until golden',
                'is_filipino_dish' => true,
                'ingredients' => ['spring roll wrapper', 'moringa leaves', 'onion', 'garlic', 'oil'],
            ],
            [
                'name' => 'Lumpiang Pechay',
                'description' => 'Filipino Chinese cabbage spring roll',
                'prep_time' => 20,
                'cook_time' => 12,
                'servings' => 8,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 70,
                'protein_per_serving' => 3,
                'carbs_per_serving' => 8,
                'fat_per_serving' => 2,
                'instructions' => 'Wrap Chinese cabbage mixture in spring roll wrapper, fry until golden',
                'is_filipino_dish' => true,
                'ingredients' => ['spring roll wrapper', 'Chinese cabbage', 'onion', 'garlic', 'oil'],
            ],
            [
                'name' => 'Lumpiang Repolyo',
                'description' => 'Filipino cabbage spring roll',
                'prep_time' => 20,
                'cook_time' => 12,
                'servings' => 8,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 75,
                'protein_per_serving' => 3,
                'carbs_per_serving' => 8,
                'fat_per_serving' => 2,
                'instructions' => 'Wrap cabbage mixture in spring roll wrapper, fry until golden',
                'is_filipino_dish' => true,
                'ingredients' => ['spring roll wrapper', 'cabbage', 'onion', 'garlic', 'oil'],
            ],
            [
                'name' => 'Lumpiang Labanos',
                'description' => 'Filipino radish spring roll',
                'prep_time' => 20,
                'cook_time' => 12,
                'servings' => 8,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 70,
                'protein_per_serving' => 3,
                'carbs_per_serving' => 8,
                'fat_per_serving' => 2,
                'instructions' => 'Wrap radish mixture in spring roll wrapper, fry until golden',
                'is_filipino_dish' => true,
                'ingredients' => ['spring roll wrapper', 'radish', 'onion', 'garlic', 'oil'],
            ],
        ];

        foreach ($recipes as $recipeData) {
            $ingredients = $recipeData['ingredients'];
            unset($recipeData['ingredients']);
            
            $recipe = Recipe::firstOrCreate(
                ['name' => $recipeData['name']],
                $recipeData
            );

            // Attach ingredients to recipe
            foreach ($ingredients as $ingredientName) {
                $ingredient = Ingredient::where('name', $ingredientName)->first();
                if ($ingredient && !$recipe->ingredients()->where('ingredient_id', $ingredient->id)->exists()) {
                    $recipe->ingredients()->attach($ingredient->id, [
                        'quantity' => '1',
                        'unit' => 'piece'
                    ]);
                }
            }
        }
    }
}
