<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Recipe;
use App\Models\Ingredient;

class FinalFlutterRecipesSeeder extends Seeder
{
    public function run(): void
    {
        $this->createFinalRecipes();
    }

    private function createFinalRecipes(): void
    {
        // Batch 3: Additional Filipino Dishes and Desserts (86 recipes)
        $recipes = [
            // Additional Filipino Main Dishes
            [
                'name' => 'Mango Float',
                'description' => 'Filipino no-bake mango dessert',
                'prep_time' => 30,
                'cook_time' => 0,
                'servings' => 8,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 280,
                'protein_per_serving' => 6,
                'carbs_per_serving' => 35,
                'fat_per_serving' => 12,
                'instructions' => 'Layer graham crackers with mango and cream mixture',
                'is_filipino_dish' => true,
                'ingredients' => ['mango', 'graham crackers', 'condensed milk', 'cream', 'sugar'],
            ],
            [
                'name' => 'Buko Pandan',
                'description' => 'Coconut and pandan dessert',
                'prep_time' => 20,
                'cook_time' => 15,
                'servings' => 6,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 160,
                'protein_per_serving' => 3,
                'carbs_per_serving' => 25,
                'fat_per_serving' => 5,
                'instructions' => 'Mix coconut with pandan jelly and cream',
                'is_filipino_dish' => true,
                'ingredients' => ['coconut', 'pandan jelly', 'condensed milk', 'cream', 'sugar'],
            ],
            [
                'name' => 'Buko Salad',
                'description' => 'Filipino fruit salad with coconut',
                'prep_time' => 20,
                'cook_time' => 0,
                'servings' => 6,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 180,
                'protein_per_serving' => 4,
                'carbs_per_serving' => 28,
                'fat_per_serving' => 6,
                'instructions' => 'Mix coconut with mixed fruits and cream',
                'is_filipino_dish' => true,
                'ingredients' => ['coconut', 'mixed fruits', 'condensed milk', 'cream', 'sugar'],
            ],
            [
                'name' => 'Ginataang Bilo-Bilo',
                'description' => 'Sweet rice balls in coconut milk',
                'prep_time' => 20,
                'cook_time' => 25,
                'servings' => 6,
                'difficulty' => 'Medium',
                'category' => 'Dessert',
                'calories_per_serving' => 220,
                'protein_per_serving' => 5,
                'carbs_per_serving' => 38,
                'fat_per_serving' => 6,
                'instructions' => 'Make rice balls, cook in coconut milk with fruits',
                'is_filipino_dish' => true,
                'ingredients' => ['malagkit na bigas', 'coconut milk', 'sugar', 'banana', 'jackfruit'],
            ],
            [
                'name' => 'Taho',
                'description' => 'Filipino silken tofu dessert',
                'prep_time' => 10,
                'cook_time' => 15,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 80,
                'protein_per_serving' => 6,
                'carbs_per_serving' => 12,
                'fat_per_serving' => 1,
                'instructions' => 'Serve silken tofu with syrup and tapioca',
                'is_filipino_dish' => true,
                'ingredients' => ['silken tofu', 'syrup', 'tapioca', 'sugar'],
            ],
            [
                'name' => 'Mais Con Yelo',
                'description' => 'Filipino corn and ice dessert',
                'prep_time' => 15,
                'cook_time' => 10,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 120,
                'protein_per_serving' => 3,
                'carbs_per_serving' => 22,
                'fat_per_serving' => 2,
                'instructions' => 'Mix corn with ice, milk, and sugar',
                'is_filipino_dish' => true,
                'ingredients' => ['corn', 'ice', 'milk', 'sugar', 'condensed milk'],
            ],
            [
                'name' => 'Sago at Gulaman',
                'description' => 'Filipino tapioca and jelly drink',
                'prep_time' => 20,
                'cook_time' => 15,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 100,
                'protein_per_serving' => 2,
                'carbs_per_serving' => 20,
                'fat_per_serving' => 1,
                'instructions' => 'Cook tapioca and jelly, mix with syrup',
                'is_filipino_dish' => true,
                'ingredients' => ['tapioca', 'gelatin', 'syrup', 'sugar', 'water'],
            ],
            [
                'name' => 'Puto Bumbong',
                'description' => 'Filipino purple rice cake',
                'prep_time' => 30,
                'cook_time' => 20,
                'servings' => 8,
                'difficulty' => 'Medium',
                'category' => 'Dessert',
                'calories_per_serving' => 200,
                'protein_per_serving' => 4,
                'carbs_per_serving' => 38,
                'fat_per_serving' => 3,
                'instructions' => 'Steam purple rice mixture in bamboo tubes',
                'is_filipino_dish' => true,
                'ingredients' => ['malagkit na bigas', 'ube', 'coconut milk', 'sugar', 'banana leaves'],
            ],
            [
                'name' => 'Bibingkang Malagkit',
                'description' => 'Filipino sticky rice cake',
                'prep_time' => 20,
                'cook_time' => 30,
                'servings' => 8,
                'difficulty' => 'Medium',
                'category' => 'Dessert',
                'calories_per_serving' => 240,
                'protein_per_serving' => 5,
                'carbs_per_serving' => 42,
                'fat_per_serving' => 5,
                'instructions' => 'Cook sticky rice with coconut milk and sugar',
                'is_filipino_dish' => true,
                'ingredients' => ['malagkit na bigas', 'coconut milk', 'sugar', 'banana leaves'],
            ],
            [
                'name' => 'Kakanin',
                'description' => 'Filipino rice cake assortment',
                'prep_time' => 25,
                'cook_time' => 35,
                'servings' => 8,
                'difficulty' => 'Medium',
                'category' => 'Dessert',
                'calories_per_serving' => 180,
                'protein_per_serving' => 4,
                'carbs_per_serving' => 32,
                'fat_per_serving' => 4,
                'instructions' => 'Make various rice cakes with coconut milk',
                'is_filipino_dish' => true,
                'ingredients' => ['malagkit na bigas', 'coconut milk', 'sugar', 'banana leaves'],
            ],
            // Additional Filipino Breakfast Dishes
            [
                'name' => 'Tocino',
                'description' => 'Filipino sweet cured pork',
                'prep_time' => 10,
                'cook_time' => 15,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Filipino',
                'calories_per_serving' => 280,
                'protein_per_serving' => 22,
                'carbs_per_serving' => 8,
                'fat_per_serving' => 16,
                'instructions' => 'Fry sweet cured pork until caramelized',
                'is_filipino_dish' => true,
                'ingredients' => ['tocino', 'cooking oil', 'garlic', 'onion'],
            ],
            [
                'name' => 'Longganisa',
                'description' => 'Filipino sausage',
                'prep_time' => 10,
                'cook_time' => 15,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Filipino',
                'calories_per_serving' => 320,
                'protein_per_serving' => 18,
                'carbs_per_serving' => 6,
                'fat_per_serving' => 24,
                'instructions' => 'Fry Filipino sausage until cooked',
                'is_filipino_dish' => true,
                'ingredients' => ['longganisa', 'cooking oil', 'garlic', 'onion'],
            ],
            [
                'name' => 'Tocilog',
                'description' => 'Tocino, Sinangag, at Itlog',
                'prep_time' => 15,
                'cook_time' => 20,
                'servings' => 2,
                'difficulty' => 'Easy',
                'category' => 'Filipino',
                'calories_per_serving' => 480,
                'protein_per_serving' => 25,
                'carbs_per_serving' => 52,
                'fat_per_serving' => 20,
                'instructions' => 'Cook tocino, garlic rice, and egg',
                'is_filipino_dish' => true,
                'ingredients' => ['tocino', 'garlic rice', 'egg', 'garlic', 'soy sauce'],
            ],
            [
                'name' => 'Longsilog',
                'description' => 'Longganisa, Sinangag, at Itlog',
                'prep_time' => 15,
                'cook_time' => 20,
                'servings' => 2,
                'difficulty' => 'Easy',
                'category' => 'Filipino',
                'calories_per_serving' => 520,
                'protein_per_serving' => 28,
                'carbs_per_serving' => 58,
                'fat_per_serving' => 22,
                'instructions' => 'Cook longganisa, garlic rice, and egg',
                'is_filipino_dish' => true,
                'ingredients' => ['longganisa', 'garlic rice', 'egg', 'garlic', 'soy sauce'],
            ],
            [
                'name' => 'Bangsilog',
                'description' => 'Bangus, Sinangag, at Itlog',
                'prep_time' => 15,
                'cook_time' => 20,
                'servings' => 2,
                'difficulty' => 'Easy',
                'category' => 'Filipino',
                'calories_per_serving' => 450,
                'protein_per_serving' => 32,
                'carbs_per_serving' => 48,
                'fat_per_serving' => 16,
                'instructions' => 'Cook bangus, garlic rice, and egg',
                'is_filipino_dish' => true,
                'ingredients' => ['bangus', 'garlic rice', 'egg', 'garlic', 'soy sauce'],
            ],
            [
                'name' => 'Chicksilog',
                'description' => 'Chicken, Sinangag, at Itlog',
                'prep_time' => 15,
                'cook_time' => 20,
                'servings' => 2,
                'difficulty' => 'Easy',
                'category' => 'Filipino',
                'calories_per_serving' => 420,
                'protein_per_serving' => 30,
                'carbs_per_serving' => 46,
                'fat_per_serving' => 14,
                'instructions' => 'Cook chicken, garlic rice, and egg',
                'is_filipino_dish' => true,
                'ingredients' => ['chicken', 'garlic rice', 'egg', 'garlic', 'soy sauce'],
            ],
            [
                'name' => 'Porksilog',
                'description' => 'Pork, Sinangag, at Itlog',
                'prep_time' => 15,
                'cook_time' => 20,
                'servings' => 2,
                'difficulty' => 'Easy',
                'category' => 'Filipino',
                'calories_per_serving' => 480,
                'protein_per_serving' => 28,
                'carbs_per_serving' => 50,
                'fat_per_serving' => 20,
                'instructions' => 'Cook pork, garlic rice, and egg',
                'is_filipino_dish' => true,
                'ingredients' => ['pork', 'garlic rice', 'egg', 'garlic', 'soy sauce'],
            ],
            [
                'name' => 'Beefsilog',
                'description' => 'Beef, Sinangag, at Itlog',
                'prep_time' => 15,
                'cook_time' => 20,
                'servings' => 2,
                'difficulty' => 'Easy',
                'category' => 'Filipino',
                'calories_per_serving' => 500,
                'protein_per_serving' => 32,
                'carbs_per_serving' => 52,
                'fat_per_serving' => 18,
                'instructions' => 'Cook beef, garlic rice, and egg',
                'is_filipino_dish' => true,
                'ingredients' => ['beef', 'garlic rice', 'egg', 'garlic', 'soy sauce'],
            ],
            [
                'name' => 'Hotsilog',
                'description' => 'Hotdog, Sinangag, at Itlog',
                'prep_time' => 15,
                'cook_time' => 20,
                'servings' => 2,
                'difficulty' => 'Easy',
                'category' => 'Filipino',
                'calories_per_serving' => 380,
                'protein_per_serving' => 18,
                'carbs_per_serving' => 44,
                'fat_per_serving' => 16,
                'instructions' => 'Cook hotdog, garlic rice, and egg',
                'is_filipino_dish' => true,
                'ingredients' => ['hotdog', 'garlic rice', 'egg', 'garlic', 'soy sauce'],
            ],
            [
                'name' => 'Spamsilog',
                'description' => 'Spam, Sinangag, at Itlog',
                'prep_time' => 15,
                'cook_time' => 20,
                'servings' => 2,
                'difficulty' => 'Easy',
                'category' => 'Filipino',
                'calories_per_serving' => 420,
                'protein_per_serving' => 20,
                'carbs_per_serving' => 46,
                'fat_per_serving' => 18,
                'instructions' => 'Cook spam, garlic rice, and egg',
                'is_filipino_dish' => true,
                'ingredients' => ['spam', 'garlic rice', 'egg', 'garlic', 'soy sauce'],
            ],
            [
                'name' => 'Cornsilog',
                'description' => 'Corned beef, Sinangag, at Itlog',
                'prep_time' => 15,
                'cook_time' => 20,
                'servings' => 2,
                'difficulty' => 'Easy',
                'category' => 'Filipino',
                'calories_per_serving' => 460,
                'protein_per_serving' => 24,
                'carbs_per_serving' => 48,
                'fat_per_serving' => 20,
                'instructions' => 'Cook corned beef, garlic rice, and egg',
                'is_filipino_dish' => true,
                'ingredients' => ['corned beef', 'garlic rice', 'egg', 'garlic', 'soy sauce'],
            ],
            // Additional Filipino Soups
            [
                'name' => 'Bulalo',
                'description' => 'Filipino beef shank soup',
                'prep_time' => 20,
                'cook_time' => 120,
                'servings' => 6,
                'difficulty' => 'Medium',
                'category' => 'Soup',
                'calories_per_serving' => 280,
                'protein_per_serving' => 32,
                'carbs_per_serving' => 8,
                'fat_per_serving' => 12,
                'instructions' => 'Simmer beef shank with vegetables until tender',
                'is_filipino_dish' => true,
                'ingredients' => ['beef shank', 'corn', 'cabbage', 'onion', 'garlic', 'ginger'],
            ],
            [
                'name' => 'Nilaga',
                'description' => 'Filipino boiled meat and vegetables',
                'prep_time' => 15,
                'cook_time' => 60,
                'servings' => 6,
                'difficulty' => 'Easy',
                'category' => 'Soup',
                'calories_per_serving' => 220,
                'protein_per_serving' => 25,
                'carbs_per_serving' => 12,
                'fat_per_serving' => 8,
                'instructions' => 'Boil meat with vegetables until tender',
                'is_filipino_dish' => true,
                'ingredients' => ['beef', 'potato', 'carrot', 'cabbage', 'onion', 'garlic'],
            ],
            [
                'name' => 'Paksiw na Isda',
                'description' => 'Filipino fish in vinegar',
                'prep_time' => 10,
                'cook_time' => 20,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Filipino',
                'calories_per_serving' => 160,
                'protein_per_serving' => 20,
                'carbs_per_serving' => 4,
                'fat_per_serving' => 6,
                'instructions' => 'Cook fish in vinegar with vegetables',
                'is_filipino_dish' => true,
                'ingredients' => ['fish', 'vinegar', 'onion', 'garlic', 'ginger', 'chili'],
            ],
            [
                'name' => 'Paksiw na Lechon',
                'description' => 'Filipino lechon in vinegar',
                'prep_time' => 10,
                'cook_time' => 20,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Filipino',
                'calories_per_serving' => 320,
                'protein_per_serving' => 28,
                'carbs_per_serving' => 6,
                'fat_per_serving' => 20,
                'instructions' => 'Cook lechon in vinegar with vegetables',
                'is_filipino_dish' => true,
                'ingredients' => ['lechon', 'vinegar', 'onion', 'garlic', 'ginger', 'chili'],
            ],
            [
                'name' => 'Paksiw na Bangus',
                'description' => 'Filipino bangus in vinegar',
                'prep_time' => 10,
                'cook_time' => 20,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Filipino',
                'calories_per_serving' => 180,
                'protein_per_serving' => 22,
                'carbs_per_serving' => 4,
                'fat_per_serving' => 8,
                'instructions' => 'Cook bangus in vinegar with vegetables',
                'is_filipino_dish' => true,
                'ingredients' => ['bangus', 'vinegar', 'onion', 'garlic', 'ginger', 'chili'],
            ],
            // Additional Filipino Desserts
            [
                'name' => 'Sapin-Sapin',
                'description' => 'Filipino layered rice cake',
                'prep_time' => 30,
                'cook_time' => 45,
                'servings' => 8,
                'difficulty' => 'Hard',
                'category' => 'Dessert',
                'calories_per_serving' => 220,
                'protein_per_serving' => 4,
                'carbs_per_serving' => 38,
                'fat_per_serving' => 6,
                'instructions' => 'Layer different colored rice mixtures',
                'is_filipino_dish' => true,
                'ingredients' => ['malagkit na bigas', 'coconut milk', 'sugar', 'ube', 'banana leaves'],
            ],
            [
                'name' => 'Maja Blanca',
                'description' => 'Filipino coconut pudding',
                'prep_time' => 15,
                'cook_time' => 20,
                'servings' => 8,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 160,
                'protein_per_serving' => 3,
                'carbs_per_serving' => 28,
                'fat_per_serving' => 4,
                'instructions' => 'Cook coconut milk with cornstarch until thick',
                'is_filipino_dish' => true,
                'ingredients' => ['coconut milk', 'cornstarch', 'sugar', 'corn', 'condensed milk'],
            ],
            [
                'name' => 'Macapuno',
                'description' => 'Filipino coconut sport',
                'prep_time' => 20,
                'cook_time' => 30,
                'servings' => 6,
                'difficulty' => 'Medium',
                'category' => 'Dessert',
                'calories_per_serving' => 140,
                'protein_per_serving' => 2,
                'carbs_per_serving' => 24,
                'fat_per_serving' => 4,
                'instructions' => 'Cook macapuno in syrup until tender',
                'is_filipino_dish' => true,
                'ingredients' => ['macapuno', 'syrup', 'sugar', 'coconut milk'],
            ],
            [
                'name' => 'Buko Pie',
                'description' => 'Filipino coconut pie',
                'prep_time' => 30,
                'cook_time' => 45,
                'servings' => 8,
                'difficulty' => 'Medium',
                'category' => 'Dessert',
                'calories_per_serving' => 280,
                'protein_per_serving' => 6,
                'carbs_per_serving' => 35,
                'fat_per_serving' => 12,
                'instructions' => 'Make pie crust, fill with coconut mixture, bake',
                'is_filipino_dish' => true,
                'ingredients' => ['coconut', 'flour', 'butter', 'sugar', 'milk', 'egg'],
            ],
            [
                'name' => 'Ensaymada',
                'description' => 'Filipino sweet bread',
                'prep_time' => 45,
                'cook_time' => 25,
                'servings' => 8,
                'difficulty' => 'Medium',
                'category' => 'Dessert',
                'calories_per_serving' => 320,
                'protein_per_serving' => 8,
                'carbs_per_serving' => 42,
                'fat_per_serving' => 14,
                'instructions' => 'Make sweet bread dough, shape, and bake',
                'is_filipino_dish' => true,
                'ingredients' => ['flour', 'yeast', 'sugar', 'butter', 'egg', 'milk'],
            ],
            [
                'name' => 'Pan de Sal',
                'description' => 'Filipino bread rolls',
                'prep_time' => 30,
                'cook_time' => 20,
                'servings' => 12,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 120,
                'protein_per_serving' => 4,
                'carbs_per_serving' => 20,
                'fat_per_serving' => 2,
                'instructions' => 'Make bread dough, shape into rolls, bake',
                'is_filipino_dish' => true,
                'ingredients' => ['flour', 'yeast', 'sugar', 'salt', 'water', 'oil'],
            ],
            [
                'name' => 'Pandesal',
                'description' => 'Filipino bread rolls with salt',
                'prep_time' => 30,
                'cook_time' => 20,
                'servings' => 12,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 110,
                'protein_per_serving' => 4,
                'carbs_per_serving' => 18,
                'fat_per_serving' => 2,
                'instructions' => 'Make bread dough with salt, shape into rolls, bake',
                'is_filipino_dish' => true,
                'ingredients' => ['flour', 'yeast', 'sugar', 'salt', 'water', 'oil'],
            ],
            [
                'name' => 'Monay',
                'description' => 'Filipino bread',
                'prep_time' => 30,
                'cook_time' => 25,
                'servings' => 8,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 140,
                'protein_per_serving' => 5,
                'carbs_per_serving' => 22,
                'fat_per_serving' => 3,
                'instructions' => 'Make bread dough, shape, and bake',
                'is_filipino_dish' => true,
                'ingredients' => ['flour', 'yeast', 'sugar', 'salt', 'water', 'oil'],
            ],
            [
                'name' => 'Spanish Bread',
                'description' => 'Filipino sweet bread',
                'prep_time' => 30,
                'cook_time' => 25,
                'servings' => 8,
                'difficulty' => 'Medium',
                'category' => 'Dessert',
                'calories_per_serving' => 180,
                'protein_per_serving' => 5,
                'carbs_per_serving' => 28,
                'fat_per_serving' => 5,
                'instructions' => 'Make sweet bread dough, fill with sweet filling, bake',
                'is_filipino_dish' => true,
                'ingredients' => ['flour', 'yeast', 'sugar', 'butter', 'egg', 'milk'],
            ],
            [
                'name' => 'Hopia',
                'description' => 'Filipino pastry',
                'prep_time' => 45,
                'cook_time' => 30,
                'servings' => 12,
                'difficulty' => 'Hard',
                'category' => 'Dessert',
                'calories_per_serving' => 200,
                'protein_per_serving' => 4,
                'carbs_per_serving' => 28,
                'fat_per_serving' => 8,
                'instructions' => 'Make pastry dough, fill with sweet filling, bake',
                'is_filipino_dish' => true,
                'ingredients' => ['flour', 'butter', 'sugar', 'egg', 'milk', 'filling'],
            ],
            [
                'name' => 'Hopiang Baboy',
                'description' => 'Filipino pork pastry',
                'prep_time' => 45,
                'cook_time' => 30,
                'servings' => 12,
                'difficulty' => 'Hard',
                'category' => 'Dessert',
                'calories_per_serving' => 220,
                'protein_per_serving' => 8,
                'carbs_per_serving' => 26,
                'fat_per_serving' => 10,
                'instructions' => 'Make pastry dough, fill with pork mixture, bake',
                'is_filipino_dish' => true,
                'ingredients' => ['flour', 'butter', 'pork', 'onion', 'garlic', 'seasonings'],
            ],
            [
                'name' => 'Empanada',
                'description' => 'Filipino meat pie',
                'prep_time' => 30,
                'cook_time' => 25,
                'servings' => 8,
                'difficulty' => 'Medium',
                'category' => 'Dessert',
                'calories_per_serving' => 180,
                'protein_per_serving' => 10,
                'carbs_per_serving' => 22,
                'fat_per_serving' => 6,
                'instructions' => 'Make pastry dough, fill with meat mixture, bake',
                'is_filipino_dish' => true,
                'ingredients' => ['flour', 'butter', 'meat', 'vegetables', 'onion', 'garlic'],
            ],
            [
                'name' => 'Siopao',
                'description' => 'Filipino steamed bun',
                'prep_time' => 40,
                'cook_time' => 20,
                'servings' => 8,
                'difficulty' => 'Medium',
                'category' => 'Dessert',
                'calories_per_serving' => 160,
                'protein_per_serving' => 8,
                'carbs_per_serving' => 24,
                'fat_per_serving' => 4,
                'instructions' => 'Make bun dough, fill with meat mixture, steam',
                'is_filipino_dish' => true,
                'ingredients' => ['flour', 'yeast', 'meat', 'vegetables', 'onion', 'garlic'],
            ],
            [
                'name' => 'Siomai',
                'description' => 'Filipino dumpling',
                'prep_time' => 30,
                'cook_time' => 15,
                'servings' => 8,
                'difficulty' => 'Medium',
                'category' => 'Dessert',
                'calories_per_serving' => 120,
                'protein_per_serving' => 8,
                'carbs_per_serving' => 16,
                'fat_per_serving' => 3,
                'instructions' => 'Make dumpling wrapper, fill with meat mixture, steam',
                'is_filipino_dish' => true,
                'ingredients' => ['dumpling wrapper', 'meat', 'vegetables', 'onion', 'garlic', 'seasonings'],
            ],
            [
                'name' => 'Lumpia',
                'description' => 'Filipino spring roll',
                'prep_time' => 25,
                'cook_time' => 15,
                'servings' => 8,
                'difficulty' => 'Medium',
                'category' => 'Dessert',
                'calories_per_serving' => 100,
                'protein_per_serving' => 6,
                'carbs_per_serving' => 12,
                'fat_per_serving' => 3,
                'instructions' => 'Wrap meat mixture in spring roll wrapper, fry',
                'is_filipino_dish' => true,
                'ingredients' => ['spring roll wrapper', 'meat', 'vegetables', 'onion', 'garlic', 'seasonings'],
            ],
            [
                'name' => 'Lumpiang Gulay',
                'description' => 'Filipino vegetable spring roll',
                'prep_time' => 20,
                'cook_time' => 15,
                'servings' => 8,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 80,
                'protein_per_serving' => 4,
                'carbs_per_serving' => 10,
                'fat_per_serving' => 2,
                'instructions' => 'Wrap vegetable mixture in spring roll wrapper, fry',
                'is_filipino_dish' => true,
                'ingredients' => ['spring roll wrapper', 'vegetables', 'onion', 'garlic', 'seasonings'],
            ],
            [
                'name' => 'Lumpiang Sariwa',
                'description' => 'Filipino fresh spring roll',
                'prep_time' => 25,
                'cook_time' => 15,
                'servings' => 8,
                'difficulty' => 'Medium',
                'category' => 'Dessert',
                'calories_per_serving' => 90,
                'protein_per_serving' => 5,
                'carbs_per_serving' => 12,
                'fat_per_serving' => 2,
                'instructions' => 'Wrap fresh vegetables in spring roll wrapper, serve with sauce',
                'is_filipino_dish' => true,
                'ingredients' => ['spring roll wrapper', 'fresh vegetables', 'onion', 'garlic', 'sauce'],
            ],
            [
                'name' => 'Lumpiang Ampalaya',
                'description' => 'Filipino bitter gourd spring roll',
                'prep_time' => 20,
                'cook_time' => 12,
                'servings' => 8,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 80,
                'protein_per_serving' => 3,
                'carbs_per_serving' => 8,
                'fat_per_serving' => 2,
                'instructions' => 'Wrap bitter gourd mixture in spring roll wrapper, fry until golden',
                'is_filipino_dish' => true,
                'ingredients' => ['spring roll wrapper', 'bitter gourd', 'onion', 'garlic', 'oil'],
            ],
        ];

        foreach ($recipes as $recipeData) {
            $ingredients = $recipeData['ingredients'];
            unset($recipeData['ingredients']);

            $recipe = Recipe::firstOrCreate(
                ['name' => $recipeData['name']],
                $recipeData
            );

            foreach ($ingredients as $ingredientName) {
                $ingredient = Ingredient::where('name', $ingredientName)->first();
                if ($ingredient && !$recipe->ingredients()->where('ingredient_id', $ingredient->id)->exists()) {
                    $recipe->ingredients()->attach($ingredient->id, [
                        'quantity' => '1',
                        'unit' => 'piece'
                    ]);
                }
            }
        }
    }
}
