<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Recipe;
use App\Models\Ingredient;

class HealthyFilipinoFoodsSeeder extends Seeder
{
    public function run(): void
    {
        // Create additional healthy ingredients first
        $this->createHealthyIngredients();
        
        // Create 50 additional healthy Filipino recipes
        $this->createHealthyRecipes();
    }

    private function createHealthyIngredients(): void
    {
        $ingredients = [
            // Healthy Proteins
            ['name' => 'salmon', 'category' => 'Protein', 'description' => 'Fresh salmon'],
            ['name' => 'tuna', 'category' => 'Protein', 'description' => 'Fresh tuna'],
            ['name' => 'mackerel', 'category' => 'Protein', 'description' => 'Fresh mackerel'],
            ['name' => 'sardines', 'category' => 'Protein', 'description' => 'Fresh sardines'],
            ['name' => 'chicken breast', 'category' => 'Protein', 'description' => 'Skinless chicken breast'],
            ['name' => 'lean pork', 'category' => 'Protein', 'description' => 'Lean pork cuts'],
            ['name' => 'tofu', 'category' => 'Protein', 'description' => 'Firm tofu'],
            ['name' => 'tempeh', 'category' => 'Protein', 'description' => 'Tempeh'],
            ['name' => 'quail eggs', 'category' => 'Protein', 'description' => 'Quail eggs'],
            ['name' => 'duck eggs', 'category' => 'Protein', 'description' => 'Duck eggs'],
            
            // Healthy Grains & Starches
            ['name' => 'quinoa', 'category' => 'Grain', 'description' => 'Quinoa'],
            ['name' => 'oats', 'category' => 'Grain', 'description' => 'Rolled oats'],
            ['name' => 'barley', 'category' => 'Grain', 'description' => 'Pearl barley'],
            ['name' => 'buckwheat', 'category' => 'Grain', 'description' => 'Buckwheat'],
            ['name' => 'wild rice', 'category' => 'Grain', 'description' => 'Wild rice'],
            ['name' => 'red rice', 'category' => 'Grain', 'description' => 'Red rice'],
            ['name' => 'black rice', 'category' => 'Grain', 'description' => 'Black rice'],
            ['name' => 'sweet potato leaves', 'category' => 'Vegetable', 'description' => 'Sweet potato leaves (talbos)'],
            ['name' => 'malunggay', 'category' => 'Vegetable', 'description' => 'Moringa leaves'],
            ['name' => 'kangkong', 'category' => 'Vegetable', 'description' => 'Water spinach'],
            
            // Healthy Vegetables
            ['name' => 'okra', 'category' => 'Vegetable', 'description' => 'Okra'],
            ['name' => 'ampalaya', 'category' => 'Vegetable', 'description' => 'Bitter gourd'],
            ['name' => 'sitaw', 'category' => 'Vegetable', 'description' => 'String beans'],
            ['name' => 'patola', 'category' => 'Vegetable', 'description' => 'Sponge gourd'],
            ['name' => 'upo', 'category' => 'Vegetable', 'description' => 'Bottle gourd'],
            ['name' => 'kalabasa', 'category' => 'Vegetable', 'description' => 'Squash'],
            ['name' => 'gabi', 'category' => 'Vegetable', 'description' => 'Taro root'],
            ['name' => 'camote tops', 'category' => 'Vegetable', 'description' => 'Sweet potato tops'],
            ['name' => 'alugbati', 'category' => 'Vegetable', 'description' => 'Basella'],
            ['name' => 'pechay', 'category' => 'Vegetable', 'description' => 'Chinese cabbage'],
            
            // Healthy Fruits
            ['name' => 'guyabano', 'category' => 'Fruit', 'description' => 'Soursop'],
            ['name' => 'lansones', 'category' => 'Fruit', 'description' => 'Lansones'],
            ['name' => 'rambutan', 'category' => 'Fruit', 'description' => 'Rambutan'],
            ['name' => 'duhat', 'category' => 'Fruit', 'description' => 'Java plum'],
            ['name' => 'santol', 'category' => 'Fruit', 'description' => 'Santol'],
            ['name' => 'atis', 'category' => 'Fruit', 'description' => 'Sugar apple'],
            ['name' => 'chico', 'category' => 'Fruit', 'description' => 'Sapodilla'],
            ['name' => 'papaya', 'category' => 'Fruit', 'description' => 'Papaya'],
            ['name' => 'pineapple', 'category' => 'Fruit', 'description' => 'Pineapple'],
            ['name' => 'coconut', 'category' => 'Fruit', 'description' => 'Fresh coconut'],
            
            // Healthy Nuts & Seeds
            ['name' => 'cashew nuts', 'category' => 'Nut', 'description' => 'Cashew nuts'],
            ['name' => 'almonds', 'category' => 'Nut', 'description' => 'Almonds'],
            ['name' => 'walnuts', 'category' => 'Nut', 'description' => 'Walnuts'],
            ['name' => 'chia seeds', 'category' => 'Seed', 'description' => 'Chia seeds'],
            ['name' => 'flax seeds', 'category' => 'Seed', 'description' => 'Flax seeds'],
            ['name' => 'sesame seeds', 'category' => 'Seed', 'description' => 'Sesame seeds'],
            ['name' => 'sunflower seeds', 'category' => 'Seed', 'description' => 'Sunflower seeds'],
            
            // Healthy Condiments
            ['name' => 'coconut oil', 'category' => 'Fat', 'description' => 'Virgin coconut oil'],
            ['name' => 'avocado oil', 'category' => 'Fat', 'description' => 'Avocado oil'],
            ['name' => 'sesame oil', 'category' => 'Fat', 'description' => 'Sesame oil'],
            ['name' => 'coconut vinegar', 'category' => 'Condiment', 'description' => 'Coconut vinegar'],
            ['name' => 'cane vinegar', 'category' => 'Condiment', 'description' => 'Cane vinegar'],
            ['name' => 'calamansi', 'category' => 'Fruit', 'description' => 'Calamansi lime'],
            ['name' => 'lemongrass', 'category' => 'Herb', 'description' => 'Lemongrass'],
            ['name' => 'pandan', 'category' => 'Herb', 'description' => 'Pandan leaves'],
            ['name' => 'turmeric', 'category' => 'Spice', 'description' => 'Turmeric root'],
            ['name' => 'ginger', 'category' => 'Spice', 'description' => 'Fresh ginger'],
        ];

        foreach ($ingredients as $ingredient) {
            Ingredient::firstOrCreate(
                ['name' => $ingredient['name']],
                $ingredient
            );
        }
    }

    private function createHealthyRecipes(): void
    {
        $recipes = [
            // Healthy Breakfast Options
            [
                'name' => 'Oatmeal with Malunggay and Banana',
                'description' => 'Nutritious oatmeal with moringa leaves and banana',
                'prep_time' => 5,
                'cook_time' => 10,
                'servings' => 2,
                'difficulty' => 'Easy',
                'category' => 'Healthy',
                'calories_per_serving' => 280,
                'protein_per_serving' => 12,
                'carbs_per_serving' => 45,
                'fat_per_serving' => 6,
                'instructions' => 'Cook oats with water, add malunggay leaves and sliced banana',
                'is_filipino_dish' => true,
                'ingredients' => ['oats', 'malunggay', 'banana', 'coconut milk', 'honey'],
            ],
            [
                'name' => 'Quinoa Champorado',
                'description' => 'Healthy chocolate quinoa porridge',
                'prep_time' => 5,
                'cook_time' => 15,
                'servings' => 2,
                'difficulty' => 'Easy',
                'category' => 'Healthy',
                'calories_per_serving' => 320,
                'protein_per_serving' => 8,
                'carbs_per_serving' => 55,
                'fat_per_serving' => 7,
                'instructions' => 'Cook quinoa with cocoa powder and coconut milk',
                'is_filipino_dish' => true,
                'ingredients' => ['quinoa', 'cocoa powder', 'coconut milk', 'honey', 'cinnamon'],
            ],
            [
                'name' => 'Tofu Scramble with Vegetables',
                'description' => 'Scrambled tofu with mixed vegetables',
                'prep_time' => 10,
                'cook_time' => 15,
                'servings' => 2,
                'difficulty' => 'Easy',
                'category' => 'Healthy',
                'calories_per_serving' => 180,
                'protein_per_serving' => 15,
                'carbs_per_serving' => 12,
                'fat_per_serving' => 8,
                'instructions' => 'Scramble tofu with vegetables and spices',
                'is_filipino_dish' => true,
                'ingredients' => ['tofu', 'mixed vegetables', 'garlic', 'onion', 'turmeric'],
            ],
            [
                'name' => 'Sweet Potato Hash',
                'description' => 'Roasted sweet potato with vegetables',
                'prep_time' => 10,
                'cook_time' => 25,
                'servings' => 3,
                'difficulty' => 'Easy',
                'category' => 'Healthy',
                'calories_per_serving' => 220,
                'protein_per_serving' => 6,
                'carbs_per_serving' => 42,
                'fat_per_serving' => 4,
                'instructions' => 'Roast diced sweet potato with vegetables and herbs',
                'is_filipino_dish' => true,
                'ingredients' => ['sweet potato', 'bell peppers', 'onion', 'garlic', 'olive oil'],
            ],
            [
                'name' => 'Green Smoothie Bowl',
                'description' => 'Nutritious smoothie bowl with Filipino fruits',
                'prep_time' => 10,
                'cook_time' => 0,
                'servings' => 1,
                'difficulty' => 'Easy',
                'category' => 'Healthy',
                'calories_per_serving' => 250,
                'protein_per_serving' => 8,
                'carbs_per_serving' => 45,
                'fat_per_serving' => 6,
                'instructions' => 'Blend spinach, mango, banana, and coconut milk',
                'is_filipino_dish' => true,
                'ingredients' => ['spinach', 'mango', 'banana', 'coconut milk', 'chia seeds'],
            ],

            // Healthy Soups & Stews
            [
                'name' => 'Ginataang Kalabasa',
                'description' => 'Squash in coconut milk with vegetables',
                'prep_time' => 15,
                'cook_time' => 20,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Healthy',
                'calories_per_serving' => 180,
                'protein_per_serving' => 6,
                'carbs_per_serving' => 25,
                'fat_per_serving' => 8,
                'instructions' => 'Cook squash in coconut milk with vegetables',
                'is_filipino_dish' => true,
                'ingredients' => ['kalabasa', 'coconut milk', 'sitaw', 'malunggay', 'garlic'],
            ],
            [
                'name' => 'Tinolang Isda',
                'description' => 'Healthy fish soup with ginger and vegetables',
                'prep_time' => 15,
                'cook_time' => 20,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Healthy',
                'calories_per_serving' => 200,
                'protein_per_serving' => 25,
                'carbs_per_serving' => 15,
                'fat_per_serving' => 5,
                'instructions' => 'Boil fish with ginger, add vegetables and season',
                'is_filipino_dish' => true,
                'ingredients' => ['fish', 'ginger', 'malunggay', 'sitaw', 'onion'],
            ],
            [
                'name' => 'Ginisang Monggo with Malunggay',
                'description' => 'Mung beans with moringa leaves',
                'prep_time' => 10,
                'cook_time' => 30,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Healthy',
                'calories_per_serving' => 160,
                'protein_per_serving' => 12,
                'carbs_per_serving' => 22,
                'fat_per_serving' => 3,
                'instructions' => 'Cook mung beans, sauté with vegetables and malunggay',
                'is_filipino_dish' => true,
                'ingredients' => ['mung beans', 'malunggay', 'garlic', 'onion', 'tomato'],
            ],
            [
                'name' => 'Sinigang na Hipon',
                'description' => 'Sour soup with shrimp and vegetables',
                'prep_time' => 15,
                'cook_time' => 25,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Healthy',
                'calories_per_serving' => 150,
                'protein_per_serving' => 18,
                'carbs_per_serving' => 12,
                'fat_per_serving' => 4,
                'instructions' => 'Boil shrimp with tamarind and vegetables',
                'is_filipino_dish' => true,
                'ingredients' => ['shrimp', 'tamarind', 'sitaw', 'okra', 'malunggay'],
            ],
            [
                'name' => 'Nilagang Baka with Vegetables',
                'description' => 'Boiled beef with mixed vegetables',
                'prep_time' => 20,
                'cook_time' => 60,
                'servings' => 6,
                'difficulty' => 'Medium',
                'category' => 'Healthy',
                'calories_per_serving' => 280,
                'protein_per_serving' => 30,
                'carbs_per_serving' => 20,
                'fat_per_serving' => 8,
                'instructions' => 'Boil beef until tender, add vegetables',
                'is_filipino_dish' => true,
                'ingredients' => ['lean beef', 'potatoes', 'carrots', 'sitaw', 'malunggay'],
            ],

            // Healthy Main Dishes
            [
                'name' => 'Grilled Salmon with Atchara',
                'description' => 'Grilled salmon with pickled vegetables',
                'prep_time' => 15,
                'cook_time' => 15,
                'servings' => 2,
                'difficulty' => 'Easy',
                'category' => 'Healthy',
                'calories_per_serving' => 320,
                'protein_per_serving' => 35,
                'carbs_per_serving' => 8,
                'fat_per_serving' => 16,
                'instructions' => 'Grill salmon, serve with atchara',
                'is_filipino_dish' => true,
                'ingredients' => ['salmon', 'atchara', 'lemon', 'garlic', 'olive oil'],
            ],
            [
                'name' => 'Chicken Breast Adobo',
                'description' => 'Healthy chicken breast adobo',
                'prep_time' => 15,
                'cook_time' => 25,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Healthy',
                'calories_per_serving' => 220,
                'protein_per_serving' => 35,
                'carbs_per_serving' => 8,
                'fat_per_serving' => 6,
                'instructions' => 'Marinate chicken breast, cook in soy sauce and vinegar',
                'is_filipino_dish' => true,
                'ingredients' => ['chicken breast', 'soy sauce', 'vinegar', 'garlic', 'bay leaves'],
            ],
            [
                'name' => 'Tofu Sisig',
                'description' => 'Healthy tofu sisig',
                'prep_time' => 20,
                'cook_time' => 15,
                'servings' => 4,
                'difficulty' => 'Medium',
                'category' => 'Healthy',
                'calories_per_serving' => 180,
                'protein_per_serving' => 15,
                'carbs_per_serving' => 8,
                'fat_per_serving' => 10,
                'instructions' => 'Sauté tofu with vegetables and spices',
                'is_filipino_dish' => true,
                'ingredients' => ['tofu', 'onion', 'garlic', 'chili', 'calamansi'],
            ],
            [
                'name' => 'Baked Bangus with Herbs',
                'description' => 'Baked milkfish with fresh herbs',
                'prep_time' => 15,
                'cook_time' => 25,
                'servings' => 2,
                'difficulty' => 'Easy',
                'category' => 'Healthy',
                'calories_per_serving' => 250,
                'protein_per_serving' => 30,
                'carbs_per_serving' => 5,
                'fat_per_serving' => 12,
                'instructions' => 'Bake bangus with herbs and lemon',
                'is_filipino_dish' => true,
                'ingredients' => ['bangus', 'lemongrass', 'ginger', 'garlic', 'lemon'],
            ],
            [
                'name' => 'Vegetable Kare-Kare',
                'description' => 'Vegetarian kare-kare with peanut sauce',
                'prep_time' => 20,
                'cook_time' => 30,
                'servings' => 6,
                'difficulty' => 'Medium',
                'category' => 'Healthy',
                'calories_per_serving' => 200,
                'protein_per_serving' => 8,
                'carbs_per_serving' => 25,
                'fat_per_serving' => 10,
                'instructions' => 'Cook vegetables in peanut sauce',
                'is_filipino_dish' => true,
                'ingredients' => ['sitaw', 'okra', 'eggplant', 'peanut butter', 'bagoong'],
            ],

            // Healthy Vegetable Dishes
            [
                'name' => 'Ampalaya with Egg',
                'description' => 'Bitter gourd with scrambled egg',
                'prep_time' => 15,
                'cook_time' => 15,
                'servings' => 3,
                'difficulty' => 'Easy',
                'category' => 'Healthy',
                'calories_per_serving' => 120,
                'protein_per_serving' => 8,
                'carbs_per_serving' => 8,
                'fat_per_serving' => 6,
                'instructions' => 'Sauté ampalaya with scrambled egg',
                'is_filipino_dish' => true,
                'ingredients' => ['ampalaya', 'egg', 'garlic', 'onion', 'soy sauce'],
            ],
            [
                'name' => 'Ginataang Sitaw at Kalabasa',
                'description' => 'String beans and squash in coconut milk',
                'prep_time' => 10,
                'cook_time' => 20,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Healthy',
                'calories_per_serving' => 150,
                'protein_per_serving' => 4,
                'carbs_per_serving' => 20,
                'fat_per_serving' => 8,
                'instructions' => 'Cook vegetables in coconut milk',
                'is_filipino_dish' => true,
                'ingredients' => ['sitaw', 'kalabasa', 'coconut milk', 'garlic', 'onion'],
            ],
            [
                'name' => 'Kangkong with Garlic',
                'description' => 'Water spinach with garlic',
                'prep_time' => 5,
                'cook_time' => 10,
                'servings' => 3,
                'difficulty' => 'Easy',
                'category' => 'Healthy',
                'calories_per_serving' => 60,
                'protein_per_serving' => 4,
                'carbs_per_serving' => 8,
                'fat_per_serving' => 2,
                'instructions' => 'Sauté kangkong with garlic',
                'is_filipino_dish' => true,
                'ingredients' => ['kangkong', 'garlic', 'soy sauce', 'sesame oil'],
            ],
            [
                'name' => 'Ginisang Pechay',
                'description' => 'Sautéed Chinese cabbage',
                'prep_time' => 5,
                'cook_time' => 10,
                'servings' => 3,
                'difficulty' => 'Easy',
                'category' => 'Healthy',
                'calories_per_serving' => 50,
                'protein_per_serving' => 3,
                'carbs_per_serving' => 6,
                'fat_per_serving' => 2,
                'instructions' => 'Sauté pechay with garlic and onion',
                'is_filipino_dish' => true,
                'ingredients' => ['pechay', 'garlic', 'onion', 'soy sauce'],
            ],
            [
                'name' => 'Malunggay with Gata',
                'description' => 'Moringa leaves in coconut milk',
                'prep_time' => 5,
                'cook_time' => 15,
                'servings' => 3,
                'difficulty' => 'Easy',
                'category' => 'Healthy',
                'calories_per_serving' => 80,
                'protein_per_serving' => 4,
                'carbs_per_serving' => 6,
                'fat_per_serving' => 5,
                'instructions' => 'Cook malunggay in coconut milk',
                'is_filipino_dish' => true,
                'ingredients' => ['malunggay', 'coconut milk', 'garlic', 'onion'],
            ],

            // Healthy Snacks & Desserts
            [
                'name' => 'Buko Pandan Salad',
                'description' => 'Young coconut with pandan jelly',
                'prep_time' => 20,
                'cook_time' => 15,
                'servings' => 6,
                'difficulty' => 'Easy',
                'category' => 'Healthy',
                'calories_per_serving' => 120,
                'protein_per_serving' => 2,
                'carbs_per_serving' => 25,
                'fat_per_serving' => 2,
                'instructions' => 'Mix young coconut with pandan jelly and condensed milk',
                'is_filipino_dish' => true,
                'ingredients' => ['young coconut', 'pandan jelly', 'condensed milk', 'cream'],
            ],
            [
                'name' => 'Turon with Banana and Jackfruit',
                'description' => 'Healthy banana and jackfruit spring roll',
                'prep_time' => 15,
                'cook_time' => 20,
                'servings' => 6,
                'difficulty' => 'Easy',
                'category' => 'Healthy',
                'calories_per_serving' => 180,
                'protein_per_serving' => 3,
                'carbs_per_serving' => 35,
                'fat_per_serving' => 5,
                'instructions' => 'Wrap banana and jackfruit in spring roll wrapper, bake',
                'is_filipino_dish' => true,
                'ingredients' => ['banana', 'jackfruit', 'spring roll wrapper', 'brown sugar'],
            ],
            [
                'name' => 'Ginataang Bilo-Bilo',
                'description' => 'Sweet rice balls in coconut milk',
                'prep_time' => 20,
                'cook_time' => 25,
                'servings' => 6,
                'difficulty' => 'Medium',
                'category' => 'Healthy',
                'calories_per_serving' => 200,
                'protein_per_serving' => 4,
                'carbs_per_serving' => 35,
                'fat_per_serving' => 6,
                'instructions' => 'Make rice balls, cook in coconut milk with fruits',
                'is_filipino_dish' => true,
                'ingredients' => ['glutinous rice', 'coconut milk', 'sweet potato', 'banana', 'jackfruit'],
            ],
            [
                'name' => 'Fresh Fruit Salad',
                'description' => 'Mixed Filipino fruits with yogurt',
                'prep_time' => 15,
                'cook_time' => 0,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Healthy',
                'calories_per_serving' => 150,
                'protein_per_serving' => 6,
                'carbs_per_serving' => 30,
                'fat_per_serving' => 2,
                'instructions' => 'Mix fresh fruits with Greek yogurt',
                'is_filipino_dish' => true,
                'ingredients' => ['mango', 'papaya', 'pineapple', 'banana', 'greek yogurt'],
            ],
            [
                'name' => 'Chia Pudding with Mango',
                'description' => 'Chia seed pudding with fresh mango',
                'prep_time' => 10,
                'cook_time' => 0,
                'servings' => 2,
                'difficulty' => 'Easy',
                'category' => 'Healthy',
                'calories_per_serving' => 200,
                'protein_per_serving' => 8,
                'carbs_per_serving' => 25,
                'fat_per_serving' => 8,
                'instructions' => 'Soak chia seeds in coconut milk, top with mango',
                'is_filipino_dish' => true,
                'ingredients' => ['chia seeds', 'coconut milk', 'mango', 'honey'],
            ],

            // Healthy Rice Alternatives
            [
                'name' => 'Cauliflower Rice',
                'description' => 'Grated cauliflower as rice substitute',
                'prep_time' => 10,
                'cook_time' => 10,
                'servings' => 3,
                'difficulty' => 'Easy',
                'category' => 'Healthy',
                'calories_per_serving' => 50,
                'protein_per_serving' => 3,
                'carbs_per_serving' => 8,
                'fat_per_serving' => 2,
                'instructions' => 'Grate cauliflower, sauté with garlic and oil',
                'is_filipino_dish' => true,
                'ingredients' => ['cauliflower', 'garlic', 'onion', 'olive oil'],
            ],
            [
                'name' => 'Quinoa Fried Rice',
                'description' => 'Fried quinoa with vegetables',
                'prep_time' => 10,
                'cook_time' => 15,
                'servings' => 3,
                'difficulty' => 'Easy',
                'category' => 'Healthy',
                'calories_per_serving' => 220,
                'protein_per_serving' => 8,
                'carbs_per_serving' => 35,
                'fat_per_serving' => 6,
                'instructions' => 'Cook quinoa, stir-fry with vegetables and soy sauce',
                'is_filipino_dish' => true,
                'ingredients' => ['quinoa', 'mixed vegetables', 'garlic', 'soy sauce', 'sesame oil'],
            ],
            [
                'name' => 'Brown Rice Congee',
                'description' => 'Healthy brown rice porridge',
                'prep_time' => 5,
                'cook_time' => 30,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Healthy',
                'calories_per_serving' => 180,
                'protein_per_serving' => 6,
                'carbs_per_serving' => 35,
                'fat_per_serving' => 3,
                'instructions' => 'Cook brown rice in chicken broth until soft',
                'is_filipino_dish' => true,
                'ingredients' => ['brown rice', 'chicken broth', 'ginger', 'garlic', 'spring onion'],
            ],

            // Healthy Drinks
            [
                'name' => 'Malunggay Smoothie',
                'description' => 'Nutritious moringa smoothie',
                'prep_time' => 10,
                'cook_time' => 0,
                'servings' => 2,
                'difficulty' => 'Easy',
                'category' => 'Healthy',
                'calories_per_serving' => 120,
                'protein_per_serving' => 6,
                'carbs_per_serving' => 20,
                'fat_per_serving' => 3,
                'instructions' => 'Blend malunggay leaves with fruits and coconut water',
                'is_filipino_dish' => true,
                'ingredients' => ['malunggay', 'banana', 'mango', 'coconut water', 'honey'],
            ],
            [
                'name' => 'Ginger Turmeric Tea',
                'description' => 'Anti-inflammatory ginger turmeric tea',
                'prep_time' => 5,
                'cook_time' => 10,
                'servings' => 2,
                'difficulty' => 'Easy',
                'category' => 'Healthy',
                'calories_per_serving' => 20,
                'protein_per_serving' => 1,
                'carbs_per_serving' => 4,
                'fat_per_serving' => 0,
                'instructions' => 'Boil ginger and turmeric, add honey and lemon',
                'is_filipino_dish' => true,
                'ingredients' => ['ginger', 'turmeric', 'honey', 'lemon', 'water'],
            ],
            [
                'name' => 'Calamansi Detox Drink',
                'description' => 'Refreshing calamansi detox drink',
                'prep_time' => 5,
                'cook_time' => 0,
                'servings' => 2,
                'difficulty' => 'Easy',
                'category' => 'Healthy',
                'calories_per_serving' => 30,
                'protein_per_serving' => 1,
                'carbs_per_serving' => 8,
                'fat_per_serving' => 0,
                'instructions' => 'Mix calamansi juice with water and honey',
                'is_filipino_dish' => true,
                'ingredients' => ['calamansi', 'honey', 'water', 'mint leaves'],
            ],

            // Additional Healthy Dishes
            [
                'name' => 'Grilled Tuna Steak',
                'description' => 'Grilled tuna with herbs and lemon',
                'prep_time' => 15,
                'cook_time' => 12,
                'servings' => 2,
                'difficulty' => 'Easy',
                'category' => 'Healthy',
                'calories_per_serving' => 280,
                'protein_per_serving' => 40,
                'carbs_per_serving' => 5,
                'fat_per_serving' => 10,
                'instructions' => 'Grill tuna steak with herbs and lemon',
                'is_filipino_dish' => true,
                'ingredients' => ['tuna', 'lemongrass', 'ginger', 'garlic', 'lemon'],
            ],
            [
                'name' => 'Vegetable Lumpia',
                'description' => 'Fresh vegetable spring rolls',
                'prep_time' => 30,
                'cook_time' => 0,
                'servings' => 8,
                'difficulty' => 'Medium',
                'category' => 'Healthy',
                'calories_per_serving' => 80,
                'protein_per_serving' => 4,
                'carbs_per_serving' => 12,
                'fat_per_serving' => 2,
                'instructions' => 'Wrap fresh vegetables in rice paper',
                'is_filipino_dish' => true,
                'ingredients' => ['rice paper', 'lettuce', 'carrots', 'cucumber', 'mint'],
            ],
            [
                'name' => 'Steamed Fish with Ginger',
                'description' => 'Steamed fish with ginger and soy sauce',
                'prep_time' => 10,
                'cook_time' => 15,
                'servings' => 2,
                'difficulty' => 'Easy',
                'category' => 'Healthy',
                'calories_per_serving' => 200,
                'protein_per_serving' => 35,
                'carbs_per_serving' => 5,
                'fat_per_serving' => 4,
                'instructions' => 'Steam fish with ginger and soy sauce',
                'is_filipino_dish' => true,
                'ingredients' => ['fish', 'ginger', 'soy sauce', 'garlic', 'spring onion'],
            ],
            [
                'name' => 'Mushroom Adobo',
                'description' => 'Vegetarian mushroom adobo',
                'prep_time' => 10,
                'cook_time' => 20,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Healthy',
                'calories_per_serving' => 120,
                'protein_per_serving' => 8,
                'carbs_per_serving' => 15,
                'fat_per_serving' => 4,
                'instructions' => 'Cook mushrooms in soy sauce and vinegar',
                'is_filipino_dish' => true,
                'ingredients' => ['mushrooms', 'soy sauce', 'vinegar', 'garlic', 'bay leaves'],
            ],
            [
                'name' => 'Baked Sweet Potato Fries',
                'description' => 'Healthy baked sweet potato fries',
                'prep_time' => 10,
                'cook_time' => 25,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Healthy',
                'calories_per_serving' => 150,
                'protein_per_serving' => 3,
                'carbs_per_serving' => 30,
                'fat_per_serving' => 4,
                'instructions' => 'Cut sweet potato into fries, bake until crispy',
                'is_filipino_dish' => true,
                'ingredients' => ['sweet potato', 'olive oil', 'salt', 'paprika'],
            ],
        ];

        foreach ($recipes as $recipeData) {
            $ingredients = $recipeData['ingredients'];
            unset($recipeData['ingredients']);
            
            $recipe = Recipe::firstOrCreate(
                ['name' => $recipeData['name']],
                $recipeData
            );

            // Attach ingredients to recipe
            foreach ($ingredients as $ingredientName) {
                $ingredient = Ingredient::where('name', $ingredientName)->first();
                if ($ingredient && !$recipe->ingredients()->where('ingredient_id', $ingredient->id)->exists()) {
                    $recipe->ingredients()->attach($ingredient->id, [
                        'quantity' => '1',
                        'unit' => 'piece'
                    ]);
                }
            }
        }
    }
}
