<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Recipe;
use App\Models\Ingredient;

class LastBatchRecipesSeeder extends Seeder
{
    public function run(): void
    {
        $this->createLastBatchRecipes();
    }

    private function createLastBatchRecipes(): void
    {
        // Final batch: Last 24 recipes to reach 222 total
        $recipes = [
            // Additional Filipino Main Dishes
            [
                'name' => 'Pork Adobo',
                'description' => 'Filipino pork adobo',
                'prep_time' => 15,
                'cook_time' => 30,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Filipino',
                'calories_per_serving' => 350,
                'protein_per_serving' => 26,
                'carbs_per_serving' => 8,
                'fat_per_serving' => 22,
                'instructions' => 'Marinate pork in soy sauce and vinegar, then simmer until tender',
                'is_filipino_dish' => true,
                'ingredients' => ['pork', 'soy sauce', 'vinegar', 'garlic', 'bay leaves', 'pepper'],
            ],
            [
                'name' => 'Beef Adobo',
                'description' => 'Filipino beef adobo',
                'prep_time' => 15,
                'cook_time' => 45,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Filipino',
                'calories_per_serving' => 380,
                'protein_per_serving' => 32,
                'carbs_per_serving' => 8,
                'fat_per_serving' => 24,
                'instructions' => 'Marinate beef in soy sauce and vinegar, then simmer until tender',
                'is_filipino_dish' => true,
                'ingredients' => ['beef', 'soy sauce', 'vinegar', 'garlic', 'bay leaves', 'pepper'],
            ],
            [
                'name' => 'Fish Adobo',
                'description' => 'Filipino fish adobo',
                'prep_time' => 15,
                'cook_time' => 20,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Filipino',
                'calories_per_serving' => 220,
                'protein_per_serving' => 28,
                'carbs_per_serving' => 6,
                'fat_per_serving' => 8,
                'instructions' => 'Marinate fish in soy sauce and vinegar, then simmer until tender',
                'is_filipino_dish' => true,
                'ingredients' => ['fish', 'soy sauce', 'vinegar', 'garlic', 'bay leaves', 'pepper'],
            ],
            [
                'name' => 'Squid Adobo',
                'description' => 'Filipino squid adobo',
                'prep_time' => 15,
                'cook_time' => 20,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Filipino',
                'calories_per_serving' => 200,
                'protein_per_serving' => 24,
                'carbs_per_serving' => 6,
                'fat_per_serving' => 8,
                'instructions' => 'Marinate squid in soy sauce and vinegar, then simmer until tender',
                'is_filipino_dish' => true,
                'ingredients' => ['squid', 'soy sauce', 'vinegar', 'garlic', 'bay leaves', 'pepper'],
            ],
            [
                'name' => 'Shrimp Adobo',
                'description' => 'Filipino shrimp adobo',
                'prep_time' => 15,
                'cook_time' => 15,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Filipino',
                'calories_per_serving' => 180,
                'protein_per_serving' => 22,
                'carbs_per_serving' => 6,
                'fat_per_serving' => 6,
                'instructions' => 'Marinate shrimp in soy sauce and vinegar, then simmer until tender',
                'is_filipino_dish' => true,
                'ingredients' => ['shrimp', 'soy sauce', 'vinegar', 'garlic', 'bay leaves', 'pepper'],
            ],
            [
                'name' => 'Crab Adobo',
                'description' => 'Filipino crab adobo',
                'prep_time' => 20,
                'cook_time' => 25,
                'servings' => 4,
                'difficulty' => 'Medium',
                'category' => 'Filipino',
                'calories_per_serving' => 220,
                'protein_per_serving' => 26,
                'carbs_per_serving' => 6,
                'fat_per_serving' => 10,
                'instructions' => 'Marinate crab in soy sauce and vinegar, then simmer until tender',
                'is_filipino_dish' => true,
                'ingredients' => ['crab', 'soy sauce', 'vinegar', 'garlic', 'bay leaves', 'pepper'],
            ],
            [
                'name' => 'Clam Adobo',
                'description' => 'Filipino clam adobo',
                'prep_time' => 15,
                'cook_time' => 20,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Filipino',
                'calories_per_serving' => 160,
                'protein_per_serving' => 20,
                'carbs_per_serving' => 6,
                'fat_per_serving' => 4,
                'instructions' => 'Marinate clam in soy sauce and vinegar, then simmer until tender',
                'is_filipino_dish' => true,
                'ingredients' => ['clam', 'soy sauce', 'vinegar', 'garlic', 'bay leaves', 'pepper'],
            ],
            [
                'name' => 'Mussel Adobo',
                'description' => 'Filipino mussel adobo',
                'prep_time' => 15,
                'cook_time' => 20,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Filipino',
                'calories_per_serving' => 150,
                'protein_per_serving' => 18,
                'carbs_per_serving' => 6,
                'fat_per_serving' => 4,
                'instructions' => 'Marinate mussel in soy sauce and vinegar, then simmer until tender',
                'is_filipino_dish' => true,
                'ingredients' => ['mussel', 'soy sauce', 'vinegar', 'garlic', 'bay leaves', 'pepper'],
            ],
            [
                'name' => 'Oyster Adobo',
                'description' => 'Filipino oyster adobo',
                'prep_time' => 15,
                'cook_time' => 20,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Filipino',
                'calories_per_serving' => 140,
                'protein_per_serving' => 16,
                'carbs_per_serving' => 6,
                'fat_per_serving' => 4,
                'instructions' => 'Marinate oyster in soy sauce and vinegar, then simmer until tender',
                'is_filipino_dish' => true,
                'ingredients' => ['oyster', 'soy sauce', 'vinegar', 'garlic', 'bay leaves', 'pepper'],
            ],
            [
                'name' => 'Vegetable Adobo',
                'description' => 'Filipino vegetable adobo',
                'prep_time' => 15,
                'cook_time' => 20,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Healthy',
                'calories_per_serving' => 80,
                'protein_per_serving' => 4,
                'carbs_per_serving' => 12,
                'fat_per_serving' => 2,
                'instructions' => 'Cook vegetables in soy sauce and vinegar',
                'is_filipino_dish' => true,
                'ingredients' => ['mixed vegetables', 'soy sauce', 'vinegar', 'garlic', 'bay leaves', 'pepper'],
            ],
            [
                'name' => 'Tofu Adobo',
                'description' => 'Filipino tofu adobo',
                'prep_time' => 15,
                'cook_time' => 20,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Healthy',
                'calories_per_serving' => 120,
                'protein_per_serving' => 8,
                'carbs_per_serving' => 8,
                'fat_per_serving' => 6,
                'instructions' => 'Cook tofu in soy sauce and vinegar',
                'is_filipino_dish' => true,
                'ingredients' => ['tofu', 'soy sauce', 'vinegar', 'garlic', 'bay leaves', 'pepper'],
            ],
            [
                'name' => 'Egg Adobo',
                'description' => 'Filipino egg adobo',
                'prep_time' => 15,
                'cook_time' => 20,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Filipino',
                'calories_per_serving' => 140,
                'protein_per_serving' => 10,
                'carbs_per_serving' => 6,
                'fat_per_serving' => 8,
                'instructions' => 'Cook eggs in soy sauce and vinegar',
                'is_filipino_dish' => true,
                'ingredients' => ['egg', 'soy sauce', 'vinegar', 'garlic', 'bay leaves', 'pepper'],
            ],
            [
                'name' => 'Chicken Tinola',
                'description' => 'Filipino chicken soup with ginger',
                'prep_time' => 15,
                'cook_time' => 25,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Healthy',
                'calories_per_serving' => 180,
                'protein_per_serving' => 22,
                'carbs_per_serving' => 8,
                'fat_per_serving' => 6,
                'instructions' => 'Boil chicken with ginger, onion, and vegetables',
                'is_filipino_dish' => true,
                'ingredients' => ['chicken', 'ginger', 'onion', 'garlic', 'chayote', 'morning glory'],
            ],
            [
                'name' => 'Pork Tinola',
                'description' => 'Filipino pork soup with ginger',
                'prep_time' => 15,
                'cook_time' => 30,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Healthy',
                'calories_per_serving' => 220,
                'protein_per_serving' => 20,
                'carbs_per_serving' => 8,
                'fat_per_serving' => 12,
                'instructions' => 'Boil pork with ginger, onion, and vegetables',
                'is_filipino_dish' => true,
                'ingredients' => ['pork', 'ginger', 'onion', 'garlic', 'chayote', 'morning glory'],
            ],
            [
                'name' => 'Beef Tinola',
                'description' => 'Filipino beef soup with ginger',
                'prep_time' => 15,
                'cook_time' => 45,
                'servings' => 4,
                'difficulty' => 'Medium',
                'category' => 'Healthy',
                'calories_per_serving' => 280,
                'protein_per_serving' => 28,
                'carbs_per_serving' => 8,
                'fat_per_serving' => 14,
                'instructions' => 'Boil beef with ginger, onion, and vegetables',
                'is_filipino_dish' => true,
                'ingredients' => ['beef', 'ginger', 'onion', 'garlic', 'chayote', 'morning glory'],
            ],
            [
                'name' => 'Fish Tinola',
                'description' => 'Filipino fish soup with ginger',
                'prep_time' => 15,
                'cook_time' => 20,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Healthy',
                'calories_per_serving' => 160,
                'protein_per_serving' => 24,
                'carbs_per_serving' => 6,
                'fat_per_serving' => 4,
                'instructions' => 'Boil fish with ginger, onion, and vegetables',
                'is_filipino_dish' => true,
                'ingredients' => ['fish', 'ginger', 'onion', 'garlic', 'chayote', 'morning glory'],
            ],
            [
                'name' => 'Shrimp Tinola',
                'description' => 'Filipino shrimp soup with ginger',
                'prep_time' => 15,
                'cook_time' => 15,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Healthy',
                'calories_per_serving' => 140,
                'protein_per_serving' => 20,
                'carbs_per_serving' => 6,
                'fat_per_serving' => 3,
                'instructions' => 'Boil shrimp with ginger, onion, and vegetables',
                'is_filipino_dish' => true,
                'ingredients' => ['shrimp', 'ginger', 'onion', 'garlic', 'chayote', 'morning glory'],
            ],
            [
                'name' => 'Crab Tinola',
                'description' => 'Filipino crab soup with ginger',
                'prep_time' => 20,
                'cook_time' => 25,
                'servings' => 4,
                'difficulty' => 'Medium',
                'category' => 'Healthy',
                'calories_per_serving' => 180,
                'protein_per_serving' => 22,
                'carbs_per_serving' => 6,
                'fat_per_serving' => 6,
                'instructions' => 'Boil crab with ginger, onion, and vegetables',
                'is_filipino_dish' => true,
                'ingredients' => ['crab', 'ginger', 'onion', 'garlic', 'chayote', 'morning glory'],
            ],
            [
                'name' => 'Squid Tinola',
                'description' => 'Filipino squid soup with ginger',
                'prep_time' => 15,
                'cook_time' => 20,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Healthy',
                'calories_per_serving' => 150,
                'protein_per_serving' => 20,
                'carbs_per_serving' => 6,
                'fat_per_serving' => 4,
                'instructions' => 'Boil squid with ginger, onion, and vegetables',
                'is_filipino_dish' => true,
                'ingredients' => ['squid', 'ginger', 'onion', 'garlic', 'chayote', 'morning glory'],
            ],
            [
                'name' => 'Clam Tinola',
                'description' => 'Filipino clam soup with ginger',
                'prep_time' => 15,
                'cook_time' => 20,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Healthy',
                'calories_per_serving' => 130,
                'protein_per_serving' => 18,
                'carbs_per_serving' => 6,
                'fat_per_serving' => 3,
                'instructions' => 'Boil clam with ginger, onion, and vegetables',
                'is_filipino_dish' => true,
                'ingredients' => ['clam', 'ginger', 'onion', 'garlic', 'chayote', 'morning glory'],
            ],
            [
                'name' => 'Mussel Tinola',
                'description' => 'Filipino mussel soup with ginger',
                'prep_time' => 15,
                'cook_time' => 20,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Healthy',
                'calories_per_serving' => 120,
                'protein_per_serving' => 16,
                'carbs_per_serving' => 6,
                'fat_per_serving' => 3,
                'instructions' => 'Boil mussel with ginger, onion, and vegetables',
                'is_filipino_dish' => true,
                'ingredients' => ['mussel', 'ginger', 'onion', 'garlic', 'chayote', 'morning glory'],
            ],
            [
                'name' => 'Oyster Tinola',
                'description' => 'Filipino oyster soup with ginger',
                'prep_time' => 15,
                'cook_time' => 20,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Healthy',
                'calories_per_serving' => 110,
                'protein_per_serving' => 14,
                'carbs_per_serving' => 6,
                'fat_per_serving' => 3,
                'instructions' => 'Boil oyster with ginger, onion, and vegetables',
                'is_filipino_dish' => true,
                'ingredients' => ['oyster', 'ginger', 'onion', 'garlic', 'chayote', 'morning glory'],
            ],
            [
                'name' => 'Vegetable Tinola',
                'description' => 'Filipino vegetable soup with ginger',
                'prep_time' => 15,
                'cook_time' => 20,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Healthy',
                'calories_per_serving' => 60,
                'protein_per_serving' => 3,
                'carbs_per_serving' => 10,
                'fat_per_serving' => 1,
                'instructions' => 'Boil vegetables with ginger, onion, and seasonings',
                'is_filipino_dish' => true,
                'ingredients' => ['mixed vegetables', 'ginger', 'onion', 'garlic', 'chayote', 'morning glory'],
            ],
            [
                'name' => 'Tofu Tinola',
                'description' => 'Filipino tofu soup with ginger',
                'prep_time' => 15,
                'cook_time' => 20,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Healthy',
                'calories_per_serving' => 80,
                'protein_per_serving' => 6,
                'carbs_per_serving' => 8,
                'fat_per_serving' => 3,
                'instructions' => 'Boil tofu with ginger, onion, and vegetables',
                'is_filipino_dish' => true,
                'ingredients' => ['tofu', 'ginger', 'onion', 'garlic', 'chayote', 'morning glory'],
            ],
        ];

        foreach ($recipes as $recipeData) {
            $ingredients = $recipeData['ingredients'];
            unset($recipeData['ingredients']);

            $recipe = Recipe::firstOrCreate(
                ['name' => $recipeData['name']],
                $recipeData
            );

            foreach ($ingredients as $ingredientName) {
                $ingredient = Ingredient::where('name', $ingredientName)->first();
                if ($ingredient && !$recipe->ingredients()->where('ingredient_id', $ingredient->id)->exists()) {
                    $recipe->ingredients()->attach($ingredient->id, [
                        'quantity' => '1',
                        'unit' => 'piece'
                    ]);
                }
            }
        }
    }
}
