<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Recipe;

class RecipeSeeder extends Seeder
{
    public function run(): void
    {
        $recipes = [
            [
                'name' => 'Adobo',
                'description' => 'Classic Filipino chicken adobo',
                'instructions' => 'Marinate chicken in soy sauce and vinegar. Cook until tender.',
                'prep_time' => 15,
                'cook_time' => 30,
                'servings' => 4,
                'calories' => 250,
                'protein' => 25.0,
                'carbs' => 8.0,
                'fat' => 12.0,
                'fiber' => 2.0,
                'sugar' => 4.0,
                'sodium' => 800.0,
                'difficulty' => 'Easy',
                'cuisine' => 'Filipino',
                'meal_type' => 'Main Course',
                'tags' => json_encode(['Comfort Food', 'Traditional']),
                'allergens' => json_encode(['Soy']),
            ],
            [
                'name' => 'Sinigang',
                'description' => 'Sour soup with vegetables and meat',
                'instructions' => 'Boil meat with tamarind. Add vegetables and season.',
                'prep_time' => 10,
                'cook_time' => 25,
                'servings' => 6,
                'calories' => 180,
                'protein' => 20.0,
                'carbs' => 15.0,
                'fat' => 5.0,
                'fiber' => 4.0,
                'sugar' => 8.0,
                'sodium' => 600.0,
                'difficulty' => 'Easy',
                'cuisine' => 'Filipino',
                'meal_type' => 'Soup',
                'tags' => json_encode(['Healthy', 'Comfort Food']),
                'allergens' => json_encode([]),
            ],
            [
                'name' => 'Kare-Kare',
                'description' => 'Oxtail stew with peanut sauce',
                'instructions' => 'Simmer oxtail until tender. Add vegetables and peanut sauce.',
                'prep_time' => 20,
                'cook_time' => 60,
                'servings' => 6,
                'calories' => 320,
                'protein' => 28.0,
                'carbs' => 12.0,
                'fat' => 18.0,
                'fiber' => 6.0,
                'sugar' => 5.0,
                'sodium' => 700.0,
                'difficulty' => 'Medium',
                'cuisine' => 'Filipino',
                'meal_type' => 'Main Course',
                'tags' => json_encode(['Traditional', 'Special Occasion']),
                'allergens' => json_encode(['Peanuts']),
            ],
            [
                'name' => 'Lechon Kawali',
                'description' => 'Crispy fried pork belly',
                'instructions' => 'Boil pork belly, then deep fry until crispy.',
                'prep_time' => 30,
                'cook_time' => 45,
                'servings' => 4,
                'calories' => 450,
                'protein' => 35.0,
                'carbs' => 2.0,
                'fat' => 32.0,
                'fiber' => 0.0,
                'sugar' => 1.0,
                'sodium' => 900.0,
                'difficulty' => 'Medium',
                'cuisine' => 'Filipino',
                'meal_type' => 'Main Course',
                'tags' => json_encode(['Special Occasion', 'Crispy']),
                'allergens' => json_encode([]),
            ],
            [
                'name' => 'Pancit Canton',
                'description' => 'Stir-fried noodles with vegetables',
                'instructions' => 'Stir-fry noodles with vegetables and soy sauce.',
                'prep_time' => 15,
                'cook_time' => 20,
                'servings' => 4,
                'calories' => 280,
                'protein' => 12.0,
                'carbs' => 45.0,
                'fat' => 8.0,
                'fiber' => 3.0,
                'sugar' => 6.0,
                'sodium' => 750.0,
                'difficulty' => 'Easy',
                'cuisine' => 'Filipino',
                'meal_type' => 'Main Course',
                'tags' => json_encode(['Quick', 'Vegetarian Option']),
                'allergens' => json_encode(['Wheat', 'Soy']),
            ],
            [
                'name' => 'Tinolang Manok',
                'description' => 'Chicken soup with ginger and vegetables',
                'instructions' => 'Boil chicken with ginger. Add vegetables and season with fish sauce.',
                'prep_time' => 15,
                'cook_time' => 25,
                'servings' => 4,
                'calories' => 200,
                'protein' => 22.0,
                'carbs' => 12.0,
                'fat' => 6.0,
                'fiber' => 3.0,
                'sugar' => 5.0,
                'sodium' => 650.0,
                'difficulty' => 'Easy',
                'cuisine' => 'Filipino',
                'meal_type' => 'Soup',
                'tags' => json_encode(['Healthy', 'Comfort Food']),
                'allergens' => json_encode([]),
            ],
            [
                'name' => 'Bistek Tagalog',
                'description' => 'Beef steak with onions and soy sauce',
                'instructions' => 'Marinate beef in soy sauce and calamansi. Cook with onions.',
                'prep_time' => 20,
                'cook_time' => 15,
                'servings' => 4,
                'calories' => 280,
                'protein' => 30.0,
                'carbs' => 8.0,
                'fat' => 12.0,
                'fiber' => 2.0,
                'sugar' => 6.0,
                'sodium' => 850.0,
                'difficulty' => 'Easy',
                'cuisine' => 'Filipino',
                'meal_type' => 'Main Course',
                'tags' => json_encode(['Traditional', 'Quick']),
                'allergens' => json_encode(['Soy']),
            ],
            [
                'name' => 'Pork Sisig',
                'description' => 'Sizzling pork with onions and chili',
                'instructions' => 'Cook pork until crispy. Mix with onions, chili, and calamansi.',
                'prep_time' => 25,
                'cook_time' => 20,
                'servings' => 4,
                'calories' => 320,
                'protein' => 28.0,
                'carbs' => 5.0,
                'fat' => 20.0,
                'fiber' => 1.0,
                'sugar' => 3.0,
                'sodium' => 700.0,
                'difficulty' => 'Medium',
                'cuisine' => 'Filipino',
                'meal_type' => 'Main Course',
                'tags' => json_encode(['Spicy', 'Popular']),
                'allergens' => json_encode([]),
            ],
            [
                'name' => 'Lumpia',
                'description' => 'Spring rolls with vegetables and meat',
                'instructions' => 'Wrap vegetables and meat in spring roll wrapper. Deep fry until golden.',
                'prep_time' => 30,
                'cook_time' => 15,
                'servings' => 6,
                'calories' => 180,
                'protein' => 12.0,
                'carbs' => 20.0,
                'fat' => 8.0,
                'fiber' => 2.0,
                'sugar' => 3.0,
                'sodium' => 400.0,
                'difficulty' => 'Medium',
                'cuisine' => 'Filipino',
                'meal_type' => 'Appetizer',
                'tags' => json_encode(['Crispy', 'Party Food']),
                'allergens' => json_encode(['Wheat']),
            ],
            [
                'name' => 'Halo-Halo',
                'description' => 'Mixed dessert with shaved ice and toppings',
                'instructions' => 'Layer shaved ice with various sweet toppings and evaporated milk.',
                'prep_time' => 10,
                'cook_time' => 0,
                'servings' => 1,
                'calories' => 250,
                'protein' => 6.0,
                'carbs' => 45.0,
                'fat' => 8.0,
                'fiber' => 3.0,
                'sugar' => 35.0,
                'sodium' => 50.0,
                'difficulty' => 'Easy',
                'cuisine' => 'Filipino',
                'meal_type' => 'Dessert',
                'tags' => json_encode(['Sweet', 'Refreshing']),
                'allergens' => json_encode(['Dairy']),
            ]
        ];

        foreach ($recipes as $recipe) {
            Recipe::create($recipe);
        }
    }
}

