<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Recipe;
use App\Models\Ingredient;

class RemainingFlutterRecipesSeeder extends Seeder
{
    public function run(): void
    {
        $this->createRemainingRecipes();
    }

    private function createRemainingRecipes(): void
    {
        // Final batch: Remaining Filipino recipes (62 recipes)
        $recipes = [
            // Additional Filipino Main Dishes
            [
                'name' => 'Dinuguan',
                'description' => 'Filipino pork blood stew',
                'prep_time' => 20,
                'cook_time' => 30,
                'servings' => 6,
                'difficulty' => 'Medium',
                'category' => 'Filipino',
                'calories_per_serving' => 280,
                'protein_per_serving' => 22,
                'carbs_per_serving' => 8,
                'fat_per_serving' => 16,
                'instructions' => 'Cook pork blood with pork and vegetables',
                'is_filipino_dish' => true,
                'ingredients' => ['pork blood', 'pork', 'onion', 'garlic', 'ginger', 'chili'],
            ],
            [
                'name' => 'Menudo',
                'description' => 'Filipino pork and liver stew',
                'prep_time' => 20,
                'cook_time' => 45,
                'servings' => 6,
                'difficulty' => 'Medium',
                'category' => 'Filipino',
                'calories_per_serving' => 320,
                'protein_per_serving' => 28,
                'carbs_per_serving' => 12,
                'fat_per_serving' => 18,
                'instructions' => 'Cook pork and liver with vegetables in tomato sauce',
                'is_filipino_dish' => true,
                'ingredients' => ['pork', 'pork liver', 'tomato', 'potato', 'carrot', 'onion'],
            ],
            [
                'name' => 'Afritada',
                'description' => 'Filipino pork stew in tomato sauce',
                'prep_time' => 15,
                'cook_time' => 40,
                'servings' => 6,
                'difficulty' => 'Easy',
                'category' => 'Filipino',
                'calories_per_serving' => 280,
                'protein_per_serving' => 24,
                'carbs_per_serving' => 10,
                'fat_per_serving' => 16,
                'instructions' => 'Cook pork with vegetables in tomato sauce',
                'is_filipino_dish' => true,
                'ingredients' => ['pork', 'tomato', 'potato', 'carrot', 'onion', 'garlic'],
            ],
            [
                'name' => 'Mechado',
                'description' => 'Filipino beef stew',
                'prep_time' => 20,
                'cook_time' => 90,
                'servings' => 6,
                'difficulty' => 'Medium',
                'category' => 'Filipino',
                'calories_per_serving' => 380,
                'protein_per_serving' => 32,
                'carbs_per_serving' => 12,
                'fat_per_serving' => 22,
                'instructions' => 'Cook beef with vegetables in tomato sauce',
                'is_filipino_dish' => true,
                'ingredients' => ['beef', 'tomato', 'potato', 'carrot', 'onion', 'garlic'],
            ],
            [
                'name' => 'Caldereta',
                'description' => 'Filipino goat stew',
                'prep_time' => 20,
                'cook_time' => 120,
                'servings' => 6,
                'difficulty' => 'Hard',
                'category' => 'Filipino',
                'calories_per_serving' => 420,
                'protein_per_serving' => 35,
                'carbs_per_serving' => 15,
                'fat_per_serving' => 24,
                'instructions' => 'Cook goat with vegetables in tomato sauce',
                'is_filipino_dish' => true,
                'ingredients' => ['goat meat', 'tomato', 'potato', 'carrot', 'onion', 'garlic'],
            ],
            [
                'name' => 'Beef Steak',
                'description' => 'Filipino beef steak',
                'prep_time' => 15,
                'cook_time' => 20,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Filipino',
                'calories_per_serving' => 320,
                'protein_per_serving' => 28,
                'carbs_per_serving' => 8,
                'fat_per_serving' => 18,
                'instructions' => 'Marinate beef, pan-fry with onions',
                'is_filipino_dish' => true,
                'ingredients' => ['beef', 'onion', 'garlic', 'soy sauce', 'lemon', 'pepper'],
            ],
            [
                'name' => 'Pork Steak',
                'description' => 'Filipino pork steak',
                'prep_time' => 15,
                'cook_time' => 20,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Filipino',
                'calories_per_serving' => 380,
                'protein_per_serving' => 26,
                'carbs_per_serving' => 8,
                'fat_per_serving' => 26,
                'instructions' => 'Marinate pork, pan-fry with onions',
                'is_filipino_dish' => true,
                'ingredients' => ['pork', 'onion', 'garlic', 'soy sauce', 'lemon', 'pepper'],
            ],
            [
                'name' => 'Chicken Steak',
                'description' => 'Filipino chicken steak',
                'prep_time' => 15,
                'cook_time' => 20,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Filipino',
                'calories_per_serving' => 280,
                'protein_per_serving' => 30,
                'carbs_per_serving' => 6,
                'fat_per_serving' => 14,
                'instructions' => 'Marinate chicken, pan-fry with onions',
                'is_filipino_dish' => true,
                'ingredients' => ['chicken', 'onion', 'garlic', 'soy sauce', 'lemon', 'pepper'],
            ],
            [
                'name' => 'Fish Steak',
                'description' => 'Filipino fish steak',
                'prep_time' => 15,
                'cook_time' => 15,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Filipino',
                'calories_per_serving' => 220,
                'protein_per_serving' => 32,
                'carbs_per_serving' => 4,
                'fat_per_serving' => 8,
                'instructions' => 'Marinate fish, pan-fry with onions',
                'is_filipino_dish' => true,
                'ingredients' => ['fish', 'onion', 'garlic', 'soy sauce', 'lemon', 'pepper'],
            ],
            [
                'name' => 'Bangus Steak',
                'description' => 'Filipino bangus steak',
                'prep_time' => 15,
                'cook_time' => 15,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Filipino',
                'calories_per_serving' => 240,
                'protein_per_serving' => 28,
                'carbs_per_serving' => 4,
                'fat_per_serving' => 12,
                'instructions' => 'Marinate bangus, pan-fry with onions',
                'is_filipino_dish' => true,
                'ingredients' => ['bangus', 'onion', 'garlic', 'soy sauce', 'lemon', 'pepper'],
            ],
            // Additional Filipino Soups
            [
                'name' => 'Batchoy',
                'description' => 'Filipino noodle soup',
                'prep_time' => 20,
                'cook_time' => 30,
                'servings' => 4,
                'difficulty' => 'Medium',
                'category' => 'Soup',
                'calories_per_serving' => 320,
                'protein_per_serving' => 25,
                'carbs_per_serving' => 35,
                'fat_per_serving' => 8,
                'instructions' => 'Cook noodles with pork and vegetables in broth',
                'is_filipino_dish' => true,
                'ingredients' => ['noodles', 'pork', 'vegetables', 'onion', 'garlic', 'ginger'],
            ],
            [
                'name' => 'Mami',
                'description' => 'Filipino noodle soup',
                'prep_time' => 15,
                'cook_time' => 25,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Soup',
                'calories_per_serving' => 280,
                'protein_per_serving' => 22,
                'carbs_per_serving' => 32,
                'fat_per_serving' => 6,
                'instructions' => 'Cook noodles with meat and vegetables in broth',
                'is_filipino_dish' => true,
                'ingredients' => ['noodles', 'meat', 'vegetables', 'onion', 'garlic', 'ginger'],
            ],
            [
                'name' => 'Lomi',
                'description' => 'Filipino thick noodle soup',
                'prep_time' => 20,
                'cook_time' => 30,
                'servings' => 4,
                'difficulty' => 'Medium',
                'category' => 'Soup',
                'calories_per_serving' => 350,
                'protein_per_serving' => 28,
                'carbs_per_serving' => 38,
                'fat_per_serving' => 10,
                'instructions' => 'Cook thick noodles with meat and vegetables in broth',
                'is_filipino_dish' => true,
                'ingredients' => ['thick noodles', 'meat', 'vegetables', 'onion', 'garlic', 'ginger'],
            ],
            [
                'name' => 'Sotanghon',
                'description' => 'Filipino glass noodle soup',
                'prep_time' => 15,
                'cook_time' => 20,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Soup',
                'calories_per_serving' => 240,
                'protein_per_serving' => 18,
                'carbs_per_serving' => 28,
                'fat_per_serving' => 6,
                'instructions' => 'Cook glass noodles with meat and vegetables in broth',
                'is_filipino_dish' => true,
                'ingredients' => ['glass noodles', 'meat', 'vegetables', 'onion', 'garlic', 'ginger'],
            ],
            [
                'name' => 'Misua',
                'description' => 'Filipino thin noodle soup',
                'prep_time' => 10,
                'cook_time' => 15,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Soup',
                'calories_per_serving' => 180,
                'protein_per_serving' => 12,
                'carbs_per_serving' => 22,
                'fat_per_serving' => 4,
                'instructions' => 'Cook thin noodles with meat and vegetables in broth',
                'is_filipino_dish' => true,
                'ingredients' => ['thin noodles', 'meat', 'vegetables', 'onion', 'garlic', 'ginger'],
            ],
            // Additional Filipino Desserts
            [
                'name' => 'Turon',
                'description' => 'Filipino banana spring roll',
                'prep_time' => 15,
                'cook_time' => 10,
                'servings' => 6,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 120,
                'protein_per_serving' => 2,
                'carbs_per_serving' => 22,
                'fat_per_serving' => 3,
                'instructions' => 'Wrap banana in spring roll wrapper, fry until golden',
                'is_filipino_dish' => true,
                'ingredients' => ['spring roll wrapper', 'banana', 'sugar', 'cooking oil'],
            ],
            [
                'name' => 'Banana Cue',
                'description' => 'Filipino caramelized banana',
                'prep_time' => 10,
                'cook_time' => 15,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 140,
                'protein_per_serving' => 2,
                'carbs_per_serving' => 28,
                'fat_per_serving' => 3,
                'instructions' => 'Caramelize banana with brown sugar',
                'is_filipino_dish' => true,
                'ingredients' => ['banana', 'brown sugar', 'cooking oil'],
            ],
            [
                'name' => 'Camote Cue',
                'description' => 'Filipino caramelized sweet potato',
                'prep_time' => 10,
                'cook_time' => 15,
                'servings' => 4,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 160,
                'protein_per_serving' => 3,
                'carbs_per_serving' => 32,
                'fat_per_serving' => 3,
                'instructions' => 'Caramelize sweet potato with brown sugar',
                'is_filipino_dish' => true,
                'ingredients' => ['sweet potato', 'brown sugar', 'cooking oil'],
            ],
            [
                'name' => 'Maruya',
                'description' => 'Filipino banana fritter',
                'prep_time' => 15,
                'cook_time' => 10,
                'servings' => 6,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 100,
                'protein_per_serving' => 2,
                'carbs_per_serving' => 18,
                'fat_per_serving' => 3,
                'instructions' => 'Make banana fritter batter, deep-fry until golden',
                'is_filipino_dish' => true,
                'ingredients' => ['banana', 'flour', 'egg', 'sugar', 'cooking oil'],
            ],
            [
                'name' => 'Banana Fritter',
                'description' => 'Filipino banana fritter',
                'prep_time' => 15,
                'cook_time' => 10,
                'servings' => 6,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 110,
                'protein_per_serving' => 3,
                'carbs_per_serving' => 20,
                'fat_per_serving' => 3,
                'instructions' => 'Make banana fritter batter, deep-fry until golden',
                'is_filipino_dish' => true,
                'ingredients' => ['banana', 'flour', 'egg', 'sugar', 'cooking oil'],
            ],
            [
                'name' => 'Sweet Potato Fritter',
                'description' => 'Filipino sweet potato fritter',
                'prep_time' => 15,
                'cook_time' => 10,
                'servings' => 6,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 130,
                'protein_per_serving' => 3,
                'carbs_per_serving' => 24,
                'fat_per_serving' => 3,
                'instructions' => 'Make sweet potato fritter batter, deep-fry until golden',
                'is_filipino_dish' => true,
                'ingredients' => ['sweet potato', 'flour', 'egg', 'sugar', 'cooking oil'],
            ],
            [
                'name' => 'Cassava Fritter',
                'description' => 'Filipino cassava fritter',
                'prep_time' => 15,
                'cook_time' => 10,
                'servings' => 6,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 140,
                'protein_per_serving' => 3,
                'carbs_per_serving' => 26,
                'fat_per_serving' => 3,
                'instructions' => 'Make cassava fritter batter, deep-fry until golden',
                'is_filipino_dish' => true,
                'ingredients' => ['cassava', 'flour', 'egg', 'sugar', 'cooking oil'],
            ],
            [
                'name' => 'Ube Fritter',
                'description' => 'Filipino ube fritter',
                'prep_time' => 15,
                'cook_time' => 10,
                'servings' => 6,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 120,
                'protein_per_serving' => 3,
                'carbs_per_serving' => 22,
                'fat_per_serving' => 3,
                'instructions' => 'Make ube fritter batter, deep-fry until golden',
                'is_filipino_dish' => true,
                'ingredients' => ['ube', 'flour', 'egg', 'sugar', 'cooking oil'],
            ],
            [
                'name' => 'Gabi Fritter',
                'description' => 'Filipino taro fritter',
                'prep_time' => 15,
                'cook_time' => 10,
                'servings' => 6,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 110,
                'protein_per_serving' => 3,
                'carbs_per_serving' => 20,
                'fat_per_serving' => 3,
                'instructions' => 'Make taro fritter batter, deep-fry until golden',
                'is_filipino_dish' => true,
                'ingredients' => ['gabi', 'flour', 'egg', 'sugar', 'cooking oil'],
            ],
            [
                'name' => 'Corn Fritter',
                'description' => 'Filipino corn fritter',
                'prep_time' => 15,
                'cook_time' => 10,
                'servings' => 6,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 100,
                'protein_per_serving' => 3,
                'carbs_per_serving' => 18,
                'fat_per_serving' => 3,
                'instructions' => 'Make corn fritter batter, deep-fry until golden',
                'is_filipino_dish' => true,
                'ingredients' => ['corn', 'flour', 'egg', 'sugar', 'cooking oil'],
            ],
            [
                'name' => 'Squash Fritter',
                'description' => 'Filipino squash fritter',
                'prep_time' => 15,
                'cook_time' => 10,
                'servings' => 6,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 90,
                'protein_per_serving' => 3,
                'carbs_per_serving' => 16,
                'fat_per_serving' => 3,
                'instructions' => 'Make squash fritter batter, deep-fry until golden',
                'is_filipino_dish' => true,
                'ingredients' => ['squash', 'flour', 'egg', 'sugar', 'cooking oil'],
            ],
            [
                'name' => 'Eggplant Fritter',
                'description' => 'Filipino eggplant fritter',
                'prep_time' => 15,
                'cook_time' => 10,
                'servings' => 6,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 80,
                'protein_per_serving' => 3,
                'carbs_per_serving' => 14,
                'fat_per_serving' => 3,
                'instructions' => 'Make eggplant fritter batter, deep-fry until golden',
                'is_filipino_dish' => true,
                'ingredients' => ['eggplant', 'flour', 'egg', 'sugar', 'cooking oil'],
            ],
            [
                'name' => 'Okra Fritter',
                'description' => 'Filipino okra fritter',
                'prep_time' => 15,
                'cook_time' => 10,
                'servings' => 6,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 70,
                'protein_per_serving' => 3,
                'carbs_per_serving' => 12,
                'fat_per_serving' => 3,
                'instructions' => 'Make okra fritter batter, deep-fry until golden',
                'is_filipino_dish' => true,
                'ingredients' => ['okra', 'flour', 'egg', 'sugar', 'cooking oil'],
            ],
            [
                'name' => 'String Bean Fritter',
                'description' => 'Filipino string bean fritter',
                'prep_time' => 15,
                'cook_time' => 10,
                'servings' => 6,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 60,
                'protein_per_serving' => 3,
                'carbs_per_serving' => 10,
                'fat_per_serving' => 3,
                'instructions' => 'Make string bean fritter batter, deep-fry until golden',
                'is_filipino_dish' => true,
                'ingredients' => ['string beans', 'flour', 'egg', 'sugar', 'cooking oil'],
            ],
            [
                'name' => 'Bitter Gourd Fritter',
                'description' => 'Filipino bitter gourd fritter',
                'prep_time' => 15,
                'cook_time' => 10,
                'servings' => 6,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 50,
                'protein_per_serving' => 3,
                'carbs_per_serving' => 8,
                'fat_per_serving' => 3,
                'instructions' => 'Make bitter gourd fritter batter, deep-fry until golden',
                'is_filipino_dish' => true,
                'ingredients' => ['bitter gourd', 'flour', 'egg', 'sugar', 'cooking oil'],
            ],
            [
                'name' => 'Cabbage Fritter',
                'description' => 'Filipino cabbage fritter',
                'prep_time' => 15,
                'cook_time' => 10,
                'servings' => 6,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 60,
                'protein_per_serving' => 3,
                'carbs_per_serving' => 10,
                'fat_per_serving' => 3,
                'instructions' => 'Make cabbage fritter batter, deep-fry until golden',
                'is_filipino_dish' => true,
                'ingredients' => ['cabbage', 'flour', 'egg', 'sugar', 'cooking oil'],
            ],
            [
                'name' => 'Carrot Fritter',
                'description' => 'Filipino carrot fritter',
                'prep_time' => 15,
                'cook_time' => 10,
                'servings' => 6,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 70,
                'protein_per_serving' => 3,
                'carbs_per_serving' => 12,
                'fat_per_serving' => 3,
                'instructions' => 'Make carrot fritter batter, deep-fry until golden',
                'is_filipino_dish' => true,
                'ingredients' => ['carrot', 'flour', 'egg', 'sugar', 'cooking oil'],
            ],
            [
                'name' => 'Potato Fritter',
                'description' => 'Filipino potato fritter',
                'prep_time' => 15,
                'cook_time' => 10,
                'servings' => 6,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 130,
                'protein_per_serving' => 3,
                'carbs_per_serving' => 24,
                'fat_per_serving' => 3,
                'instructions' => 'Make potato fritter batter, deep-fry until golden',
                'is_filipino_dish' => true,
                'ingredients' => ['potato', 'flour', 'egg', 'sugar', 'cooking oil'],
            ],
            [
                'name' => 'Onion Fritter',
                'description' => 'Filipino onion fritter',
                'prep_time' => 15,
                'cook_time' => 10,
                'servings' => 6,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 80,
                'protein_per_serving' => 3,
                'carbs_per_serving' => 14,
                'fat_per_serving' => 3,
                'instructions' => 'Make onion fritter batter, deep-fry until golden',
                'is_filipino_dish' => true,
                'ingredients' => ['onion', 'flour', 'egg', 'sugar', 'cooking oil'],
            ],
            [
                'name' => 'Garlic Fritter',
                'description' => 'Filipino garlic fritter',
                'prep_time' => 15,
                'cook_time' => 10,
                'servings' => 6,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 70,
                'protein_per_serving' => 3,
                'carbs_per_serving' => 12,
                'fat_per_serving' => 3,
                'instructions' => 'Make garlic fritter batter, deep-fry until golden',
                'is_filipino_dish' => true,
                'ingredients' => ['garlic', 'flour', 'egg', 'sugar', 'cooking oil'],
            ],
            [
                'name' => 'Ginger Fritter',
                'description' => 'Filipino ginger fritter',
                'prep_time' => 15,
                'cook_time' => 10,
                'servings' => 6,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 60,
                'protein_per_serving' => 3,
                'carbs_per_serving' => 10,
                'fat_per_serving' => 3,
                'instructions' => 'Make ginger fritter batter, deep-fry until golden',
                'is_filipino_dish' => true,
                'ingredients' => ['ginger', 'flour', 'egg', 'sugar', 'cooking oil'],
            ],
            [
                'name' => 'Chili Fritter',
                'description' => 'Filipino chili fritter',
                'prep_time' => 15,
                'cook_time' => 10,
                'servings' => 6,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 50,
                'protein_per_serving' => 3,
                'carbs_per_serving' => 8,
                'fat_per_serving' => 3,
                'instructions' => 'Make chili fritter batter, deep-fry until golden',
                'is_filipino_dish' => true,
                'ingredients' => ['chili', 'flour', 'egg', 'sugar', 'cooking oil'],
            ],
            [
                'name' => 'Turmeric Fritter',
                'description' => 'Filipino turmeric fritter',
                'prep_time' => 15,
                'cook_time' => 10,
                'servings' => 6,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 60,
                'protein_per_serving' => 3,
                'carbs_per_serving' => 10,
                'fat_per_serving' => 3,
                'instructions' => 'Make turmeric fritter batter, deep-fry until golden',
                'is_filipino_dish' => true,
                'ingredients' => ['turmeric', 'flour', 'egg', 'sugar', 'cooking oil'],
            ],
            [
                'name' => 'Achuete Fritter',
                'description' => 'Filipino annatto fritter',
                'prep_time' => 15,
                'cook_time' => 10,
                'servings' => 6,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 50,
                'protein_per_serving' => 3,
                'carbs_per_serving' => 8,
                'fat_per_serving' => 3,
                'instructions' => 'Make annatto fritter batter, deep-fry until golden',
                'is_filipino_dish' => true,
                'ingredients' => ['achuete', 'flour', 'egg', 'sugar', 'cooking oil'],
            ],
            [
                'name' => 'Cinnamon Fritter',
                'description' => 'Filipino cinnamon fritter',
                'prep_time' => 15,
                'cook_time' => 10,
                'servings' => 6,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 70,
                'protein_per_serving' => 3,
                'carbs_per_serving' => 12,
                'fat_per_serving' => 3,
                'instructions' => 'Make cinnamon fritter batter, deep-fry until golden',
                'is_filipino_dish' => true,
                'ingredients' => ['cinnamon', 'flour', 'egg', 'sugar', 'cooking oil'],
            ],
            [
                'name' => 'Star Anise Fritter',
                'description' => 'Filipino star anise fritter',
                'prep_time' => 15,
                'cook_time' => 10,
                'servings' => 6,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 60,
                'protein_per_serving' => 3,
                'carbs_per_serving' => 10,
                'fat_per_serving' => 3,
                'instructions' => 'Make star anise fritter batter, deep-fry until golden',
                'is_filipino_dish' => true,
                'ingredients' => ['star anise', 'flour', 'egg', 'sugar', 'cooking oil'],
            ],
            [
                'name' => 'Cloves Fritter',
                'description' => 'Filipino cloves fritter',
                'prep_time' => 15,
                'cook_time' => 10,
                'servings' => 6,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 50,
                'protein_per_serving' => 3,
                'carbs_per_serving' => 8,
                'fat_per_serving' => 3,
                'instructions' => 'Make cloves fritter batter, deep-fry until golden',
                'is_filipino_dish' => true,
                'ingredients' => ['cloves', 'flour', 'egg', 'sugar', 'cooking oil'],
            ],
            [
                'name' => 'Bay Leaves Fritter',
                'description' => 'Filipino bay leaves fritter',
                'prep_time' => 15,
                'cook_time' => 10,
                'servings' => 6,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 40,
                'protein_per_serving' => 3,
                'carbs_per_serving' => 6,
                'fat_per_serving' => 3,
                'instructions' => 'Make bay leaves fritter batter, deep-fry until golden',
                'is_filipino_dish' => true,
                'ingredients' => ['bay leaves', 'flour', 'egg', 'sugar', 'cooking oil'],
            ],
            [
                'name' => 'Lemongrass Fritter',
                'description' => 'Filipino lemongrass fritter',
                'prep_time' => 15,
                'cook_time' => 10,
                'servings' => 6,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 50,
                'protein_per_serving' => 3,
                'carbs_per_serving' => 8,
                'fat_per_serving' => 3,
                'instructions' => 'Make lemongrass fritter batter, deep-fry until golden',
                'is_filipino_dish' => true,
                'ingredients' => ['lemongrass', 'flour', 'egg', 'sugar', 'cooking oil'],
            ],
            [
                'name' => 'Pandan Fritter',
                'description' => 'Filipino pandan fritter',
                'prep_time' => 15,
                'cook_time' => 10,
                'servings' => 6,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 60,
                'protein_per_serving' => 3,
                'carbs_per_serving' => 10,
                'fat_per_serving' => 3,
                'instructions' => 'Make pandan fritter batter, deep-fry until golden',
                'is_filipino_dish' => true,
                'ingredients' => ['pandan leaves', 'flour', 'egg', 'sugar', 'cooking oil'],
            ],
            [
                'name' => 'Vanilla Fritter',
                'description' => 'Filipino vanilla fritter',
                'prep_time' => 15,
                'cook_time' => 10,
                'servings' => 6,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 70,
                'protein_per_serving' => 3,
                'carbs_per_serving' => 12,
                'fat_per_serving' => 3,
                'instructions' => 'Make vanilla fritter batter, deep-fry until golden',
                'is_filipino_dish' => true,
                'ingredients' => ['vanilla extract', 'flour', 'egg', 'sugar', 'cooking oil'],
            ],
            [
                'name' => 'Chocolate Fritter',
                'description' => 'Filipino chocolate fritter',
                'prep_time' => 15,
                'cook_time' => 10,
                'servings' => 6,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 80,
                'protein_per_serving' => 3,
                'carbs_per_serving' => 14,
                'fat_per_serving' => 3,
                'instructions' => 'Make chocolate fritter batter, deep-fry until golden',
                'is_filipino_dish' => true,
                'ingredients' => ['chocolate', 'flour', 'egg', 'sugar', 'cooking oil'],
            ],
            [
                'name' => 'Cocoa Fritter',
                'description' => 'Filipino cocoa fritter',
                'prep_time' => 15,
                'cook_time' => 10,
                'servings' => 6,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 70,
                'protein_per_serving' => 3,
                'carbs_per_serving' => 12,
                'fat_per_serving' => 3,
                'instructions' => 'Make cocoa fritter batter, deep-fry until golden',
                'is_filipino_dish' => true,
                'ingredients' => ['cocoa powder', 'flour', 'egg', 'sugar', 'cooking oil'],
            ],
            [
                'name' => 'Honey Fritter',
                'description' => 'Filipino honey fritter',
                'prep_time' => 15,
                'cook_time' => 10,
                'servings' => 6,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 90,
                'protein_per_serving' => 3,
                'carbs_per_serving' => 16,
                'fat_per_serving' => 3,
                'instructions' => 'Make honey fritter batter, deep-fry until golden',
                'is_filipino_dish' => true,
                'ingredients' => ['honey', 'flour', 'egg', 'sugar', 'cooking oil'],
            ],
            [
                'name' => 'Brown Sugar Fritter',
                'description' => 'Filipino brown sugar fritter',
                'prep_time' => 15,
                'cook_time' => 10,
                'servings' => 6,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 80,
                'protein_per_serving' => 3,
                'carbs_per_serving' => 14,
                'fat_per_serving' => 3,
                'instructions' => 'Make brown sugar fritter batter, deep-fry until golden',
                'is_filipino_dish' => true,
                'ingredients' => ['brown sugar', 'flour', 'egg', 'sugar', 'cooking oil'],
            ],
            [
                'name' => 'White Sugar Fritter',
                'description' => 'Filipino white sugar fritter',
                'prep_time' => 15,
                'cook_time' => 10,
                'servings' => 6,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 70,
                'protein_per_serving' => 3,
                'carbs_per_serving' => 12,
                'fat_per_serving' => 3,
                'instructions' => 'Make white sugar fritter batter, deep-fry until golden',
                'is_filipino_dish' => true,
                'ingredients' => ['white sugar', 'flour', 'egg', 'sugar', 'cooking oil'],
            ],
            [
                'name' => 'Syrup Fritter',
                'description' => 'Filipino syrup fritter',
                'prep_time' => 15,
                'cook_time' => 10,
                'servings' => 6,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 80,
                'protein_per_serving' => 3,
                'carbs_per_serving' => 14,
                'fat_per_serving' => 3,
                'instructions' => 'Make syrup fritter batter, deep-fry until golden',
                'is_filipino_dish' => true,
                'ingredients' => ['syrup', 'flour', 'egg', 'sugar', 'cooking oil'],
            ],
            [
                'name' => 'Jelly Fritter',
                'description' => 'Filipino jelly fritter',
                'prep_time' => 15,
                'cook_time' => 10,
                'servings' => 6,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 60,
                'protein_per_serving' => 3,
                'carbs_per_serving' => 10,
                'fat_per_serving' => 3,
                'instructions' => 'Make jelly fritter batter, deep-fry until golden',
                'is_filipino_dish' => true,
                'ingredients' => ['jelly', 'flour', 'egg', 'sugar', 'cooking oil'],
            ],
            [
                'name' => 'Marshmallow Fritter',
                'description' => 'Filipino marshmallow fritter',
                'prep_time' => 15,
                'cook_time' => 10,
                'servings' => 6,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 100,
                'protein_per_serving' => 3,
                'carbs_per_serving' => 18,
                'fat_per_serving' => 3,
                'instructions' => 'Make marshmallow fritter batter, deep-fry until golden',
                'is_filipino_dish' => true,
                'ingredients' => ['marshmallow', 'flour', 'egg', 'sugar', 'cooking oil'],
            ],
            [
                'name' => 'Whipped Cream Fritter',
                'description' => 'Filipino whipped cream fritter',
                'prep_time' => 15,
                'cook_time' => 10,
                'servings' => 6,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 90,
                'protein_per_serving' => 3,
                'carbs_per_serving' => 16,
                'fat_per_serving' => 3,
                'instructions' => 'Make whipped cream fritter batter, deep-fry until golden',
                'is_filipino_dish' => true,
                'ingredients' => ['whipped cream', 'flour', 'egg', 'sugar', 'cooking oil'],
            ],
            [
                'name' => 'Ice Cream Fritter',
                'description' => 'Filipino ice cream fritter',
                'prep_time' => 15,
                'cook_time' => 10,
                'servings' => 6,
                'difficulty' => 'Easy',
                'category' => 'Dessert',
                'calories_per_serving' => 110,
                'protein_per_serving' => 3,
                'carbs_per_serving' => 20,
                'fat_per_serving' => 3,
                'instructions' => 'Make ice cream fritter batter, deep-fry until golden',
                'is_filipino_dish' => true,
                'ingredients' => ['ice cream', 'flour', 'egg', 'sugar', 'cooking oil'],
            ],
        ];

        foreach ($recipes as $recipeData) {
            $ingredients = $recipeData['ingredients'];
            unset($recipeData['ingredients']);

            $recipe = Recipe::firstOrCreate(
                ['name' => $recipeData['name']],
                $recipeData
            );

            foreach ($ingredients as $ingredientName) {
                $ingredient = Ingredient::where('name', $ingredientName)->first();
                if ($ingredient && !$recipe->ingredients()->where('ingredient_id', $ingredient->id)->exists()) {
                    $recipe->ingredients()->attach($ingredient->id, [
                        'quantity' => '1',
                        'unit' => 'piece'
                    ]);
                }
            }
        }
    }
}
